### ISSUE TITLE
There is no leader for this topic-partition as we are in the middle of a leadership election

### ISSUE THREAD

**Issue by alex-jesper** [tulios/kafkajs#1008]
**Describe the bug**
With a kafka started with KAFKA_AUTO_CREATE_TOPICS_ENABLE, I get "There is no leader for this topic-partition as we are in the middle of a leadership election" errors when sending a message on a non existing topic.

Also described [here](https://stackoverflow.com/questions/63566301/waiting-for-leadership-elections-in-kafkajs)

I use the admin tool to create non existing topic as a workaround:

```
await this.admin.connect()
const existingTopics = await this.admin.listTopics()
if (!existingTopics.some((topic) => topic === topics.create.event)) {
  await this.admin.createTopics({
    waitForLeaders: true,
    topics: [
      { topic: topics.create.event }
    ]
  })
}
await this.admin.disconnect()
```
But since I have auto create topics on it does not really make sense to create them upfront.

**To Reproduce**
Start a kafka with no topics send a message with a non-existing topic, and get the error.

**Expected behavior**
No error produced

**Observed behavior**
The error is produced

**Feature request**
Make producer.send() waitForLeaders like admin.createTopics() does

**Environment:**
 - KafkaJS version 1.15.0
 - Kafka version latest
 - NodeJS version 15.5.1

**Comment by tulios** [comment]
Hi @alex-jesper, this behavior is expected, that's a normal flow for Kafka. Even with auto-creation enabled, the topic doesn't have a leader when created and has to conduct a leader election. This is logged as an error because it is an error but it is handled inside KafkaJS, it's a retriable error.

**Comment by alex-jesper** [comment]
Hi @tulios,
Thank you for the clarification. Could you describe if I could handle the error in a better way? Maybe not creating the topics upfront but instead retry in some way.
What would be the best-practice solution?

**Comment by tulios** [comment]
@alex-jesper the producer should automatically retry this kind of error, you might just see them in the logs.

**Comment by fnordian** [comment]
Can the log be turned off? If everything is ok, then there shouldn't be error messages in the log.

**Comment by okanaslan** [comment]
@tulios the producer automatically retries; however after retry limit exceeds it throws error and crashes. You you have any suggestions about this issue?

```
/usr/app/node_modules/kafkajs/src/protocol/error.js:581
--
Thu, Jan 20 2022 1:59:20 pm | return new KafkaJSProtocolError(errorCodes.find(e => e.code === code) \|\| unknownErrorCode(code))
Thu, Jan 20 2022 1:59:20 pm | ^
Thu, Jan 20 2022 1:59:20 pm | KafkaJSNonRetriableError
Thu, Jan 20 2022 1:59:20 pm | Caused by: KafkaJSProtocolError: There is no leader for this topic-partition as we are in the middle of a leadership election
Thu, Jan 20 2022 1:59:20 pm | at createErrorFromCode (/usr/app/node_modules/kafkajs/src/protocol/error.js:581:10)
Thu, Jan 20 2022 1:59:20 pm | at Object.parse (/usr/app/node_modules/kafkajs/src/protocol/requests/metadata/v0/response.js:66:11)
Thu, Jan 20 2022 1:59:20 pm | at Connection.send (/usr/app/node_modules/kafkajs/src/network/connection.js:336:35)
Thu, Jan 20 2022 1:59:20 pm | at processTicksAndRejections (node:internal/process/task_queues:96:5)
Thu, Jan 20 2022 1:59:20 pm | at async Broker.[private:Broker:sendRequest] (/usr/app/node_modules/kafkajs/src/broker/index.js:890:14)
Thu, Jan 20 2022 1:59:20 pm | at async Broker.metadata (/usr/app/node_modules/kafkajs/src/broker/index.js:191:12)
Thu, Jan 20 2022 1:59:20 pm | at async /usr/app/node_modules/kafkajs/src/cluster/brokerPool.js:155:25
Thu, Jan 20 2022 1:59:20 pm | at async /usr/app/node_modules/kafkajs/src/cluster/index.js:152:9
Thu, Jan 20 2022 1:59:20 pm | at async Object.listTopics (/usr/app/node_modules/kafkajs/src/admin/index.js:103:31) {
Thu, Jan 20 2022 1:59:20 pm | name: 'KafkaJSNumberOfRetriesExceeded',
Thu, Jan 20 2022 1:59:20 pm | retriable: false,
Thu, Jan 20 2022 1:59:20 pm | helpUrl: undefined,
Thu, Jan 20 2022 1:59:20 pm | originalError: KafkaJSProtocolError: There is no leader for this topic-partition as we are in the middle of a leadership election
Thu, Jan 20 2022 1:59:20 pm | at createErrorFromCode (/usr/app/node_modules/kafkajs/src/protocol/error.js:581:10)
Thu, Jan 20 2022 1:59:20 pm | at Object.parse (/usr/app/node_modules/kafkajs/src/protocol/requests/metadata/v0/response.js:66:11)
Thu, Jan 20 2022 1:59:20 pm | at Connection.send (/usr/app/node_modules/kafkajs/src/network/connection.js:336:35)
Thu, Jan 20 2022 1:59:20 pm | at processTicksAndRejections (node:internal/process/task_queues:96:5)
Thu, Jan 20 2022 1:59:20 pm | at async Broker.[private:Broker:sendRequest] (/usr/app/node_modules/kafkajs/src/broker/index.js:890:14)
Thu, Jan 20 2022 1:59:20 pm | at async Broker.metadata (/usr/app/node_modules/kafkajs/src/broker/index.js:191:12)
Thu, Jan 20 2022 1:59:20 pm | at async /usr/app/node_modules/kafkajs/src/cluster/brokerPool.js:155:25
Thu, Jan 20 2022 1:59:20 pm | at async /usr/app/node_modules/kafkajs/src/cluster/index.js:152:9
Thu, Jan 20 2022 1:59:20 pm | at async Object.listTopics (/usr/app/node_modules/kafkajs/src/admin/index.js:103:31) {
Thu, Jan 20 2022 1:59:20 pm | retriable: true,
Thu, Jan 20 2022 1:59:20 pm | helpUrl: undefined,
Thu, Jan 20 2022 1:59:20 pm | type: 'LEADER_NOT_AVAILABLE',
Thu, Jan 20 2022 1:59:20 pm | code: 5
Thu, Jan 20 2022 1:59:20 pm | },
Thu, Jan 20 2022 1:59:20 pm | retryCount: 8,
Thu, Jan 20 2022 1:59:20 pm | retryTime: 30000
Thu, Jan 20 2022 1:59:20 pm | }
```

**Comment by zaro** [comment]
This message got me chasing problems for quite some time, but indeed even though the message is printed, the message is sent as expected.

**Comment by Clashsoft** [comment]
For me this crashes the whole service after about 7 tries.

```
KafkaJSNonRetriableError
  Caused by: KafkaJSProtocolError: There is no leader for this topic-partition as we are in the middle of a leadership election
```

And after the restart it does it again. So there is never any leader.
