### ISSUE TITLE
Consumer did not restart automatically on crash

### ISSUE THREAD

**Issue by boedy** [tulios/kafkajs#1011]
I have multiple node service which I run using KafkaJS. Sometimes my consumer stops consuming if there is any error with one of the brokers. Not all consumers seem to be affected though. Based on the logs, it seems the consumer crashes, but doesn't restart. I've included the logs below.

I've sticked to the default configuration:
```js
const kafka = new Kafka({
    clientId: os.hostname(),
    brokers: process.env.KAFKA_BROKERS.split(','),
});
```

I'm not sure if this is a bug in the version I'm using (1.8.0) or if its a misconfiguration on my side. I could not find anything in the release changelogs which gave me an indication this was addresses in a later version. Please advise 🙏.

```
{"level":"ERROR","timestamp":"2021-01-25T17:19:25.167Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNumberOfRetriesExceeded: Not connected","groupId":"analytics-service","retryCount":5,"stack":"KafkaJSNumberOfRetriesExceeded\n  Caused by: KafkaJSConnectionError: Not connected\n    at Connection.failIfNotConnected (/app/node_modules/kafkajs/src/network/connection.js:341:13)\n    at Connection.send (/app/node_modules/kafkajs/src/network/connection.js:264:10)\n    at Broker.heartbeat (/app/node_modules/kafkajs/src/broker/index.js:304:34)\n    at ConsumerGroup.heartbeat (/app/node_modules/kafkajs/src/consumer/consumerGroup.js:308:30)\n    at Runner.processEachMessage (/app/node_modules/kafkajs/src/consumer/runner.js:177:32)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"level":"ERROR","timestamp":"2021-01-25T17:19:25.168Z","logger":"kafkajs","message":"[Consumer] Restarting the consumer in 8660ms","retryCount":5,"retryTime":8660,"groupId":"analytics-service"}
{"level":"INFO","timestamp":"2021-01-25T17:19:25.168Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"analytics-service"}
{"level":"INFO","timestamp":"2021-01-25T17:19:33.829Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"analytics-service"}
{"level":"ERROR","timestamp":"2021-01-25T17:19:33.836Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-2.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":1772582,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:34.147Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-2.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":1772583,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:34.781Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-2.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":1772584,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:36.042Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-2.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":1772585,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:38.111Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-2.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":1772586,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:42.400Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-2.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":1772587,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:42.405Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-1.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":0,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:42.755Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-1.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":1,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:43.489Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-1.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":2,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:44.816Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-1.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":3,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:47.012Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-1.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":4,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:50.805Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 1)","broker":"broker-1.broker-headless.kafka:9092","clientId":"analytics-service-76ff7bf4cd-npl9d","error":"The group coordinator is not available","correlationId":5,"size":22}
{"level":"ERROR","timestamp":"2021-01-25T17:19:50.805Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSGroupCoordinatorNotFound: Failed to find group coordinator","groupId":"analytics-service","stack":"KafkaJSGroupCoordinatorNotFound: Failed to find group coordinator\n    at Cluster.findGroupCoordinatorMetadata (/app/node_modules/kafkajs/src/cluster/index.js:351:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:189:7)"}
{"level":"INFO","timestamp":"2021-01-25T17:19:50.806Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"analytics-service"}
// No further KafkaJS logs seen after this last message
```

**Environment:**
Production kubernetes
 - OS: Alpine Linux
 - KafkaJS version 1.8.0
 - Kafka version: 2.1.0
 - NodeJS version v8.17.0

**Comment by tulios** [comment]
@boedy try to update to the latest version, but 1.8.1 addresses this problem https://github.com/tulios/kafkajs/blob/master/CHANGELOG.md#181---2019-06-25

The client can't find the coordinator because the metadata is not fresh, which was fixed on 1.8.1

**Comment by boedy** [comment]
Thanks @tulios. I've updated my clients to the latest versions. I'll close this ticket for now. If I run into this issue again, I'll follow up :)

**Comment by nikitakalnov** [comment]
I have encountered the same problem using version 1.15.0:
```
[Consumer] Crash: KafkaJSGroupCoordinatorNotFound: Failed to find group coordinator
  | Sep 2, 2022 @ 12:54:47.708 | - | [Consumer] Stopped
  | Sep 2, 2022 @ 12:54:47.552 | - | [Consumer] Starting

```
That's the last logs, consumer did not try to restart automatically.
