### ISSUE TITLE
Gracefull disconnect 

### ISSUE THREAD

**Issue by artur-ma** [tulios/kafkajs#1017]
**Is your feature request related to a problem? Please describe.**
We are calling "disconnect" manually on our nodeJs app when k8s pods go down, but during that process, we get some errors that look like related to not properly handle messages that are already "in-flight" 

```
"stack"  :  "Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:253:14)
    at Socket.Writable.write (_stream_writable.js:302:5)
    at Object.sendRequest (/home/app/node_modules/kafkajs/src/network/connection.js:312:27)
    at SocketRequest.send [as sendRequest] (/home/app/node_modules/kafkajs/src/network/requestQueue/index.js:139:23)
    at SocketRequest.send (/home/app/node_modules/kafkajs/src/network/requestQueue/socketRequest.js:85:10)
    at RequestQueue.sendSocketRequest (/home/app/node_modules/kafkajs/src/network/requestQueue/index.js:168:19)
    at RequestQueue.push (/home/app/node_modules/kafkajs/src/network/requestQueue/index.js:148:12)
    at /home/app/node_modules/kafkajs/src/network/connection.js:307:29
    at new Promise (<anonymous>)
    at sendRequest (/home/app/node_modules/kafkajs/src/network/connection.js:302:14)" ,
 ```
 
 and 
 
 
 ```
 "stack"  :  "KafkaJSNonRetriableError
  Caused by: TypeError: Cannot read property '18' of undefined
    at /home/app/node_modules/kafkajs/src/consumer/offsetManager/index.js:281:60
    at Array.filter (<anonymous>)
    at /home/app/node_modules/kafkajs/src/consumer/offsetManager/index.js:288:12
    at Array.map (<anonymous>)
    at OffsetManager.resolveOffsets (/home/app/node_modules/kafkajs/src/consumer/offsetManager/index.js:285:8)
    at ConsumerGroup.fetch (/home/app/node_modules/kafkajs/src/consumer/consumerGroup.js:434:32)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:412:9)
    at process.topLevelDomainCallback (domain.js:130:23)
    at async Runner.fetch (/home/app/node_modules/kafkajs/src/consumer/runner.js:249:22)" ,
```

**Describe the solution you'd like**
We would like to see clearer documentation on the shutdown process. Since it is not clear if we should handle it, or the lib itself

**Additional context**
Is there any other way to solve it? we are using "eachMessage" as a consumer option,
the only idea that I have is to save the handler promise reference, then on shutdown "pause" the consumer, wait for the promise to finish (with timeout), then disconnect.

**Comment by t-d-d** [comment]
@artur-ma 
The consumer should shut down cleanly if you call ```await consumer.disconnect()```

> We are calling "disconnect" manually

Can you post the code snippet for this?

**Comment by artur-ma** [comment]
Unfortunately, it happened once and I can not reproduce it, I think it somehow related to a race condition between the retry mechanism and disconnect.

Anyway, my point on this issue, is that I did not find any docs about the disconnect, that would say 
"It will stop consuming and will wait for all messages that are in-flight to be successfully handled"

**Comment by stavalfi** [comment]
im seeing this issue as well sometimes. it's too hard to reproduce in a deterministic way.

**Comment by Nevon** [comment]
I'm gonna close this in favor of #1074, where we have a way to reproduce the issue. Feel free to provide any more context you have in there if the issue has persisted for you.
