### ISSUE TITLE
Response Heartbeat - The group is rebalancing, so a rejoin is needed

### ISSUE THREAD

**Issue by sp-suresh** [tulios/kafkajs#1032]
I am trying `kafajs` for the first time and I need some help to correctly identify the issue and save myself🙏🏻

I have 4 pods running which stream data from BQ and produce messages which are consumed by the same microservice. Recently I was able to stream 5k events in performance testing out of which around ~1k failed due to 

`{"meta":{"message":"KafkaJSLockTimeout: Timeout while acquiring lock (1669 waiting locks): \"connect to broker 10.9.21.15:9094\"","stack":"KafkaJSLockTimeout: Timeout while acquiring lock (1669 waiting locks): \"connect to broker 10.9.21.15:9094\"\n    at Timeout._onTimeout (/app/node_modules/kafkajs/src/utils/lock.js:48:23)\n    at listOnTimeout (internal/timers.js:554:17)\n    at processTimers (internal/timers.js:497:7)"},"requestId":"969f6228efbb8729c346c4250a6036a4","level":"error","message":"Error in processing offer claim for customerId: 5f12fc393e164934f0a3e5ee, idempotencyKey: bb9fe7dd-2e44-4d2d-b334-646b8310f9a7","timestamp":"2021-02-26T10:14:33.744Z"}`

I was trying to reproduce the above with the same dataset however now I am facing a new Heartbeat issue whenever code is unable to produce a message with that group🤯. Below is the error:

```
{"level":"ERROR","timestamp":"2021-03-02T06:56:55.510Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 2)","broker":"10.9.21.15:9094","clientId":"ms-offer","error":"The group is rebalancing, so a rejoin is needed","correlationId":1027,"size":10}
{"level":"ERROR","timestamp":"2021-03-02T06:56:55.510Z","logger":"kafkajs","message":"[Runner] The group is rebalancing, re-joining","groupId":"ms-offer","memberId":"ms-offer-38b8b435-0ce9-43fc-bd13-05dfddc3070d","error":"The group is rebalancing, so a rejoin is needed","retryCount":0,"retryTime":275}
```

I receive the above errors whenever the code is trying to publish a message. I have tried restarting the pods but the issue remains the same. I checked via producing a message using Kafka Tool, which is consumed and processed successfully. Seems my producer is not working for the reason I don't know and need help on which area I should debug/check.

If you have any idea what can be tried or fix the issue, please let me know in the comments.

**Comment by afzdev13** [comment]
Hi, did you figure out how fix that?

**Comment by zzswang** [comment]
same problem, how to fix it?
