### ISSUE TITLE
Kafka producer fails to produce message when using snappy compression along with kafkajs-snappy(1.1.0)

### ISSUE THREAD

**Issue by gurbaj5124871** [tulios/kafkajs#1033]
**Describe the bug**
Kafkajs producer fails to send message when snappy compression is used alongside with kafkajs-snappy codec.

**To Reproduce**
1. Register `kafkajs-snappy` compression codes
```
import { CompressionTypes, CompressionCodecs, Kafka } from 'kafkajs';
const SnappyCodec = require('kafkajs-snappy');
CompressionCodecs[CompressionTypes.Snappy] = SnappyCodec;
```
2. Produce a message using `.send` method on producer providing the compression type as snappy:
```
sampleProducer.send({
    topic: 'topic-with-partitions',
    messages: [
      {
        key,
        value: Buffer.from(JSON.stringify(value)),
        partition: partitionNumber
      }
    ],
    compression: CompressionTypes.Snappy
  })
```

**Expected behavior**
No error should be thrown and message should be sent successfully to the kafka

**Observed behavior**
Kafkajs throws error and message doesn't gets sent into kafka. Error log stack below
```
The server experienced an unexpected error when processing the request
{
  "extra": {
    "timestamp": "2021-03-02T10:47:05.209Z",
    "logger": "kafkajs",
    "retryCount": 0,
    "retryTime": 249
  }
}
KafkaJSProtocolError: The server experienced an unexpected error when processing the request
    at createErrorFromCode (/Users/mac/Downloads/Waitroom/punjab/node_modules/kafkajs/src/protocol/error.js:581:10)
    at Object.parse (/Users/mac/Downloads/Waitroom/punjab/node_modules/kafkajs/src/protocol/requests/produce/v3/response.js:47:11)
    at Connection.send (/Users/mac/Downloads/Waitroom/punjab/node_modules/kafkajs/src/network/connection.js:336:35)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
    at Broker.[private:Broker:sendRequest] (/Users/mac/Downloads/Waitroom/punjab/node_modules/kafkajs/src/broker/index.js:890:14)
    at Broker.produce (/Users/mac/Downloads/Waitroom/punjab/node_modules/kafkajs/src/broker/index.js:254:12)
    at /Users/mac/Downloads/Waitroom/punjab/node_modules/kafkajs/src/producer/sendMessages.js:82:28
    at async Promise.all (index 0)
    at /Users/mac/Downloads/Waitroom/punjab/node_modules/kafkajs/src/producer/sendMessages.js:118:9 {
  name: 'KafkaJSProtocolError',
  retriable: false,
  helpUrl: undefined,
  type: 'UNKNOWN',
  code: -1
}
```

**Environment:**
 - OS: Mac OS 10.15.3
 - KafkaJS version 1.15.0
 - Kafka version 2.3.10 // docker link `https://hub.docker.com/r/obsidiandynamics/kafka`
 - NodeJS version 12.0.0

**Additional context**
The kafka consumers work successfully with the kafkajs-snappy codec
Also without providing the compression to producer send method the message gets sent successfully

**Comment by ankon** [comment]
Are there any messages on the broker side?

Also, you didn't specify the versions of KafkaJS nor of the Kafka version, and the referenced docker image looks fairly old (2.3.0-11? last publish 2 years ago?)

**Comment by gurbaj5124871** [comment]
> Are there any messages on the broker side?
> 
> Also, you didn't specify the versions of KafkaJS nor of the Kafka version, and the referenced docker image looks fairly old (2.3.0-11? last publish 2 years ago?)

Updated the verions of packages on the above note.
Found error stack in logs of kafka:
```
[2021-03-02 10:56:13,425] ERROR [ReplicaManager broker=0] Error processing append operation on partition topic-with-partitions-0 (kafka.server.ReplicaManager)
org.apache.kafka.common.KafkaException: java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
        at org.apache.kafka.common.record.CompressionType$3.wrapForInput(CompressionType.java:92)
        at org.apache.kafka.common.record.DefaultRecordBatch.compressedIterator(DefaultRecordBatch.java:257)
        at org.apache.kafka.common.record.DefaultRecordBatch.iterator(DefaultRecordBatch.java:324)
        at scala.collection.convert.Wrappers$JIterableWrapper.iterator(Wrappers.scala:55)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at kafka.log.LogValidator$.$anonfun$validateMessagesAndAssignOffsetsCompressed$1(LogValidator.scala:269)
        at kafka.log.LogValidator$.$anonfun$validateMessagesAndAssignOffsetsCompressed$1$adapted(LogValidator.scala:261)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at kafka.log.LogValidator$.validateMessagesAndAssignOffsetsCompressed(LogValidator.scala:261)
        at kafka.log.LogValidator$.validateMessagesAndAssignOffsets(LogValidator.scala:73)
        at kafka.log.Log.liftedTree1$1(Log.scala:881)
        at kafka.log.Log.$anonfun$append$2(Log.scala:868)
        at kafka.log.Log.maybeHandleIOException(Log.scala:2065)
        at kafka.log.Log.append(Log.scala:850)
        at kafka.log.Log.appendAsLeader(Log.scala:819)
        at kafka.cluster.Partition.$anonfun$appendRecordsToLeader$1(Partition.scala:772)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:253)
        at kafka.utils.CoreUtils$.inReadLock(CoreUtils.scala:259)
        at kafka.cluster.Partition.appendRecordsToLeader(Partition.scala:759)
        at kafka.server.ReplicaManager.$anonfun$appendToLocalLog$2(ReplicaManager.scala:763)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
        at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
        at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at kafka.server.ReplicaManager.appendToLocalLog(ReplicaManager.scala:751)
        at kafka.server.ReplicaManager.appendRecords(ReplicaManager.scala:492)
        at kafka.server.KafkaApis.handleProduceRequest(KafkaApis.scala:544)
        at kafka.server.KafkaApis.handle(KafkaApis.scala:113)
        at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:69)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.xerial.snappy.Snappy
        at org.xerial.snappy.SnappyInputStream.readFully(SnappyInputStream.java:145)
        at org.xerial.snappy.SnappyInputStream.readHeader(SnappyInputStream.java:99)
        at org.xerial.snappy.SnappyInputStream.<init>(SnappyInputStream.java:59)
        at org.apache.kafka.common.record.CompressionType$3.wrapForInput(CompressionType.java:90)
        ... 41 more
        ```

**Comment by ankon** [comment]
This is a problem on the broker, which is unable to initialize the class needed for compression/decompression. 

Quick check in google found this hint, which also rings a bell from a long-ago experience with native code in Java: https://github.com/confluentinc/kafka-connect-hdfs/issues/421#issuecomment-581315111

> Issue is with snappy libraries that are being loaded into /tmp
> /tmp by default has noexec permission so it can't load libraries from /tmp path
> 
> to resolve this issue 2 approaches can be used :
> 
> 1. -Dorg.xerial.snappy.tempdir=(path to new temp which has exec permissions)
> 2. mount the /tmp with exec permissions cmd : mount -o remount,exec /tmp

**Comment by Nevon** [comment]
Closing this as unrelated to KafkaJS. As @ankon said, it's an issue with the broker not being able to initialize the Snappy compression class.
