### ISSUE TITLE
KafkaJSProtocolError: There is no listener on the leader broker that matches the listener on which metadata request was processed

### ISSUE THREAD

**Issue by johi123** [tulios/kafkajs#1042]
**Describe the bug**
What does the above error message mean in KafkaJS?

**Background**
We use KafkaJS in our Kubernetes environment to process Kafka Messages. Sometimes (a few hours/days) we get the above error message in our services and KafkaJS stops processing messages. KafkaJS tries to resolve this issue but it doesn't seem to work. After a restart, the service seems to work like before. I've done many rounds of bug fixing now but can't find the cause of this issue. This is quite a problem for us because it seems like Kafka "loses" some messages when this error occurs.

Could you please describe the above error in detail as I can't figure out if this is a problem with our Kafka setup or my KafkaJS config?

The basic connection setup seems to work but maybe there are some configuration tweaks I missed.

```typescript
const kafkaConfig = {
    brokers: ["kafka-0.kafka-svc.clsystem.svc.cluster.local:9092","kafka-1.kafka-svc.clsystem.svc.cluster.local:9092","kafka-2.kafka-svc.clsystem.svc.cluster.local:9092"],
    ssl: { rejectUnauthorized: false },
    sasl: {
        mechanism: "plain",
        username: "user",
        password: "password",
    },
    clientId: "service-consumer",
};

const consumerConfig = {
    sessionTimeout: 60000,
    heartbeatInterval: 2500,
    rebalanceTimeout: 30000,
    groupId: "service-consumer-group",
    partitionAssigners: [customPartitionAssigner, PartitionAssigners.roundRobin],
};
```

Do you have any ideas on how to debug this issue?

**Environment:**
 - OS: node:14.15.0-alpine
 - KafkaJS version: 1.15.0
 - Kafka version: confluentinc/cp-kafka:5.5.3
 - Zookeeper version: confluentinc/cp-zookeeper:5.5.3
 - NodeJS version: 14.15.0

Please let me know if you need any further information from me.

Thank you in advance. 😃 

```
{"level":"ERROR","timestamp":"2021-03-09T10:29:43.433Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSProtocolError: There is no listener on the leader broker that matches the listener on which metadata request was processed","groupId":"service-consumer-group","stack":"KafkaJSProtocolError: There is no listener on the leader broker that matches the listener on which metadata request was processed\n    at createErrorFromCode (/home/server/node_modules/kafkajs/src/protocol/error.js:581:10)\n    at Object.parse (/home/server/node_modules/kafkajs/src/protocol/requests/metadata/v0/response.js:66:11)\n    at Connection.send (/home/server/node_modules/kafkajs/src/network/connection.js:336:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Broker.[private:Broker:sendRequest] (/home/server/node_modules/kafkajs/src/broker/index.js:890:14)\n    at async Broker.metadata (/home/server/node_modules/kafkajs/src/broker/index.js:191:12)\n    at async /home/server/node_modules/kafkajs/src/cluster/brokerPool.js:155:25\n    at async Cluster.refreshMetadataIfNecessary (/home/server/node_modules/kafkajs/src/cluster/index.js:142:5)\n    at async ConsumerGroup.connect (/home/server/node_modules/kafkajs/src/consumer/consumerGroup.js:117:5)"}
{"level":"INFO","timestamp":"2021-03-09T10:29:43.433Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"service-consumer-group"}
{"level":"ERROR","timestamp":"2021-03-09T10:29:43.433Z","logger":"kafkajs","message":"[Consumer] Restarting the consumer in 300ms","retryTime":300,"groupId":"service-consumer-group"}
{"level":"INFO","timestamp":"2021-03-09T10:29:43.465Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"service-consumer-group-2"}
{"level":"ERROR","timestamp":"2021-03-09T10:29:43.483Z","logger":"kafkajs","message":"[Connection] Response Metadata(key: 3, version: 6)","broker":"kafka-0.kafka-svc.clsystem.svc.cluster.local:9092","clientId":"consumer","error":"There is no listener on the leader broker that matches the listener on which metadata request was processed","correlationId":108,"size":218}
{"level":"ERROR","timestamp":"2021-03-09T10:29:43.484Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSProtocolError: There is no listener on the leader broker that matches the listener on which metadata request was processed","groupId":"service-consumer-group-2","stack":"KafkaJSProtocolError: There is no listener on the leader broker that matches the listener on which metadata request was processed\n    at createErrorFromCode (/home/server/node_modules/kafkajs/src/protocol/error.js:581:10)\n    at Object.parse (/home/server/node_modules/kafkajs/src/protocol/requests/metadata/v0/response.js:66:11)\n    at Connection.send (/home/server/node_modules/kafkajs/src/network/connection.js:336:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Broker.[private:Broker:sendRequest] (/home/server/node_modules/kafkajs/src/broker/index.js:890:14)\n    at async Broker.metadata (/home/server/node_modules/kafkajs/src/broker/index.js:191:12)\n    at async /home/server/node_modules/kafkajs/src/cluster/brokerPool.js:155:25\n    at async Cluster.refreshMetadataIfNecessary (/home/server/node_modules/kafkajs/src/cluster/index.js:142:5)\n    at async ConsumerGroup.connect (/home/server/node_modules/kafkajs/src/consumer/consumerGroup.js:117:5)"}
{"level":"INFO","timestamp":"2021-03-09T10:29:43.484Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"service-consumer-group-2"}
{"level":"ERROR","timestamp":"2021-03-09T10:29:43.484Z","logger":"kafkajs","message":"[Consumer] Restarting the consumer in 300ms","retryTime":300,"groupId":"service-consumer-group-2"}
{"level":"INFO","timestamp":"2021-03-09T10:29:43.734Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"service-consumer-group"}
{"level":"INFO","timestamp":"2021-03-09T10:29:43.784Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"service-consumer-group-2"}
{"level":"INFO","timestamp":"2021-03-09T10:29:46.647Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"service-consumer-group","memberId":"consumer-4b890ac8-fbf2-45b6-b944-e68505da3e34","leaderId":"consumer-6dfd1108-93bf-433f-b74f-aa76eafed436","isLeader":false,"memberAssignment":{"queue-topic-1":[0],"facts-topic-1":[0]},"groupProtocol":"customPartitionAssigner","duration":2900}
{"level":"ERROR","timestamp":"2021-03-09T10:29:46.708Z","logger":"kafkajs","message":"[Connection] Response ListOffsets(key: 2, version: 3)","broker":"10.244.1.77:9092","clientId":"consumer","error":"This server does not host this topic-partition","correlationId":2,"size":61}
{"level":"INFO","timestamp":"2021-03-09T10:29:46.713Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"service-consumer-group","memberId":"consumer-4b890ac8-fbf2-45b6-b944-e68505da3e34","leaderId":"consumer-6dfd1108-93bf-433f-b74f-aa76eafed436","isLeader":false,"memberAssignment":{"queue-topic-1":[0],"facts-topic-1":[0]},"groupProtocol":"customPartitionAssigner","duration":4}
{"level":"INFO","timestamp":"2021-03-09T10:29:46.817Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"service-consumer-group-2","memberId":"consumer-ecf896ea-1db4-4195-9d64-459c84114394","leaderId":"consumer-cd80de56-eab2-4162-af28-c45a7e2ab73e","isLeader":false,"memberAssignment":{"queue-topic-2":[0],"2":[0]},"groupProtocol":"customPartitionAssigner","duration":3016}
{"level":"ERROR","timestamp":"2021-03-09T10:29:46.918Z","logger":"kafkajs","message":"[Connection] Response Fetch(key: 1, version: 11)","broker":"10.244.1.77:9092","clientId":"consumer","error":"This server does not host this topic-partition","correlationId":2,"size":87}
{"level":"ERROR","timestamp":"2021-03-09T10:29:46.988Z","logger":"kafkajs","message":"[Connection] Response ListOffsets(key: 2, version: 3)","broker":"10.244.1.77:9092","clientId":"consumer","error":"This server does not host this topic-partition","correlationId":3,"size":61}
{"level":"INFO","timestamp":"2021-03-09T10:29:46.994Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"service-consumer-group","memberId":"consumer-4b890ac8-fbf2-45b6-b944-e68505da3e34","leaderId":"consumer-6dfd1108-93bf-433f-b74f-aa76eafed436","isLeader":false,"memberAssignment":{"queue-topic-1":[0],"facts-topic-1":[0]},"groupProtocol":"customPartitionAssigner","duration":4}
{"level":"ERROR","timestamp":"2021-03-09T10:29:47.539Z","logger":"kafkajs","message":"[Connection] Response ListOffsets(key: 2, version: 3)","broker":"10.244.1.77:9092","clientId":"consumer","error":"This server does not host this topic-partition","correlationId":4,"size":61}
{"level":"INFO","timestamp":"2021-03-09T10:29:47.545Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"service-consumer-group","memberId":"consumer-4b890ac8-fbf2-45b6-b944-e68505da3e34","leaderId":"consumer-6dfd1108-93bf-433f-b74f-aa76eafed436","isLeader":false,"memberAssignment":{"queue-topic-1":[0],"facts-topic-1":[0]},"groupProtocol":"customPartitionAssigner","duration":4}
```

**Comment by Nevon** [comment]
This is a broker cluster misconfiguration. The intention of the error is to inform you of that. See this issue for more information: https://issues.apache.org/jira/browse/KAFKA-6546
