### ISSUE TITLE
Does kafkajs support broker names with domains?

### ISSUE THREAD

**Issue by gbarton** [tulios/kafkajs#1090]
While I am rummaging through the src to see how the broker string is parsed I figure I'd ask if I'm going down the wrong hole.

When I deploy kafka in k8s in the same namespace I can point kafkajs at kafka-cluster:9092 and it connects and does its thing.
When I deploy kafka in k8s in a different namespace, I can point kafkajs at kafka-cluster.dev:9092 and it does not connect and errors out.

I have verified kafka is up because I can deploy the same service into that same namespace and it will work.

In the logs though when I am in a different namespace, I see the domain dropped from the error output:

```
kafka:producer creating producer uploader kafka-cluster.dev:9092 +0ms
... other init stuffs, try to publish a message and...
KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionError: Connection error: getaddrinfo ENOTFOUND kafka-cluster
    at Socket.onError (/headless/wrk/fetcher/node_modules/kafkajs/src/network/connection.js:152:23)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'KafkaJSNumberOfRetriesExceeded',
  retriable: false,
  helpUrl: undefined,
  originalError: KafkaJSConnectionError: Connection error: getaddrinfo ENOTFOUND kafka-cluster
      at Socket.onError (/headless/wrk/fetcher/node_modules/kafkajs/src/network/connection.js:152:23)
      at Socket.emit (events.js:314:20)
      at emitErrorNT (internal/streams/destroy.js:92:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    retriable: true,
    helpUrl: undefined,
    broker: 'kafka-cluster:9092',
    code: 'ENOTFOUND'
  },
  retryCount: 3,
  retryTime: 2400
} +1ms
```

**Comment by gbarton** [comment]
Turned on debug logging to see if there was more information.

```
{"level":"DEBUG","timestamp":"2021-05-06T01:52:11.949Z","logger":"kafkajs","message":"[Connection] Request Metadata(key: 3, version: 6)","broker":"kafka-cluster.dev:9092","clientId":"uploader","correlationId":1,"expectResponse":true,"size":40}
{"level":"DEBUG","timestamp":"2021-05-06T01:52:11.952Z","logger":"kafkajs","message":"[Connection] Response Metadata(key: 3, version: 6)","broker":"kafka-cluster.dev:9092","clientId":"uploader","correlationId":1,"size":119,"data":{"throttleTime":0,"brokers":[{"nodeId":1,"host":"kafka-cluster","port":9092,"rack":null}],"clusterId":"wcOdsadtTPyOz7Z7mJsJbw","controllerId":1,"topicMetadata":[{"topicErrorCode":0,"topic":"coordinator","isInternal":false,"partitionMetadata":[{"partitionErrorCode":0,"partitionId":0,"leader":1,"replicas":[1],"isr":[1],"offlineReplicas":[]}]}],"clientSideThrottleTime":0}}
{"level":"DEBUG","timestamp":"2021-05-06T01:52:11.955Z","logger":"kafkajs","message":"[Connection] Connecting","broker":"kafka-cluster:9092","clientId":"uploader","ssl":false,"sasl":false}
{"level":"ERROR","timestamp":"2021-05-06T01:52:11.968Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND kafka-cluster","broker":"kafka-cluster:9092","clientId":"uploader","stack":"Error: getaddrinfo ENOTFOUND kafka-cluster\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}
{"level":"DEBUG","timestamp":"2021-05-06T01:52:11.969Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"kafka-cluster:9092","clientId":"uploader"}
{"level":"DEBUG","timestamp":"2021-05-06T01:52:11.969Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"kafka-cluster:9092","clientId":"uploader"}
{"level":"DEBUG","timestamp":"2021-05-06T01:52:11.970Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"kafka-cluster:9092","clientId":"uploader"}
{"level":"DEBUG","timestamp":"2021-05-06T01:52:11.970Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"kafka-cluster:9092","clientId":"uploader"}
{"level":"DEBUG","timestamp":"2021-05-06T01:52:11.970Z","logger":"kafkajs","message":"[Connection] Connecting","broker":"kafka-cluster:9092","clientId":"uploader","ssl":false,"sasl":false}
{"level":"ERROR","timestamp":"2021-05-06T01:52:11.977Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND kafka-cluster","broker":"kafka-cluster:9092","clientId":"uploader","stack":"Error: getaddrinfo ENOTFOUND kafka-cluster\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"}

```

**Comment by gbarton** [comment]
alright, for anyone else that runs into this, what is happening is the kafkajs code IS using the full dns, reaching out to kafka, and in this case the kafka prop `KAFKA_ADVERTIZED_ADDRESS`  was set to `kafka-cluster` instead of `kafka-cluster.dev` as it should. So when kafkajs reached out, got told to connect to just `kafka-cluster`, obviously that wouldnt work.

Thank you all for entertaining my digging and frustration, and thanks again for an awesome kafka implementation!
