### ISSUE TITLE
Trying to stop server gracefully when Kafka connection error occurs

### ISSUE THREAD

**Issue by eliw00d** [tulios/kafkajs#1203]
**Is your feature request related to a problem? Please describe.**
I have some code where I try to catch the error thrown by consumer.connect and stop my server gracefully as a result:
```javascript
try {
  await consumer.connect()
} catch (error) {
  logger.error('myErrorMessage', error)
  return stopServer()
}
```

stopServer looks something like:
```javascript
const stopServer = () => {
  await consumer.disconnect()

  process.exitCode = 1
  logger.end()
}
```

I use winston and `logger.end()` is how to stop the logger gracefully and ensure everything gets logged.

However, I continue to get logs after `logger.end()`, as you can see below:
```
{
  name: 'KafkaJSNumberOfRetriesExceeded',
  retriable: false,
  helpUrl: undefined,
  originalError: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 127.0.0.1:9092
      at Socket.onError (/Users/eliw00d/Documents/GitHub/myProject/node_modules/kafkajs/src/network/connection.js:152:23)
      at Socket.emit (events.js:315:20)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    retriable: true,
    helpUrl: undefined,
    broker: 'localhost:9092',
    code: 'ECONNREFUSED'
  },
  retryCount: 5,
  retryTime: 10460,
  level: 'error',
  message: 'myErrorMessage. Connection error: connect ECONNREFUSED 127.0.0.1:9092',
  stack: 'KafkaJSNonRetriableError\n' +
    '  Caused by: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 127.0.0.1:9092\n' +
    '    at Socket.onError (/Users/eliw00d/Documents/GitHub/myProject/node_modules/kafkajs/src/network/connection.js:152:23)\n' +
    '    at Socket.emit (events.js:315:20)\n' +
    '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
    '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:80:21)'
}
{
  level: 'info',
  timestamp: '2021-10-07T22:16:59.032Z',
  groupId: 'myGroupId',
  message: 'Stopped'
}
{
  level: 'error',
  timestamp: '2021-10-07T22:16:59.040Z',
  broker: 'localhost:9092',
  clientId: 'myClientId',
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:9092\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)',
  message: 'Connection error: connect ECONNREFUSED 127.0.0.1:9092'
}
{
  level: 'error',
  timestamp: '2021-10-07T22:16:59.041Z',
  retryCount: 0,
  retryTime: 283,
  message: 'Failed to connect to seed broker, trying another broker from the list: Connection error: connect ECONNREFUSED 127.0.0.1:9092'
}
(node:48231) UnhandledPromiseRejectionWarning: KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 127.0.0.1:9092
    at Socket.onError (/Users/eliw00d/Documents/GitHub/myProject/node_modules/kafkajs/src/network/connection.js:152:23)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:48231) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:48231) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Describe the solution you'd like**
Is there a way to ensure once a connection error occurs that no more logs will be written so that I can stop my server gracefully? Alternatively, is there an event I can listen to so that I know it's safe to stop?

**Additional context**
kafkajs version is 1.15.0

**Comment by mj123muskan** [comment]
Hi, @eliw00d can u please explain how did u resolve this error

**Comment by eliw00d** [comment]
> Hi, @eliw00d can u please explain how did u resolve this error

I don't remember exactly but it was pretty specific to my code and totally unrelated to Kafka.js.
