### ISSUE TITLE
Fetch retry occurs even on disconnected consumer

### ISSUE THREAD

**Issue by sempasha** [tulios/kafkajs#1327]
**Describe the bug**

NodeJS process doesn't exit as expected, when KafkaJS consumer has been disconnected after message processing error.

When consumer gets an error during message processing (no matter `eachMessage` or `eachBatch`) it starts retries.
Consumer schedules new `fetch` request.
When consumer disconnection occurs between scheduling `fetch` retry and scheduled `fetch` retry issue occurs.

**To Reproduce**

```js
const { Kafka } = require('kafkajs');

(async function main() {
  const topic = 'topic';
  const kafka = new Kafka({ brokers: ['kafka:9092'] });

  const producer = kafka.producer();
  await producer.connect();
  await producer.send({
    messages: [{
      value: 'Hello, World!',
      headers: { 'Content-Type': 'text/plain' },
    }],
    topic,
  });
  await producer.disconnect();

  const consumer = kafka.consumer({ groupId: 'group-id' });
  await consumer.connect();
  await consumer.subscribe({ topic, fromBeginning: true });
  await new Promise((resolve) => {
    consumer.run({
      async eachMessage() {
        process.nextTick(resolve);
        throw new Error('Failure!');
      },
    })
  });
  await consumer.disconnect();
  console.info('consumer disconnected, process should exit now');
})();
```

**Expected behavior**

When running provided script we expect NodeJS process will exit.

**Observed behavior**

When running provided script NodeJS process running forever.
Process output:
```
{"level":"INFO","timestamp":"2022-04-20T14:40:46.694Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"group-id"}
{"level":"INFO","timestamp":"2022-04-20T14:40:46.707Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"group-id","memberId":"kafkajs-fe64c5f7-5bd2-45b0-a107-68c485dede60","leaderId":"kafkajs-fe64c5f7-5bd2-45b0-a107-68c485dede60","isLeader":true,"memberAssignment":{"topic":[0]},"groupProtocol":"RoundRobinAssigner","duration":12}
{"level":"ERROR","timestamp":"2022-04-20T14:40:46.724Z","logger":"kafkajs","message":"[Runner] Error when calling eachMessage","topic":"topic","partition":0,"offset":"4","stack":"Error: Failure!\n    at Runner.eachMessage (/app/test.js:25:15)\n    at Runner.processEachMessage (/app/node_modules/kafkajs/src/consumer/runner.js:151:20)\n    at onBatch (/app/node_modules/kafkajs/src/consumer/runner.js:328:20)\n    at /app/node_modules/kafkajs/src/consumer/runner.js:383:21\n    at invoke (/app/node_modules/kafkajs/src/utils/concurrency.js:38:5)\n    at push (/app/node_modules/kafkajs/src/utils/concurrency.js:51:7)\n    at /app/node_modules/kafkajs/src/utils/concurrency.js:60:53\n    at new Promise (<anonymous>)\n    at /app/node_modules/kafkajs/src/utils/concurrency.js:60:20\n    at /app/node_modules/kafkajs/src/consumer/runner.js:377:11","error":{}}
{"level":"INFO","timestamp":"2022-04-20T14:40:46.728Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"group-id"}
```

**Environment:**

 - OS: docker at Ubuntu 20.04
 - KafkaJS version 1.16.0
 - Kafka version 3.1.0
 - NodeJS version 14.19.0

**Comment by sempasha** [comment]
Seems that issue has same nature as #1168.

When scheduled `fetch` retry occurs it start real [fetch](https://github.com/tulios/kafkajs/blob/d8fd93e7ce8e4675e3bb9b13d7a1e55a1e0f6bbf/src/consumer/runner.js#L383) request, despite the fact fetch runner is not running anymore.

Adding `if (this.running)` test before doing `fetch` request resolve the issue.

```js
if (this.running) {
  this.consuming = true
  await this.fetch()
  this.consuming = false
}
```

**Comment by Nevon** [comment]
Feel free to see if the issue can be reproduced in [the pre-release version](https://www.npmjs.com/package/kafkajs/v/1.17.0-beta.6).

Just be aware that versions after 1.17.0-beta.6 have breaking changes in anticipation of the 2.0.0 release, but beta.6 and earlier packages should be completely backwards compatible.
