### ISSUE TITLE
Invalid Transaction state exception: Cannot call "beginTransaction" in state "ABORTING" error

### ISSUE THREAD

**Issue by gergelyrozsonits** [tulios/kafkajs#1355]
**Describe the bug**
Producer throws `KafkaJSNonRetriableError: Transaction state exception: Cannot call "beginTransaction" in state "ABORTING"` error for all consecutive `producer.transaction()` invocation after a failed `transaction.abort()`.

**To Reproduce**
1. Create a producer
2. Create a transaction from the producer
3. Abort the transaction, results the following error:
```
{"level":"ERROR","timestamp":"2022-05-12T14:16:04.189Z","logger":"kafkajs","message":"[Connection] Response EndTxn(key: 26, version: 1)","broker":"<broker>:9092","clientId":"kafkajs","error":"The producer attempted a transactional operation in an invalid state","correlationId":4,"size":10}
KafkaJSProtocolError: The producer attempted a transactional operation in an invalid state
    at createErrorFromCode (<dir>\node_modules\kafkajs\src\protocol\error.js:581:10)
    at Object.parse (<dir>\node_modules\kafkajs\src\protocol\requests\endTxn\v0\response.js:24:11)
    at Connection.send (<dir>\node_modules\kafkajs\src\network\connection.js:433:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Broker.[private:Broker:sendRequest] (<dir>\node_modules\kafkajs\src\broker\index.js:875:14)
    at async Broker.endTxn (<dir>\node_modules\kafkajs\src\broker\index.js:742:12)
    at async Object.abort (<dir>\node_modules\kafkajs\src\producer\eosManager\index.js:289:9)
    at async <dir>\node_modules\kafkajs\src\producer\index.js:173:9
    at async <dir>\index.js:20:5 {
  retriable: false,
  helpUrl: undefined,
  cause: undefined,
  type: 'INVALID_TXN_STATE',
  code: 48
}
```
4. Create a new transaction from the existing producer

**Expected behavior**
The new transaction is created without any error

**Observed behavior**
KafkaJS produces the following exception:
```
KafkaJSNonRetriableError: Transaction state exception: Cannot call "beginTransaction" in state "ABORTING"
    at Object.beginTransaction (<dir>\node_modules\kafkajs\src\producer\eosManager\transactionStateMachine.js:25:23) 
    at Object.transaction (<dir>\node_modules\kafkajs\src\producer\index.js:140:29)
    at <dir>\index.js:26:20
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  retriable: false,
  helpUrl: undefined,
  cause: undefined
}
```

**Environment:**
 - OS: [Windows 10]
 - KafkaJS version [1.14.0, 2.0.0]
 - Kafka version [e.g. 2.3.1]
 - NodeJS version [e.g. 14.19.0]

**Additional context**
Code snippet to reproduce the issue:

```
const { Kafka } = require("kafkajs")

const kafka = new Kafka({
  brokers: ["broker:9092"],
  ssl: true,
  sasl: {
    mechanism: 'plain',
    username: '<username>',
    password: '<password>'
  }
});

const producer = kafka.producer({ transactionalId: '<transactional-id>' });

(async () => {
  await producer.connect();

  try {
    const transaction = await producer.transaction();
    await transaction.abort();
  } catch (e) {
    console.error(e);
  }

  try {
    await producer.transaction();
  } catch (e) {
    console.error(e);
  }
})().then(console.log).catch(console.error).then(async () => await producer.disconnect())
```

**Comment by guikubivan** [comment]
Any work around for 1.6 version?
