### ISSUE TITLE
KafkaJS 2.0.0 failing to create topics from Admin

### ISSUE THREAD

**Issue by Saeger** [tulios/kafkajs#1358]
**Describe the bug**
After upgrading to KafkaJS 2.0.0, our integration tests started failing consistently on `createTopics` from kafka.admin.

**To Reproduce**
```
const kafkaReady = async (): Promise<void> => {
  console.log('Waiting for Kafka to be ready...');

  const kafka = new Kafka({ brokers: [process.env.KAFKA_HOST] });
  const created = await kafka.admin().createTopics({
    topics: [{ topic: 'macarena' }],
  });
  console.log(created);
  console.log('Kafka is ready.');
};
```

**Expected behavior**
Topic to be created after connection is stablished.

**Observed behavior**
```
KafkaJSAggregateError: Topic creation errors
    at Object.parse (/Users/marcio.saeger/dev/dazzler-npm-kafka/node_modules/kafkajs/src/protocol/requests/createTopics/v0/response.js:29:11)
    at Connection.send (/Users/marcio.saeger/dev/dazzler-npm-kafka/node_modules/kafkajs/src/network/connection.js:433:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Broker.[private:Broker:sendRequest] (/Users/marcio.saeger/dev/dazzler-npm-kafka/node_modules/kafkajs/src/broker/index.js:875:14)
    at async Broker.createTopics (/Users/marcio.saeger/dev/dazzler-npm-kafka/node_modules/kafkajs/src/broker/index.js:555:12)
    at async /Users/marcio.saeger/dev/dazzler-npm-kafka/node_modules/kafkajs/src/admin/index.js:172:9
    at async kafkaReady (/Users/marcio.saeger/dev/dazzler-npm-kafka/integration/setup.ts:19:19)
    at async waitForImageInit (/Users/marcio.saeger/dev/dazzler-npm-kafka/integration/setup.ts:50:5) {
  errors: [
    KafkaJSCreateTopicError: Number of partitions is invalid
        at /Users/marcio.saeger/dev/dazzler-npm-kafka/node_modules/kafkajs/src/protocol/requests/createTopics/v0/response.js:32:18
        at Array.map (<anonymous>)
        at Object.parse (/Users/marcio.saeger/dev/dazzler-npm-kafka/node_modules/kafkajs/src/protocol/requests/createTopics/v0/response.js:31:23)
        at Connection.send (/Users/marcio.saeger/dev/dazzler-npm-kafka/node_modules/kafkajs/src/network/connection.js:433:35)
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async Broker.[private:Broker:sendRequest] (/Users/marcio.saeger/dev/dazzler-npm-kafka/node_modules/kafkajs/src/broker/index.js:875:14)
        at async Broker.createTopics (/Users/marcio.saeger/dev/dazzler-npm-kafka/node_modules/kafkajs/src/broker/index.js:555:12)
        at async /Users/marcio.saeger/dev/dazzler-npm-kafka/node_modules/kafkajs/src/admin/index.js:172:9
        at async kafkaReady (/Users/marcio.saeger/dev/dazzler-npm-kafka/integration/setup.ts:19:19)
        at async waitForImageInit (/Users/marcio.saeger/dev/dazzler-npm-kafka/integration/setup.ts:50:5) {
      retriable: false,
      helpUrl: undefined,
      cause: undefined,
      type: 'INVALID_PARTITIONS',
      code: 37,
      topic: 'macarena'
    }
  ]
}
```

**Environment:**
 - OS: Mac OS 12.3.1 (M1)
 - KafkaJS version [2.0.0]
 - Kafka version [2.11]
 - NodeJS version [16]

**Additional context**
This is part of our integration tests which works on previous major of KafkaJS but not with 2.0.

I noticed that, if I include `numPartitions:1` and `replicationFactor:1` it works successfully which seems weird to me since such parameters are optional and was not needed before.

```
const created = await kafka.admin().createTopics({
    topics: [{ topic: 'macarena', numPartitions: 1, replicationFactor: 1 }],
  });
```

The problem seems to be around the merge of #1305 from @Nevon which sounds a breaking change but it is not mentioned as a breaking change in the changelog. In this case, if we rely on the cluster settings and it doesn't exist (my case), then the creation of topics will fail.

**Comment by Nevon** [comment]
Indeed this is definitely fallout from #1305. I didn't consider this as a breaking change, but I'll make sure to add it as such. You _should_ get an error if the cluster doesn't have a default partition number and replication factor (I didn't actually think this was possible), but it should be marked as a breaking change.

**Comment by Saeger** [comment]
Thanks @Nevon, this seems to help others in future to make sure they think about it before migrating. I would say this issue can be closed now.
