### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined (setting '1')

### ISSUE THREAD

**Issue by rambo-panda** [tulios/kafkajs#1366]
**Describe the bug**
Such as title; 
When I invoke a long task in `eachbatch`, at the same time, when `rebalance` is completed, the [this.resolvedOffsets](https://github.com/tulios/kafkajs/blob/v2.0.0/src/consumer/offsetManager/index.js#L108) will reinitialize;

**To Reproduce**

1. [failing test in a KafkaJS fork](https://github.com/tulios/kafkajs/blob/2faef0719eeba50759eccc2b7d8800dbe63803f3/src/consumer/__tests__/consumeMessages.spec.js#L52-L97)
2. [repository with an example project reproducing the issue](https://github.com/tulios/kafkajs/blob/master/examples/consumer.js)

If none of the above are possible to provide, please write down the exact steps to reproduce the behavior:
1. Run a producer that continuously produces messages to a topic
2. Run a consumer that subscribes to that topic and logs each topic offset
3. After the consumer has consumed 100 messages, it...

**Expected behavior**
* automatically ignore overdue `offset`
* `isSate` should include checking for `offset` exists

**Observed behavior**
```json

{
    "level": "DEBUG",
    "timestamp": "xxxxxxxxxxxxxxxxxx",
    "logger": "kafkajs",
    "message": "[Runner] Error while fetching data, trying again...",
    "groupId": "<groupId>",
    "memberId": "<memebrId>",
    "error": "Cannot set properties of undefined (setting '1')",
    "stack": "TypeError: Cannot set properties of undefined (setting '1')\n    at OffsetManager.resolveOffset (<myPath>/node_modules/kafkajs/src/consumer/offsetManager/index.js:109:43)\n    at ConsumerGroup.resolveOffset (<myPath>/node_modules/kafkajs/src/consumer/consumerGroup.js:386:24)\n    at resolveOffset (<myPath>/node_modules/kafkajs/src/consumer/runner.js:263:30)\n    at Runner.eachBatch (<myPath>/first.js:33:13)\n    at Runner.processEachBatch (<myPath>/node_modules/kafkajs/src/consumer/runner.js:242:18)\n    at onBatch (<myPath>/node_modules/kafkajs/src/consumer/runner.js:409:20)\n    at <myPath>/node_modules/kafkajs/src/consumer/runner.js:423:15\n    at retry (<myPath>/node_modules/kafkajs/src/retry/index.js:43:5)\n    at <myPath>/node_modules/kafkajs/src/retry/index.js:75:5\n    at new Promise (<anonymous>)",
    "retryCount": 0,
    "retryTime": 1183
}
```

**Environment:**
```json
{
    "node": "16.11.1",
    "kafajs": "kafkajs@2.0.0",
    "Kafka": "2.7.0",
    "os": "Darwin Kernel Version 21.3.0"
}
```

**Additional context**
* Possible solutions
   When the number of consumers is greater than the number of partitions, this error may occur when one consumer cannot allocate consumption partitions；So can this be solved?  [source code](https://github.com/tulios/kafkajs/blob/master/src/consumer/consumerGroup.js#L241-L242)
  ```js
const decodedAssignment =
  decodedMemberAssignment == null
    ? topics.reduce((p, topic) => ({ ...p, [topic]: [] }), { __proto__: null })
    : decodedMemberAssignment.assignment;
  ```

**Comment by james4388** [comment]
I saw similar error 
```
TypeError: Cannot set property '0' of undefined
    at OffsetManager.resolveOffset (/<redacted>/node_modules/kafkajs/src/consumer/offsetManager/index.js:108:44)
    at ConsumerGroup.resolveOffset (/<redacted>/node_modules/kafkajs/src/consumer/consumerGroup.js:358:24)
    at resolveOffset (/<redacted>/node_modules/kafkajs/src/consumer/runner.js:207:30)
    at Runner.eachBatch (/<redacted>/src/functions/event-loader.js:1:15258)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Runner.processEachBatch (/<redacted>/node_modules/kafkajs/src/consumer/runner.js:186:7)
    at async onBatch (/<redacted>/node_modules/kafkajs/src/consumer/runner.js:328:9)
    at async /<redacted>/node_modules/kafkajs/src/consumer/runner.js:376:15
```
