### ISSUE TITLE
kafkajs consumers trying to reconnect over and over when 1st broker is stopped

### ISSUE THREAD

**Issue by tmalahie** [tulios/kafkajs#1373]
**Describe the bug**
I'm using kafkajs with a cluster of 3 kafka nodes (I use bitnami docker images for the cluster)
I have an issue when I declare multiple consumers and one of the kafka brokers is dead. The 1st consumer seams to work fine and connect to another broker, but the subsequent consumers have some trouble connecting to a working broker, they try to connect over and over to the first broker (which is dead) and eventually crash.

Not completely sure if this is an actual bug or something wrong in my setup. If it's the latter, I'm interested to know what I did wrong :)

**To Reproduce**
You can get a minimal reproducible example here: https://timothe.malahieude.net/kafkajs-error.zip
To reproduce, run those commands:
```
docker network create dev-tier
docker-compose up -d
docker stop kafka-0
docker restart node
docker logs -f node
```

**Expected behavior**
All the consumers should eventually connect to a working broker.

**Observed behavior**
The 1st consumer successfully connects, sometimes some of the following too, but eventually one of the consumers is stuck in an infinite loop and crashes.
Here are the complete logs
```
{"level":"ERROR","timestamp":"2022-05-25T15:45:38.195Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND kafka-0","broker":"kafka-0:9092","clientId":"clientId","stack":"Error: getaddrinfo ENOTFOUND kafka-0\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2022-05-25T15:45:43.678Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-0.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:45:43.681Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":0,"retryTime":359}
{"level":"INFO","timestamp":"2022-05-25T15:45:44.057Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"test-group-0"}
{"level":"ERROR","timestamp":"2022-05-25T15:45:54.762Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND kafka-0.dev-tier","broker":"kafka-0.dev-tier:9092","clientId":"clientId","stack":"Error: getaddrinfo ENOTFOUND kafka-0.dev-tier\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"INFO","timestamp":"2022-05-25T15:46:05.554Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"test-group-0","memberId":"clientId-7a69934a-0aa6-4610-9c7b-a8ec49934eb3","leaderId":"clientId-7a69934a-0aa6-4610-9c7b-a8ec49934eb3","isLeader":true,"memberAssignment":{"topic-0":[0]},"groupProtocol":"RoundRobinAssigner","duration":21495}
{"level":"ERROR","timestamp":"2022-05-25T15:46:06.559Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-0.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:06.559Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":0,"retryTime":269}
{"level":"INFO","timestamp":"2022-05-25T15:46:06.833Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"test-group-1"}
{"level":"INFO","timestamp":"2022-05-25T15:46:06.871Z","logger":"kafkajs","message":"[ConsumerGroup] Consumer has joined the group","groupId":"test-group-1","memberId":"clientId-6b534b70-d481-4c02-91b9-ff6b384f990a","leaderId":"clientId-6b534b70-d481-4c02-91b9-ff6b384f990a","isLeader":true,"memberAssignment":{"topic-1":[0]},"groupProtocol":"RoundRobinAssigner","duration":38}
{"level":"ERROR","timestamp":"2022-05-25T15:46:07.871Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-0.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:07.872Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":0,"retryTime":341}
{"level":"ERROR","timestamp":"2022-05-25T15:46:07.873Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-1:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:09.213Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-1.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:09.214Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":1,"retryTime":700}
{"level":"ERROR","timestamp":"2022-05-25T15:46:10.914Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-2.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:10.915Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":2,"retryTime":1544}
{"level":"ERROR","timestamp":"2022-05-25T15:46:11.877Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSConnectionError: Connection timeout","groupId":"test-group-1","stack":"KafkaJSConnectionError: Connection timeout\n    at Timeout.onTimeout [as _onTimeout] (/usr/src/app/node_modules/kafkajs/src/network/connection.js:223:23)\n    at listOnTimeout (node:internal/timers:559:17)\n    at processTimers (node:internal/timers:502:7)"}
{"level":"INFO","timestamp":"2022-05-25T15:46:11.887Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"test-group-1"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:11.888Z","logger":"kafkajs","message":"[Consumer] Restarting the consumer in 300ms","retryTime":300,"groupId":"test-group-1"}
{"level":"INFO","timestamp":"2022-05-25T15:46:12.187Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"test-group-1"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:13.188Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-1.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:13.188Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":0,"retryTime":356}
{"level":"ERROR","timestamp":"2022-05-25T15:46:13.459Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-0.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:13.460Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":3,"retryTime":3478}
{"level":"ERROR","timestamp":"2022-05-25T15:46:14.545Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-2.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:14.545Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":1,"retryTime":830}
{"level":"ERROR","timestamp":"2022-05-25T15:46:16.376Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-0.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:16.376Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":2,"retryTime":1504}
{"level":"ERROR","timestamp":"2022-05-25T15:46:17.696Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND kafka-0.dev-tier","broker":"kafka-0.dev-tier:9092","clientId":"clientId","stack":"Error: getaddrinfo ENOTFOUND kafka-0.dev-tier\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:17.937Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-1.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:17.938Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":4,"retryTime":6492}
{"level":"ERROR","timestamp":"2022-05-25T15:46:18.881Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-1.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:18.881Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":3,"retryTime":2474}
{"level":"ERROR","timestamp":"2022-05-25T15:46:18.969Z","logger":"kafkajs","message":"[Connection] Connection error: getaddrinfo ENOTFOUND kafka-0.dev-tier","broker":"kafka-0.dev-tier:9092","clientId":"clientId","stack":"Error: getaddrinfo ENOTFOUND kafka-0.dev-tier\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:22.356Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-2.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:22.356Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":4,"retryTime":5666}
{"level":"ERROR","timestamp":"2022-05-25T15:46:25.430Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-2.dev-tier:9092","clientId":"clientId"}
{"level":"ERROR","timestamp":"2022-05-25T15:46:25.430Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":5,"retryTime":15536}
[example/consumer] Connection timeout KafkaJSNonRetriableError
  Caused by: KafkaJSConnectionError: Connection timeout
    at Timeout.onTimeout [as _onTimeout] (/usr/src/app/node_modules/kafkajs/src/network/connection.js:223:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  name: 'KafkaJSNumberOfRetriesExceeded',
  retriable: false,
  helpUrl: undefined,
  retryCount: 5,
  retryTime: 15536,
  [cause]: KafkaJSConnectionError: Connection timeout
      at Timeout.onTimeout [as _onTimeout] (/usr/src/app/node_modules/kafkajs/src/network/connection.js:223:23)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7) {
    retriable: true,
    helpUrl: undefined,
    broker: 'kafka-2.dev-tier:9092',
    code: undefined,
    [cause]: undefined
  }
}
```

**Environment:**
 - OS: Debian 11
 - KafkaJS version: 2.0.1
 - Kafka version: 3.2
 - NodeJS version: 16

**Additional context**
It seams that the consumer isn't completely set up when consumer.run() has finished, which causes a race condition for the subsequent consumer.run(). If I add a timeout between each consumers (uncomment the 2 commented lines in index.js) it works as expected again.

**Comment by tmalahie** [comment]
Hey again
I updated my Docker version and it seams to have resolved the issue :)
