### ISSUE TITLE
How to resolve nodejs deprecation warning - RFC 6066 - seems to be coming from kafkajs

### ISSUE THREAD

**Issue by adbdkb** [tulios/kafkajs#1407]
I am trying to create a sample nodejs app for kafkajs producer and consumer. When I start the app, I get the deprecation warning. So, I tried with --trace-deprecation flag and get this stack trace. How can I fix it? I tried using different versions of kafkajs, but still keep getting this error

 `   (node:61452) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
       at Object.connect (node:_tls_wrap:1670:15)
       at /BitBucketRepos/node-js/SimpleProducerConsumer/node_modules/kafkajs/src/network/socketFactory.js:12:13
       at module.exports (/BitBucketRepos/node-js/SimpleProducerConsumer/node_modules/kafkajs/src/network/socket.js:24:18)
       at /BitBucketRepos/node-js/SimpleProducerConsumer/node_modules/kafkajs/src/network/connection.js:240:23
       at new Promise (<anonymous>)
       at Connection.connect (/BitBucketRepos/node-js/SimpleProducerConsumer/node_modules/kafkajs/src/network/connection.js:167:12)
       at ConnectionPool.getConnection (/BitBucketRepos/node-js/SimpleProducerConsumer/node_modules/kafkajs/src/network/connectionPool.js:56:24)
       at Broker.connect (/BitBucketRepos/node-js/SimpleProducerConsumer/node_modules/kafkajs/src/broker/index.js:86:52)
       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
       at async /BitBucketRepos/node-js/SimpleProducerConsumer/node_modules/kafkajs/src/cluster/brokerPool.js:319:9
`

I have tried with using ksfkajs version 1.15.0, 1.16.0, 2.1.0 in package.json - but keep getting the same error.

My current NodeJs version is 18.0.0

How can I eliminate this warning?

**Comment by Nevon** [comment]
This can be worked around by setting `ssl.servername` to a hostname. If you don't set it, we default it to the broker host, which can be an IP. You can see an example of fixing this in our example clients: https://github.com/tulios/kafkajs/blob/a0ef9556f89e638c2fc26ccf2fa47be44a3fb7bc/examples/admin.js#L9-L24

#1425 will fix this by not defaulting the servername if the host is an IP address.
