### ISSUE TITLE
Retriable Error "KafkaJSRequestTimeoutError" was thrown uncaught during a rebalance

### ISSUE THREAD

**Issue by ModernTrollfare** [tulios/kafkajs#1410]
**Describe the bug**
A "KafkaJSRequestTimeoutError" was thrown, uncaught in our user App. It was marked "Retriable: true", but seemingly no auto-retry was carried out.

**To Reproduce**
There are no clear steps to reproduce this, but the following is observed:

1. A rebalance was triggered. Our Topic has exactly 1 Consumer per group as each consumer was assigned a unique Consumer Group ID during KafkaJS instance creation, and they have exactly 1 partition. Thus, we assume that a Heartbeat Timeout is triggered.
2. KafkaJS reported error "This is not the correct coordinator for this group".
3. KafkaJS reported warn "The group is rebalanceing, re-joining".
4. After a few seconds, the error is thrown:
`KafkaJSRequestTimeoutError: Request SyncGroup(key: 14, version: 3) timed out.`

The timeouts used in KafkaJS:
```
connectionTimeout: 5000
requestTimeout: 10000
maxRetryTime: 30000
retries: 3
```
restartOnFailure is default (returning true)

**Expected behavior**
The library retries connection and re-joins indefinitely without throwing an uncaught error.

**Observed behavior**
An uncaught error marked "retriable: true" was thrown, and crashes the application.
Logs:
`2022-07-08T01:13:07.923Z ERROR [Connection] Response OffsetCommit(key: 8, version: 5) (meta:{"level":"error","logger":"kafkajs","broker":"<broker>:9092","clientId":"<clientID>","error":"This is not the correct coordinator for this group","correlationId":14179,"size":78})`
`2022-07-08T01:13:07.925Z WARN [Runner] The group is rebalancing, re-joining (meta: {"level":"warn","logger":"kafkajs","groupId":"<unique groupID>","memberId":"<memberID>","error":"This is not the correct coordinator for this group"})`
Error thrown:
`KafkaJSRequestTimeoutError: Request SyncGroup(key: 14, version:3) timed out
    at SocketRequest.timeoutRequest (node_modules/kafkajs/src/network/requestQueue/socketRequest.js:107:19)
    at node_modules/kafkajs/src/network/requestQueue/index.js:93:21
    at Map.forEach (<anonymous>)
    at Timeout._onTimeout (node_modules/kafkajs/src/network/requestQueue/index.js:91:23)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7) {
  retriable: true,
  helpUrl: undefined,
  broker: <broker>,
  correlationId: 3,
  createdAt: <epoch timestamp>,
  sentAt: <epoch timestamp>,
  pendingDuration: 0
}`

**Environment:**
 - KafkaJS v2.0.1
 - Ubuntu 21
 - nodejs v18.2
 - Kafka is hosted on Confluent cloud.
 - One single broker specified in application.

**Comment by ModernTrollfare** [comment]
Seems to be resolved with the fix mentioned in #1382 and #1384.

The current observation on v2.1.0:
- Retrier correctly catches a throw during reconnect attempts and fails with a line of log instead of crashing the whole app.
- The 'crash' during retry is catchable through instrumentation event interface.
