### ISSUE TITLE
The value of "offset" is out of range. It must be >= 0 and <= 9902. Received 9906 KafkaJSNonRetriableError

### ISSUE THREAD

**Issue by EmnaDrissi** [tulios/kafkajs#1418]
Hello
I have a strange behaviour (random) of my kafkaJs producer in production
throwing the below exceptions

I am using the below configurations
**Environment:**
 - KafkaJS version 1.150
 - Kafka version 2.2.1
 - NodeJS version 16

with the default config of the producer

The value of "offset" is out of range. It must be >= 0 and <= 9902. Received 9906 KafkaJSNonRetriableError
Caused by: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 9902. Received 9906
at new NodeError (node:internal/errors:372:5)
at boundsError (node:internal/buffer:86:9)
at Buffer.readInt32BE (node:internal/buffer:482:5)
at Decoder.readInt32 (/node_modules/kafkajs/src/protocol/decoder.js:50:31)
at /node_modules/kafkajs/src/protocol/requests/metadata/v5/response.js:46:33
at Decoder.readArray (/node_modules/kafkajs/src/protocol/decoder.js:149:18)
at partitionMetadata (/node_modules/kafkajs/src/protocol/requests/metadata/v5/response.js:46:16)
at Decoder.readArray (/node_modules/kafkajs/src/protocol/decoder.js:149:18)
at topicMetadata (/node_modules/kafkajs/src/protocol/requests/metadata/v5/response.js:38:30)
at Decoder.readArray (/node_modules/kafkajs/src/protocol/decoder.js:149:18) {
name: 'KafkaJSNumberOfRetriesExceeded',
retriable: false,
helpUrl: undefined,
originalError: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 9902. Received 9906
at new NodeError (node:internal/errors:372:5)
at boundsError (node:internal/buffer:86:9)
at Buffer.readInt32BE (node:internal/buffer:482:5)
at Decoder.readInt32 (/node_modules/kafkajs/src/protocol/decoder.js:50:31)
at /node_modules/kafkajs/src/protocol/requests/metadata/v5/response.js:46:33
at Decoder.readArray (/node_modules/kafkajs/src/protocol/decoder.js:149:18)
at partitionMetadata (/node_modules/kafkajs/src/protocol/requests/metadata/v5/response.js:46:16)
at Decoder.readArray (/node_modules/kafkajs/src/protocol/decoder.js:149:18)
at topicMetadata (/node_modules/kafkajs/src/protocol/requests/metadata/v5/response.js:38:30)
at Decoder.readArray (/node_modules/kafkajs/src/protocol/decoder.js:149:18) {
code: 'ERR_OUT_OF_RANGE'

Timeout while acquiring lock (426 waiting locks): "updating target topics" KafkaJSNonRetriableError
  Caused by: KafkaJSLockTimeout: Timeout while acquiring lock (426 waiting locks): "updating target topics"
    at Timeout._onTimeout (/node_modules/kafkajs/src/utils/lock.js:48:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  name: 'KafkaJSNumberOfRetriesExceeded',
  retriable: false,
  helpUrl: undefined,
  originalError: KafkaJSLockTimeout: Timeout while acquiring lock (426 waiting locks): "updating target topics"
      at Timeout._onTimeout (/node_modules/kafkajs/src/utils/lock.js:48:23)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7) {
    retriable: false,
    helpUrl: undefined
  },
  retryCount: 0,
  retryTime: 291
}

**Comment by EmnaDrissi** [comment]
@Nevon  you have any idea of the root cause?
