### ISSUE TITLE
Help: Code/ App crashes when KafkaJs is crashed.  

### ISSUE THREAD

**Issue by mai1x9** [tulios/kafkajs#1481]
General question, if kafkajs crashes, the entire application gets exited or stopped. How to handle such errors. 
For Eg: Below is the error log data by kafka js.
**Error: `KafkaJSGroupCoordinatorNotFound`**
```
{
    "level":"ERROR","timestamp":"2022-11-17T06:10:47.623Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSGroupCoordinatorNotFound: Failed to find group coordinator","groupId":"nlp-group01","stack":"KafkaJSGroupCoordinatorNotFound: Failed to find group coordinator\n    at Cluster.findGroupCoordinatorMetadata (/home/kafkacluster/consumer/node_modules/kafkajs/src/cluster/index.js:419:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /home/kafkacluster/consumer/node_modules/kafkajs/src/cluster/index.js:346:33\n    at async ConsumerGroup.[private:ConsumerGroup:join] (/home/kafkacluster/consumer/node_modules/kafkajs/src/consumer/consumerGroup.js:167:24)\n    at async /home/kafkacluster/consumer/node_modules/kafkajs/src/consumer/consumerGroup.js:335:9\n    at async Runner.start (/home/kafkacluster/consumer/node_modules/kafkajs/src/consumer/runner.js:84:7)\n    at async start (/home/kafkacluster/consumer/node_modules/kafkajs/src/consumer/index.js:243:7)\n    at async Object.run (/home/kafkacluster/consumer/node_modules/kafkajs/src/consumer/index.js:304:5)"

}
    
```
And the application is crashed. 

My Question is how to handle such errors from the code. try catch does not seem to be working though(i suppose from stack trace, i do not know where exactly error is thrown, nevertheless i wrapped entire kafka code in try catch but in vain.

**Comment by mai1x9** [comment]
Answering to my own question.
Refer to REF: https://github.com/tulios/kafkajs/issues/1443 for handling the crash events.
Kafkajs provides `consumer.crash` event which can be handled from code. Refer to instrumentation events for more information.
https://kafka.js.org/docs/instrumentation-event
