### ISSUE TITLE
Microsoft EventHub connections reset on producer.close()

### ISSUE THREAD

**Issue by nicolasbron** [tulios/kafkajs#1487]
**Describe the bug**
I'm trying to synchronize kafkajs producer with EventHub (using kafka integration on Azure side). 
Everything works fine as long as I'm using the event-hub npm package distributed by Microsoft.
When I configure it with kafkajs implementation messages are correctly published to the topic but I'm getting error in logs while closing the producer.

{"level":"ERROR","timestamp":"2022-11-21T06:18:42.692Z","logger":"kafkajs","message":"[Connection] Connection error: read ECONNRESET","broker":"<hostname>.servicebus.windows.net:9093","clientId":"<client_id>","stack":"Error: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)\n    at TLSWrap.callbackTrampoline (internal/async_hooks.js:130:17)"}

I simplified the code to:
`    const kafka : Kafka = new Kafka({
        clientId: clientId,
        brokers: ['<hostname>.servicebus.windows.net:9093'],
        ssl: true,
        sasl: {
            mechanism: 'plain',
            username: saslUsername,
            password: saslPassword,
        }
    });
    const producer : Producer = kafka.producer({ createPartitioner: Partitioners.DefaultPartitioner });
    await producer.connect()
    await producer.send({
    topic: eventTopic,
    messages: [
        { value: 'Hello Kafka user!' },
    ],
    })

    await producer.disconnect()`

When I use above for connecting to kafka server everything works without any problem and no error is thrown during disconnect operation.

**To Reproduce**
Configure kafkajs to publish to EventHub with above code and for disconnect operation you will receive connection reset error in logs. But still events are correctly published to topic.

**Expected behavior**
No error should be thrown while disconnecting producer.

**Observed behavior**
A clear and concise description of what *did* happen. Please include any relevant logs [with the log level set to debug](https://kafka.js.org/docs/configuration#logging).

**Environment:**
 - OS: BigSur 11.6.8
 - KafkaJS version 2.2.2
 - NodeJS version v16.18.1
 

**Additional context**

**Comment by nicolasbron** [comment]
Logs:
`[2022-11-21T07:03:28.947Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:28.945Z","logger":"kafkajs","message":"[Connection] Connecting","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","ssl":true,"sasl":true}
[2022-11-21T07:03:29.104Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.104Z","logger":"kafkajs","message":"[Connection] Request ApiVersions(key: 18, version: 2)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":0,"expectResponse":true,"size":32}
[2022-11-21T07:03:29.142Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.141Z","logger":"kafkajs","message":"[Connection] Response ApiVersions(key: 18, version: 2)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":0,"size":158,"data":{"errorCode":0,"apiVersions":[{"apiKey":0,"minVersion":3,"maxVersion":7},{"apiKey":1,"minVersion":4,"maxVersion":6},{"apiKey":2,"minVersion":0,"maxVersion":7},{"apiKey":3,"minVersion":0,"maxVersion":5},{"apiKey":8,"minVersion":0,"maxVersion":8},{"apiKey":9,"minVersion":0,"maxVersion":8},{"apiKey":10,"minVersion":0,"maxVersion":1},{"apiKey":11,"minVersion":0,"maxVersion":7},{"apiKey":12,"minVersion":0,"maxVersion":4},{"apiKey":13,"minVersion":0,"maxVersion":4},{"apiKey":14,"minVersion":0,"maxVersion":5},{"apiKey":15,"minVersion":0,"maxVersion":1},{"apiKey":16,"minVersion":0,"maxVersion":1},{"apiKey":17,"minVersion":0,"maxVersion":1},{"apiKey":18,"minVersion":0,"maxVersion":3},{"apiKey":19,"minVersion":0,"maxVersion":6},{"apiKey":20,"minVersion":0,"maxVersion":2},{"apiKey":22,"minVersion":0,"maxVersion":1},{"apiKey":23,"minVersion":0,"maxVersion":0},{"apiKey":32,"minVersion":0,"maxVersion":2},{"apiKey":36,"minVersion":0,"maxVersion":1},{"apiKey":37,"minVersion":0,"maxVersion":1},{"apiKey":42,"minVersion":0,"maxVersion":0},{"apiKey":47,"minVersion":0,"maxVersion":0}],"throttleTime":0,"clientSideThrottleTime":0}}
[2022-11-21T07:03:29.143Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.142Z","logger":"kafkajs","message":"[Broker] Verified support for SaslAuthenticate","broker":"<hostname>.servicebus.windows.net:9093","supportAuthenticationProtocol":true}
[2022-11-21T07:03:29.145Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.143Z","logger":"kafkajs","message":"[Connection] Request SaslHandshake(key: 17, version: 1)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":1,"expectResponse":true,"size":39}
[2022-11-21T07:03:29.176Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.175Z","logger":"kafkajs","message":"[Connection] Response SaslHandshake(key: 17, version: 1)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":1,"size":30,"data":{"errorCode":0,"enabledMechanisms":["PLAIN","OAUTHBEARER"]}}
[2022-11-21T07:03:29.178Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.176Z","logger":"kafkajs","message":"[SaslAuthenticator-PLAIN] Authenticate with SASL PLAIN","broker":"<hostname>.servicebus.windows.net:9093"}
[2022-11-21T07:03:29.178Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.177Z","logger":"kafkajs","message":"[Connection] Request SaslAuthenticate(key: 36, version: 1)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":2,"expectResponse":true,"size":235}
[2022-11-21T07:03:29.209Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.208Z","logger":"kafkajs","message":"[Connection] Response SaslAuthenticate(key: 36, version: 1)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":2,"size":20,"data":{"errorCode":0,"errorMessage":null,"authBytes":{"type":"Buffer","data":[0,0,0,0]},"sessionLifetimeMs":"0"}}
[2022-11-21T07:03:29.210Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.209Z","logger":"kafkajs","message":"[SaslAuthenticator-PLAIN] SASL PLAIN authentication successful","broker":"<hostname>.servicebus.windows.net:9093"}
[2022-11-21T07:03:29.212Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.211Z","logger":"kafkajs","message":"[Connection] Request Metadata(key: 3, version: 5)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":3,"expectResponse":true,"size":52}
[2022-11-21T07:03:29.250Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.246Z","logger":"kafkajs","message":"[Connection] Response Metadata(key: 3, version: 5)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":3,"size":150,"data":{"throttleTime":0,"brokers":[{"nodeId":0,"host":"<hostname>.servicebus.windows.net","port":9093,"rack":null}],"clusterId":"<hostname>.servicebus.windows.net","controllerId":0,"topicMetadata":[{"topicErrorCode":0,"topic":"<topic>","isInternal":false,"partitionMetadata":[{"partitionErrorCode":0,"partitionId":0,"leader":0,"replicas":[],"isr":[],"offlineReplicas":[]}]}]}}
[2022-11-21T07:03:29.251Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.249Z","logger":"kafkajs","message":"[Connection] Request Produce(key: 0, version: 7)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":4,"expectResponse":true,"size":156}
[2022-11-21T07:03:29.308Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.308Z","logger":"kafkajs","message":"[Connection] Response Produce(key: 0, version: 7)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":4,"size":61,"data":{"topics":[{"topicName":"<topic>","partitions":[{"partition":0,"errorCode":0,"baseOffset":"34","logAppendTime":"1669014211437","logStartOffset":"0"}]}],"throttleTime":0,"clientSideThrottleTime":0}}
[2022-11-21T07:03:29.309Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.309Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.310Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.309Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.311Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.311Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.311Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.311Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.312Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.311Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.313Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.312Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.314Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.313Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.315Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.314Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.350Z] {"level":"ERROR","timestamp":"2022-11-21T07:03:29.349Z","logger":"kafkajs","message":"[Connection] Connection error: read ECONNRESET","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","stack":"Error: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)\n    at TLSWrap.callbackTrampoline (internal/async_hooks.js:130:17)"}
[2022-11-21T07:03:29.351Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.350Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.352Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.352Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}`

**Comment by nicolasbron** [comment]
```
[2022-11-21T07:03:28.947Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:28.945Z","logger":"kafkajs","message":"[Connection] Connecting","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","ssl":true,"sasl":true}
[2022-11-21T07:03:29.104Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.104Z","logger":"kafkajs","message":"[Connection] Request ApiVersions(key: 18, version: 2)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":0,"expectResponse":true,"size":32}
[2022-11-21T07:03:29.142Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.141Z","logger":"kafkajs","message":"[Connection] Response ApiVersions(key: 18, version: 2)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":0,"size":158,"data":{"errorCode":0,"apiVersions":[{"apiKey":0,"minVersion":3,"maxVersion":7},{"apiKey":1,"minVersion":4,"maxVersion":6},{"apiKey":2,"minVersion":0,"maxVersion":7},{"apiKey":3,"minVersion":0,"maxVersion":5},{"apiKey":8,"minVersion":0,"maxVersion":8},{"apiKey":9,"minVersion":0,"maxVersion":8},{"apiKey":10,"minVersion":0,"maxVersion":1},{"apiKey":11,"minVersion":0,"maxVersion":7},{"apiKey":12,"minVersion":0,"maxVersion":4},{"apiKey":13,"minVersion":0,"maxVersion":4},{"apiKey":14,"minVersion":0,"maxVersion":5},{"apiKey":15,"minVersion":0,"maxVersion":1},{"apiKey":16,"minVersion":0,"maxVersion":1},{"apiKey":17,"minVersion":0,"maxVersion":1},{"apiKey":18,"minVersion":0,"maxVersion":3},{"apiKey":19,"minVersion":0,"maxVersion":6},{"apiKey":20,"minVersion":0,"maxVersion":2},{"apiKey":22,"minVersion":0,"maxVersion":1},{"apiKey":23,"minVersion":0,"maxVersion":0},{"apiKey":32,"minVersion":0,"maxVersion":2},{"apiKey":36,"minVersion":0,"maxVersion":1},{"apiKey":37,"minVersion":0,"maxVersion":1},{"apiKey":42,"minVersion":0,"maxVersion":0},{"apiKey":47,"minVersion":0,"maxVersion":0}],"throttleTime":0,"clientSideThrottleTime":0}}
[2022-11-21T07:03:29.143Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.142Z","logger":"kafkajs","message":"[Broker] Verified support for SaslAuthenticate","broker":"<hostname>.servicebus.windows.net:9093","supportAuthenticationProtocol":true}
[2022-11-21T07:03:29.145Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.143Z","logger":"kafkajs","message":"[Connection] Request SaslHandshake(key: 17, version: 1)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":1,"expectResponse":true,"size":39}
[2022-11-21T07:03:29.176Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.175Z","logger":"kafkajs","message":"[Connection] Response SaslHandshake(key: 17, version: 1)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":1,"size":30,"data":{"errorCode":0,"enabledMechanisms":["PLAIN","OAUTHBEARER"]}}
[2022-11-21T07:03:29.178Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.176Z","logger":"kafkajs","message":"[SaslAuthenticator-PLAIN] Authenticate with SASL PLAIN","broker":"<hostname>.servicebus.windows.net:9093"}
[2022-11-21T07:03:29.178Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.177Z","logger":"kafkajs","message":"[Connection] Request SaslAuthenticate(key: 36, version: 1)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":2,"expectResponse":true,"size":235}
[2022-11-21T07:03:29.209Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.208Z","logger":"kafkajs","message":"[Connection] Response SaslAuthenticate(key: 36, version: 1)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":2,"size":20,"data":{"errorCode":0,"errorMessage":null,"authBytes":{"type":"Buffer","data":[0,0,0,0]},"sessionLifetimeMs":"0"}}
[2022-11-21T07:03:29.210Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.209Z","logger":"kafkajs","message":"[SaslAuthenticator-PLAIN] SASL PLAIN authentication successful","broker":"<hostname>.servicebus.windows.net:9093"}
[2022-11-21T07:03:29.212Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.211Z","logger":"kafkajs","message":"[Connection] Request Metadata(key: 3, version: 5)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":3,"expectResponse":true,"size":52}
[2022-11-21T07:03:29.250Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.246Z","logger":"kafkajs","message":"[Connection] Response Metadata(key: 3, version: 5)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":3,"size":150,"data":{"throttleTime":0,"brokers":[{"nodeId":0,"host":"<hostname>.servicebus.windows.net","port":9093,"rack":null}],"clusterId":"<hostname>.servicebus.windows.net","controllerId":0,"topicMetadata":[{"topicErrorCode":0,"topic":"<topic>","isInternal":false,"partitionMetadata":[{"partitionErrorCode":0,"partitionId":0,"leader":0,"replicas":[],"isr":[],"offlineReplicas":[]}]}]}}
[2022-11-21T07:03:29.251Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.249Z","logger":"kafkajs","message":"[Connection] Request Produce(key: 0, version: 7)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":4,"expectResponse":true,"size":156}
[2022-11-21T07:03:29.308Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.308Z","logger":"kafkajs","message":"[Connection] Response Produce(key: 0, version: 7)","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","correlationId":4,"size":61,"data":{"topics":[{"topicName":"<topic>","partitions":[{"partition":0,"errorCode":0,"baseOffset":"34","logAppendTime":"1669014211437","logStartOffset":"0"}]}],"throttleTime":0,"clientSideThrottleTime":0}}
[2022-11-21T07:03:29.309Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.309Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.310Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.309Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.311Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.311Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.311Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.311Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.312Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.311Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.313Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.312Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.314Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.313Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.315Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.314Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.350Z] {"level":"ERROR","timestamp":"2022-11-21T07:03:29.349Z","logger":"kafkajs","message":"[Connection] Connection error: read ECONNRESET","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer","stack":"Error: read ECONNRESET\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)\n    at TLSWrap.callbackTrampoline (internal/async_hooks.js:130:17)"}
[2022-11-21T07:03:29.351Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.350Z","logger":"kafkajs","message":"[Connection] disconnecting...","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
[2022-11-21T07:03:29.352Z] {"level":"DEBUG","timestamp":"2022-11-21T07:03:29.352Z","logger":"kafkajs","message":"[Connection] disconnected","broker":"<hostname>.servicebus.windows.net:9093","clientId":"consumer"}
```
