### ISSUE TITLE
Error on "undefined" header attributes

### ISSUE THREAD

**Issue by ghdoergeloh** [tulios/kafkajs#1500]
**Describe the bug**
An error pops up when I emit a message with a "undefined" header attribute.

**To Reproduce**

```typescript
  const kafkaConnection = new Kafka({
    clientId: 'any_client',
    brokers: KAFKA_BROKERS,
  });
  const producer = kafkaConnection.producer();
  await producer.connect();
  await producer.send({
      topic: KAFKA_TOPIC,
      messages: [{
        headers: {
          test: undefined
        },
        value: JSON.stringify({test:'text'),
      }],
  });
  await producer.disconnect();
```

**Expected behavior**
undefined headers should simply be ignored, since the type says undefined is allowed ( #924 ).

**Observed behavior**
```
{"level":"ERROR","timestamp":"2022-12-08T11:58:21.843Z","logger":"kafkajs","message":"[Producer] The \"string\" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined","retryCount":0,"retryTime":258}
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at Function.byteLength (node:buffer:735:11)
    at sizeOfHeaders (.node_modules/kafkajs/src/protocol/recordBatch/record/v0/index.js:55:30)
    at module.exports (./node_modules/kafkajs/src/protocol/recordBatch/record/v0/index.js:38:5)
    at ./node_modules/kafkajs/src/protocol/requests/produce/v3/request.js:96:5
    at Array.map (<anonymous>)
    at ./node_modules/kafkajs/src/protocol/requests/produce/v3/request.js:95:28
    at ./node_modules/kafkajs/src/protocol/requests/produce/v3/request.js:70:13
    at encode (./node_modules/kafkajs/src/protocol/requests/produce/v3/request.js:46:15)
    at module.exports (./node_modules/kafkajs/src/protocol/request.js:4:25) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Environment:**
 - OS: Linux Ubuntu
 - KafkaJS version: 2.2.3
 - NodeJS version v16.18.1

**Comment by ghdoergeloh** [comment]
Found this issue with the cloudevents js sdk. Workaround for me is to delete undefined headers:
```ts
    for (const key in message.headers) {
      if (message.headers[key] === undefined) {
        delete message.headers[key];
      }
    }
```
