### ISSUE TITLE
Facing consumer disconnect issue.

### ISSUE THREAD

**Issue by abhinavgautam07** [tulios/kafkajs#1511]
**Describe the bug**

We are facing the error of [Consumer] crash.
`{"level":"ERROR","timestamp":"2023-01-02T02:46:51.057Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNumberOfRetriesExceeded: Not connected","groupId":"customer-recommendation-service","retryCount":5,"stack":"KafkaJSNonRetriableError\n  Caused by: KafkaJSConnectionError: Not connected\n    at Connection.failIfNotConnected (/usr/src/app/node_modules/kafkajs/src/network/connection.js:357:13)\n    at Connection.send (/usr/src/app/node_modules/kafkajs/src/network/connection.js:278:10)\n    at Broker.heartbeat (/usr/src/app/node_modules/kafkajs/src/broker/index.js:355:34)\n    at ConsumerGroup.heartbeat (/usr/src/app/node_modules/kafkajs/src/consumer/consumerGroup.js:335:30)\n    at Runner.fetch (/usr/src/app/node_modules/kafkajs/src/consumer/runner.js:407:30)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/proc
ess/task_queues.js:95:5)\n    at async /usr/src/app/node_modules/kafkajs/src/consumer/runner.js:422:9"}`

To add more context, we have implementated our own rate-limit,  where we pause and resume for the consumer-group.
During resume, we get the following error.
`Consumer group was not initialized, consumer#run must be called first","error_stack":"KafkaJSNonRetriableError: Consumer group was not initialized, consumer#run must be called first`

**To Reproduce**
Still not able to get the Root Cause of the issue, thus not able to reproduce it.

**Expected behavior**

The error should not have happened. Because there is no connection issue with the brokers. The metrics of brokers also seem to be fine.

**Observed behavior**

One observation, that I have is this error becomes more frequent when traffic increases. This might be due to autoscaling on traffic increase.

**Environment:**

 - OS: Running on docker, using ubuntu as base image.
 - KafkaJS version: 1.13.0
 - Kafka version: 3.1.0
 - NodeJS version: 14.18.0

**Additional context**

**Comment by flysen** [comment]
You mentioned `our own rate-limit` you might check the heartbeat else you get thrown out from the consumer-group. I also recommend to use the rate limit on the Kafka broker side.
