### ISSUE TITLE
Consumer did not restart automatically on crash

### ISSUE THREAD

**Issue by vishalailani** [tulios/kafkajs#1513]
Using kafkaJS for NodeJS services to connect with kafka. Freq getting these errors as consumers getting disconnected and crashed. after that service containers also getting crashed(sometimes). 

getting below errors:

`{"level":"ERROR","timestamp":"2023-01-04T13:01:28.691Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNumberOfRetriesExceeded: Not connected","groupId":"test-service","retryCount":5,"stack":"KafkaJSNonRetriableError\n  Caused by: KafkaJSConnectionError: Not connected\n    at Connection.failIfNotConnected (/usr/src/app/node_modules/kafkajs/src/network/connection.js:357:13)\n    at Connection.send (/usr/src/app/node_modules/kafkajs/src/network/connection.js:278:10)\n    at Broker.heartbeat (/usr/src/app/node_modules/kafkajs/src/broker/index.js:355:34)\n    at ConsumerGroup.heartbeat (/usr/src/app/node_modules/kafkajs/src/consumer/consumerGroup.js:335:30)\n    at Runner.fetch (/usr/src/app/node_modules/kafkajs/src/consumer/runner.js:407:30)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /usr/src/app/node_modules/kafkajs/src/consumer/runner.js:422:9"}`

Using kafka version 3.1.1
kafkaJS version 1.13.0

**Comment by vishalailani** [comment]
Found a similar ticket but did not help as already on higher version.
https://github.com/tulios/kafkajs/issues/1011

**Comment by vishalailani** [comment]
@tulios , anything related to kafkaJS ?

**Comment by OneCricketeer** [comment]
According to the error - `NumberOfRetriesExceeded` it *did* restart automatically a certain number of times, and only *then* did it crash.
