### ISSUE TITLE
The const INT_32_MAX_VALUE set wrong value

### ISSUE THREAD

**Issue by abdxy** [tulios/kafkajs#1524]
**Describe the bug**

The const INT_32_MAX_VALUE in constants.js file is set to the wrong value Math.pow(2, 32) instead of Math.pow(2, 31).
the max int 32-bit is equal to 2147483648, not 4294967296.
this cause out of range error on correlationId.

**To Reproduce**
The Error happens randomly after the service runs for a long time.

**Observed behavior**
The Error:
{code":"ERR_OUT_OF_RANGE","stack":"RangeError [ERR_OUT_OF_RANGE]: The value of \"value\" is out of range. It must be >= -2147483648 and <= 2147483647. Received 2184897912\n    at checkInt (internal/buffer.js:69:11)\n    at writeU_Int32BE (internal/buffer.js:799:3)\n    at Buffer.writeInt32BE (internal/buffer.js:887:10)\n    at Encoder.writeInt32 (/node_modules/kafkajs/src/protocol/encoder.js:110:14)\n    at module.exports (/node_modules/kafkajs/src/protocol/request.js:8:6)\n    at async sendRequest (/node_modules/kafkajs/src/network/connection.js:294:30)\n    at async Connection.send (/node_modules/kafkajs/src/network/connection.js:321:53)\n    at async Broker.[private:Broker:sendRequest] (/node_modules/kafkajs/src/broker/index.js:890:14)\n    at async Broker.produce (/node_modules/kafkajs/src/broker/index.js:254:12)\n    at async /node_modules/kafkajs/src/producer/sendMessages.js:82:28","type":"Error","msg":"The value of \"value\" is out of range. It must be >= -2147483648 and <= 2147483647. Received 2184897912"}

**Environment:**
 - OS: [Ubuntu 20.04.5]
 - KafkaJS version [1.15.0]
 - Kafka version [3.3.1]
 - NodeJS version [12.13.1]

**Comment by AlessandroMinoccheri** [comment]
This problem is fixed in the recent version I have seen.
