### ISSUE TITLE
What to do with error : KafkaJSProtocolError: The group is rebalancing, so a rejoin is needed

### ISSUE THREAD

**Issue by Patafix** [tulios/kafkajs#1527]
Everything work great, but when a rebalance is happening on my consumer group, this error is logged and my service crash.

I see that the error : REBALANCE_IN_PROGRESS is no-retriable on the code and here https://kafka.apache.org/protocol#protocol_error_codes

Is it normal the whole nodejs app crash, what we should do to make it more robust ?

Details logs: 

> Response Heartbeat(key: 12, version: 3) {
>   timestamp: '2023-02-07T11:03:21.042Z',
>   logger: 'kafkajs',
>   broker: 'XXXXX',
>   clientId: 'XXXXX',
>   error: 'The group is rebalancing, so a rejoin is needed',
>   correlationId: 107,
>   size: 10
> } Connection ERROR
> 
> /home/node/app/node_modules/kafkajs/src/protocol/error.js:581
>   return new KafkaJSProtocolError(errorCodes.find(e => e.code === code) || unknownErrorCode(code))
>          ^
> KafkaJSProtocolError: The group is rebalancing, so a rejoin is needed
>     at createErrorFromCode (/home/node/app/node_modules/kafkajs/src/protocol/error.js:581:10)
>     at Object.parse (/home/node/app/node_modules/kafkajs/src/protocol/requests/heartbeat/v0/response.js:20:11)
>     at Connection.send (/home/node/app/node_modules/kafkajs/src/network/connection.js:433:35)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at Broker.[private:Broker:sendRequest] (/home/node/app/node_modules/kafkajs/src/broker/index.js:904:14)
>     at Broker.heartbeat (/home/node/app/node_modules/kafkajs/src/broker/index.js:343:12)
>     at /home/node/app/node_modules/kafkajs/src/consumer/consumerGroup.js:143:9
>     at Runner.heartbeat (/home/node/app/node_modules/kafkajs/src/consumer/runner.js:209:7)
> npm ERR! Lifecycle script `start` failed with error:

**Comment by maximblack** [comment]
I am using `kafkajs@2.0.0`, this solves the problem for me

**Comment by MistaTwista** [comment]
@Patafix what library version do you use?

**Comment by nipu-softic** [comment]
I am facing this problem too 
switch lib 2.0.0 but not solved also use "kafkajs": "^2.2.4" same issue

**Comment by devSajan** [comment]
facing same issue in "kafkajs": "^2.2.4"

**Comment by pawan-saxena** [comment]
any solution to solve this ?

**Comment by maksym-opanasenko-ft** [comment]
We faced the same issue with v2.4.2 and had to find a workaround. 

Symptoms:
1. this error is gotten:
`{"level":"ERROR","timestamp":"2024-11-04T16:43:51.386Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 3)","broker":"kafka:9092","clientId":"test","error":"The group is rebalancing, so a rejoin is needed","correlationId":63,"size":10}`

2. after the first one, this one is gotten:
`{"level":"ERROR","timestamp":"2024-11-04T16:44:31.459Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 3)","broker":"kafka:9092","clientId":"test","error":"The coordinator is not aware of this member","correlationId":105,"size":10}`

What happens: when rebalancing is happening, kafkajs still has some messages to call `eachMessage` with. That's explained by the fact that it uses `eachBatch` under the hood for `eachMessage`. The messages are still being processed, along with the errors described above being logged by the kafkajs logger. Also, for some reason, while rebalancing, the lib can't send heartbeats to the broker, which makes the broker consider a consumer dead so the consumer is kicked out. That causes another rebalancing, which causes another rebalancing and so on...

The solution that has worked for us is catching the `REBALANCE_IN_PROGRESS` error  while doing manual heartbeats and pausing the consumer manually which allows us to reconnect after rebalancing. If you're wondering why we call heartbeats manually -- because the processing time for our messages is unpredictable and can take from 3 seconds to 10 minutes. 
The error-detecting logic is taken from the source code of the library: https://github.com/tulios/kafkajs/blob/master/src/errors.js#L268

```
const { Kafka, logLevel, KafkaJSProtocolError } = require('kafkajs');

class CustomKafkaConsumer {
	constructor(kafkaConfig) {
		this.kafkaConfig = kafkaConfig;
		this.isRebalancing = false;
		this.heartbeatTimerId = null;
	}

	async start() {
		const kafka = new Kafka({
			clientId: 'your-client-id',
			brokers: this.kafkaConfig.brokers,
			logLevel: logLevel.INFO,
		});
		const consumer = kafka.consumer({ groupId: this.kafkaConfig.groupId });

		await consumer.connect();
		await consumer.subscribe({ topic: this.kafkaConfig.topic, fromBeginning: true });

		const topics = [{ topic: this.kafkaConfig.topic }];

		// The REBALANCING event is not emitted for some reason because of an issue with the library, but is emitted after
		// the consumer is paused manually. Let's handle pausing here just in case;
		consumer.on(consumer.events.REBALANCING, () => {
			console.log('REBALANCING: Pausing consumer');
			this.isRebalancing = true;
			consumer.pause(topics);
		});

		consumer.on(consumer.events.GROUP_JOIN, () => {
			if (this.isRebalancing) {
				console.log('GROUP_JOIN: Resuming consumer');
				this.isRebalancing = false;
				consumer.resume(topics);
			}
		});

		await consumer.run({
			eachMessage: async ({ message, heartbeat }) => {
				// The problem is that there is no other way of getting the heartbeat function outside `eachMessage` and `eachBatch`
				// in the current version if kafkajs.
				this.scheduleHeartbeatIfNeeded(heartbeat);

				if (this.isRebalancing) {
					// Pausing the consumer manually as kafkajs still has messages in its internal `eachBatch` to call `eachMessage` with;
					consumer.pause(topics);
					console.log('Consumer is rebalancing, pausing');
					return;
				}

				// the message processing goes here, don't forget to await if you process async
				console.log(`Processing message: ${message.key.toString()}`);
				await new Promise(resolve => setTimeout(resolve, 5000));
			},
		});
	}

	// If messages processing can take long time so we can periodically send heartbeats to the Kafka brokers to signal that the
	// consumer is still alive, and should not be removed from its group. The timerId is stored as a property of the class
	// to make sure we always run a single timer and avoid spamming with the calls
	scheduleHeartbeatIfNeeded(heartbeat) {
		if (this.heartbeatTimerId) return;

		this.heartbeatTimerId = setInterval(async () => {
			try {
				await heartbeat();
			} catch (error) {
				if (CustomKafkaConsumer.isKafkaJsRebalancingError(error)) {
					console.warn('Rebalancing in progress; pausing heartbeat');
					this.isRebalancing = true;
					return;
				}
				console.error('Error sending heartbeat:', error);
				throw error;
			}
		}, this.kafkaConfig.heartbeatInterval);
	}

	static isKafkaJsRebalancingError(error) {
		return (
			error instanceof KafkaJSProtocolError &&
			// this check is taken from the library source: https://github.com/tulios/kafkajs/blob/master/src/errors.js#L268
			['REBALANCE_IN_PROGRESS', 'NOT_COORDINATOR_FOR_GROUP', 'ILLEGAL_GENERATION'].includes(error.type)
		);
	}
}

// Example usage:
const kafkaConfig = {
	brokers: ['localhost:9092'],
	topic: 'your-topic',
	groupId: 'your-group-id',
	heartbeatInterval: 3000,
};

const consumer = new CustomKafkaConsumer(kafkaConfig);
consumer.start().catch(console.error);

```

**Comment by aalok-simpplr** [comment]
Did anyone find a fix to this ?

**Comment by rivetmichael** [comment]
Same issue with `"kafkajs": "2.2.4",`

**Comment by maksym-opanasenko-ft** [comment]
We had to create a logger adapter class and pass it as a `logCreator` param to narrow this down:
```
		this.kafka = new Kafka({
			clientId: this.config.clientId,
			brokers: this.config.brokers,
			logCreator: this.kafkaJsLogger.createLogFunction,
		});
```


```
import { logLevel, LogEntry, logCreator } from 'kafkajs';
import { FluentLogger } from '../logger';

class KafkaJsLogger extends FluentLogger {
	private static infoMessages = [
		'Specified group generation id is not valid',
		'The group is rebalancing, so a rejoin is needed',
		'This is not the correct coordinator for this group',
		'This server is not the leader for that topic-partition',
		`The coordinator is loading and hence can't process requests for this group`,
	];

	constructor(fluentLogger: FluentLogger) {
		super(fluentLogger);
		// createLogFunction is passed as a callback so the context must be bound
		this.createLogFunction = this.createLogFunction.bind(this);
	}

	createLogFunction(minLogLevel: logLevel): ReturnType<logCreator> {
		return (entry: LogEntry): void => {
			if (entry.level > minLogLevel) return;

			// Route log entries to FluentLogger based on Kafka log level
			switch (entry.level) {
				case logLevel.ERROR:
					this.handleError(entry);
					break;
				case logLevel.WARN:
					this.warn(entry.log);
					break;
				case logLevel.INFO:
					this.info(entry.log);
					break;
				case logLevel.DEBUG:
					this.debug(entry.log);
					break;
				default:
					this.info(entry.log);
			}
		};
	}

	private handleError({ log }: LogEntry): void {
		if (typeof log.error === 'string' && KafkaJsLogger.infoMessages.includes(log.error)) {
			this.info(log);
			return;
		}

		this.error(log);
	}
}

export { KafkaJsLogger };

```
