### ISSUE TITLE
KafkaJSNonRetriableError Caused by: KafkaJSError: This is not the correct coordinator for this group at /usr/app/node_modules/kafkajs/src/consumer/consumerGroup.js:361:17

### ISSUE THREAD

**Issue by Borduhh** [tulios/kafkajs#1536]
**Describe the bug**
Getting the following error when connecting to an AWS MSK cluster:

```
KafkaJSNonRetriableError Caused by: KafkaJSError: This is not the correct coordinator for this group at /usr/app/node_modules/kafkajs/src/consumer/consumerGroup.js:361:17 at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async Runner.start (/usr/app/node_modules/kafkajs/src/consumer/runner.js:84:7) at async start (/usr/app/node_modules/kafkajs/src/consumer/index.js:243:7)
```

**To Reproduce**
1. Start up an AWS MSK production system with 2 brokers
2. Create an AWS ECS consumer with KafkaJS
3. Consume data from topic X
4. Delete topic X via the Kafka CLI
5. Re-create topic X via the kafka CLI with the same name and config
6. Try to restart AWS ECS consumer

**Expected behavior**
The consumer should connect just as it did before.

**Observed behavior**
The consumer failed with the following error:
```
KafkaJSNonRetriableError
  Caused by: KafkaJSError: This is not the correct coordinator for this group
    at /usr/app/node_modules/kafkajs/src/consumer/consumerGroup.js:361:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Runner.start (/usr/app/node_modules/kafkajs/src/consumer/runner.js:84:7)
    at async start (/usr/app/node_modules/kafkajs/src/consumer/index.js:243:7)
```

**Comment by Borduhh** [comment]
It seems like this was a Kafka issue. A broker restart did solve the problem. I am not sure if there is a better way to solve it, however.

**Comment by shg95** [comment]
Hi @Borduhh ,

I see the above error and also other non retriable errors like topic authorization failed and consumer group authorization failed errors.
The weird part is the this happens suddenly, my consumer consumes the messages and suddenly while consuming it throws these authorization non-retriable errors. Due to this my consumer stalls and stops consuming messages untill I manually restart my pod. As you know its not the right way to do. Any suggestions?
I am also using MSK and my pod is in EKS using kafkajs.

**Comment by Jabbar-Zoop** [comment]
<img width="674" alt="Screenshot 2024-01-05 at 12 13 13 AM" src="https://github.com/tulios/kafkajs/assets/62978245/94a20f0a-2856-4e62-aff3-c2ecf726d25e">


I am also getting same issue suddenly consumer throw this error and i have added retry mechanism also but still not working as expected

**Comment by shg95** [comment]
@Jabbar-Zoop ,
Instead of just retrying to connect the consumer. Create a completely new Kafka connection in your retry logic.

**Comment by Jabbar-Zoop** [comment]
@shg95 This is what my code look like.Let me know what i am missing

```
this.consumer = this.queueInstance.consumer({
                groupId: this.kafkaConfig.groupId,
                rebalanceTimeout: 90000,
                retry: {
                    initialRetryTime: 500,
                    retries: 1,
                },
                heartbeatInterval: 30000,
                sessionTimeout: 90000,
                maxWaitTimeInMs: 10000,
                maxBytes: 1000 * 1000 * 500, // Partition * maxBytesPerPartition
                minBytes: 50 * 1000 * 1000,
                allowAutoTopicCreation: false,
                maxBytesPerPartition: 50 * 1000 * 1000,
                partitionAssigners: [PartitionAssigners.roundRobin],
            });
            await this.consumer.connect();
            
             this.consumer.on('consumer.crash', async (payload) => {
                console.log({
                    message: 'Consumer crashed event error',
                    context: { ...payload },
                });
                try {
                    await this.consumer.disconnect();
                    process.exit(1);
                } catch (error) {
                    console.error({
                        message: 'Error in consumer crash event',
                        error: error?.message ?? error,
                    });
                }
            });
            this.consumer.on('consumer.rebalancing', async (payload) => {
                console.log({
                    message: 'Consumer is reblancing',
                    context: { ...payload },
                });
            });
```

**Comment by shg95** [comment]
@Jabbar-Zoop ,
I see you are listening to the crash event and you disconnect the consumer and close the process.
What I was suggesting was, on crash event recreate the kafka connection instance. What I mean by this is that call this method again,

`const kafka = new Kafka({
  clientId: 'my-app',
  brokers: ['kafka1:9092', 'kafka2:9092']
})`

This will create a new kafka connection and then you connect the consumer.

**Comment by Jabbar-Zoop** [comment]
@shg95  i am getting below error frequently in an interval of 1hr what could be possible reason
```
{
error: {
code: 27
helpUrl: "https://kafka.js.org/docs/faq#what-does-it-mean-to-get-rebalance-in-progress-errors"
name: "KafkaJSProtocolError"
retriable: false
type: "REBALANCE_IN_PROGRESS"
}
error_message: "The group is rebalancing, so a rejoin is needed"
level: "error"
message: "Error occurred while consuming the queue_message."
```

**Comment by vchrm** [comment]
Hi, when running Kafka in our CI tests, I occasionally got the mentioned `This is not the correct coordinator for this group` followed by `KafkaJSConnectionClosedError: Closed connection` errors in subsequent tests.

In our case, to my surprise, what made Kafka prone to this occasional behaviour was the fact that I was connecting both the consumer as well as the producer to the broker in parallel:
```ts
await Promise.all([
  kafkaConsumer.connect(),
  kafkaProducer.connect()
]));
```

Switching it to the following in this order fixed it in our case 🤷:
```ts
await kafkaConsumer.connect();
await kafkaProducer.connect();
```

So I just wanted to leave this note here, maybe for somebody to find it and save a few hours of debugging. Cya ✌
