### ISSUE TITLE
Node js hangs up when kafka is stopped

### ISSUE THREAD

**Issue by gurjotmindgrep** [tulios/kafkajs#1539]
**Describe the bug**
Node js application hangs up, doesn't respond anything.

**To Reproduce**
1. Node js application and kafka are running as docker containers. Started node js application.
2. Got these logs "Consumer has joined the group", topic, etc.. and other kafkajs logs.
3. Published one event on the same topic on which consumer is listening. The event is consumed.
4. Stopped kafka docker container.
5. Node js application got stuck. It's not responding on any api (neither kafka event nor any other api)
6. But this behaviour occurs randomly. Rarely, I receive these logs and my application works fine. Most of the times, it got stuck.
`{"logger":"kafkajs","message":"Connection error: connect ECONNREFUSED 172.21.0.3:9092","broker":"kafka:9092","clientId":"kafka_proj","stack":"Error: connect ECONNREFUSED 172.21.0.3:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)"}
{"logger":"kafkajs","message":"Crash: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 172.21.0.3:9092","groupId":"kafka_proj","stack":"KafkaJSConnectionError: Connection error: connect ECONNREFUSED 172.21.0.3:9092\n    at Socket.onError (/workspace/development/gs_service/node_modules/kafkajs/src/network/connection.js:210:23)\n    at Socket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}
{"logger":"kafkajs","message":"Connection error: connect ECONNREFUSED 172.21.0.3:9092","broker":"kafka:9092","clientId":"kafka_proj","stack":"Error: connect ECONNREFUSED 172.21.0.3:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)"}
{"logger":"kafkajs","message":"Stopped","groupId":"kafka_proj"}
{"logger":"kafkajs","message":"Restarting the consumer in 300ms","retryTime":300,"groupId":"kafka_proj"}`

**Expected behavior**
The application should not get stuck even if kafka gets stopped.

**Observed behavior**
1. Node js application and kafka are running as docker containers. Started node js application.
2. Got these logs "Consumer has joined the group", topic, etc.. and other kafkajs logs.
3. Published one event on the same topic on which consumer is listening. The event is consumed.
4. Stopped kafka docker container.
5. Node js application got stuck. It's not responding on any api (neither kafka event nor any other api)
6. But this behaviour occurs randomly. Rarely, I receive these logs and my application works fine. Most of the times, it got stuck.
`{"logger":"kafkajs","message":"Connection error: connect ECONNREFUSED 172.21.0.3:9092","broker":"kafka:9092","clientId":"kafka_proj","stack":"Error: connect ECONNREFUSED 172.21.0.3:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)"}
{"logger":"kafkajs","message":"Crash: KafkaJSConnectionError: Connection error: connect ECONNREFUSED 172.21.0.3:9092","groupId":"kafka_proj","stack":"KafkaJSConnectionError: Connection error: connect ECONNREFUSED 172.21.0.3:9092\n    at Socket.onError (/workspace/development/gs_service/node_modules/kafkajs/src/network/connection.js:210:23)\n    at Socket.emit (node:events:527:28)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}
{"logger":"kafkajs","message":"Connection error: connect ECONNREFUSED 172.21.0.3:9092","broker":"kafka:9092","clientId":"kafka_proj","stack":"Error: connect ECONNREFUSED 172.21.0.3:9092\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)\n    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)"}
{"logger":"kafkajs","message":"Stopped","groupId":"kafka_proj"}
{"logger":"kafkajs","message":"Restarting the consumer in 300ms","retryTime":300,"groupId":"kafka_proj"}`

**Environment:**
 - OS: Debian 10 (buster)
 - KafkaJS version 2.0.1
 - Kafka version 3.1.2
 - NodeJS version v16.15.1

**Additional context**
Here is the code snipper which I am using:
`export default class KafkaMessageBus {
    config: Record<string, any>;
    kafka: Kafka;
    consumers: Record<string, Consumer> = {};
    subscribers: Record<string, boolean> = {};
    _producer?: Producer;
   
    async producer() {
        if (!this._producer) {
            let p = this.kafka.producer();
            try {
              await p.connect();
              nodeCleanup(function() {
                console.log('calling kafka producer disconnect...');
                //@ts-ignore
                this.disconnect();
              }.bind(p));
              this._producer = p;
            } catch(error){
              logger.error('Caught error in producer %o', error);
            }
        }
        return this._producer;
    }

    async consumer(groupId: string) {
        if (!this.consumers[groupId]) {
            let fn = this.consumers[groupId] = this.kafka.consumer({ groupId });
            try {
                await  this.consumers[groupId].connect();
                nodeCleanup(function() {
                  console.log('calling kafka consumer disconnect...');
                  //@ts-ignore
                  this.disconnect();
                }.bind(fn));
              } catch(error){
              logger.error('Caught error in consumer %o', error);
            }
        }
        return this.consumers[groupId];
    }

    async subscribe(topic: string, groupId: string, datasourceName: string,  processEvent:(event: GSCloudEvent)=>Promise<any>) {
        try {
          if (this.subscribers[topic]) {
            logger.info('kafka consumer already setup and running...');
            return;
          }

          let consumer = await this.consumer(groupId);
          await consumer.subscribe({ topic });

          const self = this;

          await consumer.run({
              eachMessage: async ({ topic, partition, message }) => {
                  . . . . . . . 
            });
          this.subscribers[topic] = true;
        } catch(error){
          logger.error('Caught error in subscribe %o', error);
        }
    }

    constructor(config: Record<string, any>) {
        this.config = config;
        logger.info('Connecting to kafka %o', config);

        let brokers = config.brokers;
        if (typeof(brokers) == 'string') {
          brokers = brokers.split(',').map(s => s.trim());
        }

        this.kafka = new Kafka({
            clientId: config.client_id,
            brokers: config.brokers ? config.brokers : async () => {
                //Getting brokers from Confluent REST Proxy
                const clusterResponse = await axios(`${config.kafka_rest_base_url}/v3/clusters`, {
                  headers:  {
                    Accept:  'application/vnd.api+json',
                  }
                });

                const clusterUrl = clusterResponse.data[0].links.self;

                const brokersResponse = await axios(`${clusterUrl}/brokers`, {
                  headers: {
                    Accept: 'application/vnd.api+json',
                  }
                });

                const brokers = brokersResponse.data.map((broker: any) => {
                  const { host, port } = broker.attributes;
                  return `${host}:${port}`;
                });

                return brokers;
              },
              logCreator: pinoLogCreator
        });

        this.producer();
    }
}`

**Comment by OneCricketeer** [comment]
You'd need multiple threads, a subprocess, or to close the consumer after a certain number of retries, for the process not to "get stuck"
