### ISSUE TITLE
Connection.disconnect() debug logging breaks Jest tests

### ISSUE THREAD

**Issue by quaos** [tulios/kafkajs#1583]
**Describe the bug**

I'm implementing Kafka connection from within a NestJS app. When running Integration/E2E tests in Jest for Kafka module, the test cases succeeded, but there will be `Cannot log after tests are done.` error from Jest that make the test process eventually failed (with `Command failed with exit code 1`.)

I've checked that the consumers and producers are cleaned up using `await Consumer.disconnect()` and `await Producer.disconnect()` in the `afterAll()` block. But the logging that break tests comes from `Connection.socket.onEnd()` event handler, which somehow get triggered after all disconnect promises are complete.

_Currently I'm applying workaround by setting a flag in Custom Logger to block debug logging after all tests are completed (in `afterAll()` block), but I suppose there should be cleaner way._

**To Reproduce**
Please provide either a link to a:

1. <s>failing test in a KafkaJS fork</s>
2. [repository with an example project reproducing the issue](https://github.com/quaos/test-kafkajs-jest-log)

**Expected behavior**
Jest test process should exit without error.

**Observed behavior**
The Jest test process exited with error:
```
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "[Nest] 8766  - 06/06/2023, 11:46:04 AM   DEBUG [Connection] Object:
    {
      "broker": "localhost:9092",
      "clientId": "test",
      "message": "disconnected",
      "stack": "Error: \n    at /Users/chakrit/Projects/test-kafkajs-jest-log/src/utils/loggers/my-logger.ts:26:19\n    at Array.forEach (<anonymous>)\n    at MyLogger.printMessages (/Users/chakrit/Projects/test-kafkajs-jest-log/src/utils/loggers/my-logger.ts:21:18)\n    at MyLogger.debug (/Users/chakrit/Projects/test-kafkajs-jest-log/node_modules/@nestjs/common/services/console-logger.service.js:72:14)\n    at /Users/chakrit/Projects/test-kafkajs-jest-log/src/providers/kafka/kafka.provider.module.ts:47:53\n    at /Users/chakrit/Projects/test-kafkajs-jest-log/node_modules/kafkajs/src/loggers/index.js:16:3\n    at Connection.logDebug (/Users/chakrit/Projects/test-kafkajs-jest-log/node_modules/kafkajs/src/network/connection.js:111:7)\n    at Connection.disconnect (/Users/chakrit/Projects/test-kafkajs-jest-log/node_modules/kafkajs/src/network/connection.js:280:10)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at Socket.onEnd (/Users/chakrit/Projects/test-kafkajs-jest-log/node_modules/kafkajs/src/network/connection.js:204:9)"
    }

    ".

      55 |             )
      56 |
    > 57 |             console.debug(formattedMessage)
         |                     ^
      58 |         })
      59 |     }
      60 | }

      at console.debug (node_modules/@jest/console/build/CustomConsole.js:102:10)
      at src/utils/loggers/my-logger.ts:57:21
          at Array.forEach (<anonymous>)
      at MyLogger.printMessages (src/utils/loggers/my-logger.ts:21:18)
      at src/providers/kafka/kafka.provider.module.ts:66:49

error Command failed with exit code 1.
```

**Environment:**
 - OS: Mac OS X 12.6 (Monterey) 
 - KafkaJS version 2.2.4
 - Kafka version 7.3.0 (Docker image: `confluentinc/cp-kafka:7.3.0`)
 - NestJS version 9.4.2
 - NodeJS version 16.20.0 - 20.2.0
 - Typescript version 4.9.5

**Additional context**
* Ref.: https://github.com/tulios/kafkajs/issues/1367

**Comment by Compaurum** [comment]
+1

**Comment by egor11223** [comment]
+1
