### ISSUE TITLE
Failed to find group coordinator

### ISSUE THREAD

**Issue by dasaripravin-developer** [tulios/kafkajs#1630]
**Describe the bug**
I have 3 node consumer group and facing the ***failed to find group coordinator*** ERROR. And consumer get stopped. Can anyone assist me to figure out the this issue. Find the below details for the same.

- Error message which is got in console
{"level":"ERROR","timestamp":"2023-10-06T12:00:50.029Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSGroupCoordinatorNotFound: Failed to find group coordinator","groupId":"NODEKAFKA","stack":"KafkaJSGroupCoordinatorNotFound: Failed to find group coordinator\n    at Cluster.findGroupCoordinatorMetadata"}

**Expected behavior**
The group member should get the group coordinator.

**Observed behavior**
Getting failed to find group coordinator and stopped the consumer

**Environment:**
 - OS: [e.g. Ubuntu 16.x]
 - KafkaJS version [e.g. 2.2.3]
 - Kafka version [e.g. 3.4.1]
 - NodeJS version [e.g. 16.19.0]

**Additional context**
Application running in kubernetes pod.

Please let me know if need more details.

**Comment by saketmv** [comment]
I've seen this happen in new clusters when the `offsets.topic.replication.factor` (default: 3) is less than the actual number of brokers.

**Comment by arupsarkar-sfdc** [comment]
I am getting this error when starting my consumer, producer is working fine and publishing messages. How can I consumer messages. Can someone please help me in resolving it. 

FYI: My topic details of replication and partition is mentioned below
Replication: 3
Partition: 2

**Error Msg 1**
`{"level":"ERROR","timestamp":"2023-12-20T19:16:12.330Z","logger":"kafkajs","message":"[Connection] Response GroupCoordinator(key: 10, version: 2)","broker":"ec2-54-90-120-75.compute-1.amazonaws.com:9096","clientId":"my-app","error":"Not authorized to access group: Group authorization failed","correlationId":0,"size":49}`
**Error Msg 2**
```
{"level":"ERROR","timestamp":"2023-12-20T19:16:12.330Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSGroupCoordinatorNotFound: Failed to find group coordinator","groupId":"my-app","stack":"KafkaJSGroupCoordinatorNotFound: Failed to find group coordinator
    at Cluster.findGroupCoordinatorMetadata (/app/node_modules/kafkajs/src/cluster/index.js:420:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/kafkajs/src/cluster/index.js:346:33
    at async [private:ConsumerGroup:join] (/app/node_modules/kafkajs/src/consumer/consumerGroup.js:167:24)
    at async /app/node_modules/kafkajs/src/consumer/consumerGroup.js:335:9
    at async Runner.start (/app/node_modules/kafkajs/src/consumer/runner.js:84:7)
    at async start (/app/node_modules/kafkajs/src/consumer/index.js:243:7)
    at async Object.run (/app/node_modules/kafkajs/src/consumer/index.js:304:5)
    at async Object.startConsumer (/app/server/kafka-server.js:47:9)
    at async /app/server/app.js:477:5"}
```

**Comment by FUNJABIVRUSH** [comment]
@arupsarkar-sfdc did you find any solution ?

**Comment by florian-besser** [comment]
This issue also happened to me; worst part was that the consumer **did not recover**. Normally KafkaJS will just retry whatever failed and eventually get back to healthy again, but in this case I had to restart the entire app.

**Comment by florian-besser** [comment]
I can add some more details, the issue reappeared. Here are our logs:
```
Jul 3, 2024 @ 14:16:37.355
NS: Connection, label: ERROR, message: Connection error: getaddrinfo ENOTFOUND kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local
```
This is a correct error message; we indeed had a network wobble in our Kafka cluster. KafkaJS detected this correctly, and followed:
```
Jul 3, 2024 @ 14:16:37.367
NS: Consumer, label: ERROR, message: Crash: KafkaJSNumberOfRetriesExceeded: Connection error: getaddrinfo ENOTFOUND kafka-controller-1.kafka-controller-headless.kafka.svc.cluster.local
```
So far so good, KafkaJS tries to recover:
```
Jul 3, 2024 @ 14:16:37.374
NS: Consumer, label: ERROR, message: Restarting the consumer in 10942ms
Jul 3, 2024 @ 14:16:48.322
NS: Consumer, label: INFO, message: Starting
```
So we're seeing a fresh connection attempt, this is as expected. Unfortunately the cluster was still down, so we got:
```
Jul 3, 2024 @ 14:17:11.120
NS: Consumer, label: ERROR, message: Crash: KafkaJSGroupCoordinatorNotFound: Failed to find group coordinator
```

**Expected outcome**:

The consumer stops once more, tries again after a few seconds

**Actual outcome**:

The consumer stops after `KafkaJSGroupCoordinatorNotFound` and does not recover.

From then on the app ran without a consumer (but was reporting healthy) and had to be restarted manually - after a restart KafkaJS was working correctly once more

**Comment by belchior** [comment]
I received this error in a local environment a I fixed setting the IP address of the docker in the docker-compose file.

```yml
environment:
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://DOCKER_IP:29092
```

**Comment by clluiz** [comment]
> I've seen this happen in new clusters when the `offsets.topic.replication.factor` (default: 3) is less than the actual number of brokers.

Thanks for that. But do you know why this happens?

**Comment by EfreetSK** [comment]
@florian-besser We have the exact same problem, did you manage to handle this somehow?

**Comment by florian-besser** [comment]
We "solved" this issue by capturing the `Crash: KafkaJSGroupCoordinatorNotFound` error and killing the app. This forces a restart, which in turn allows us to connect once more.

Note that this fix is **not** a good idea: During this window your app is reporting healthy and accepting traffic, but it cannot connect to Kafka. That yields behavior that most devs were not expecting. Still, it is better than never reconnecting.

For capturing the error we use a custom Kafka logger:
```

export const customKafkaLogger = (_: logLevel) => {
  return ({ namespace, level, label, log }) => {
    const logger = new Logger('Kafka');
    const { message, ...extra } = log;
    switch (level) {
      case logLevel.NOTHING:
        return;
      case logLevel.ERROR:
        logger.error(extra, `NS: ${namespace}, label: ${label}, message: ${message}`);
        if (
          message == 'Crash: KafkaJSGroupCoordinatorNotFound: Failed to find group coordinator' ||
          message == 'Crash: KafkaJSNonRetriableError: Failed to find group coordinator'
        ) {
          // Usually KafkaJS recovers from errors, e.g. by retrying the command or restarting the consumer as a worst case scenario.
          // This error is an exception, see https://github.com/tulios/kafkajs/issues/1630
          // This issue can lead to the application till being able to send Kafka messages, but not receive them. If this happens to all consumers in a consumer group, no messages will be read!
          // This in turn causes issues (ands alerts), so it is best to kill the app when this happens, so that we force a restart which in turn gets the KafkaJS consumers going again.
          logger.fatal(`Received KafkaJSGroupCoordinatorNotFound message which KafkaJS does NOT recover. Terminating!`);
          process.kill(process.pid, ShutdownSignal.SIGTERM);
        }
        return;
      case logLevel.INFO:
      case logLevel.DEBUG:
        logger.log(extra, `NS: ${namespace}, label: ${label}, message: ${message}`);
        return;
      case logLevel.WARN:
        logger.warn(extra, `NS: ${namespace}, label: ${label}, message: ${message}`);
        return;
    }
  };
};
```

**Comment by EfreetSK** [comment]
@florian-besser Thanks! Today I was playing around with this and looking into kafkajs code and maybe I found a solution. How about this:

`consumer.on(consumer.events.CRASH, () => {throw new Error("Kafka consumer crashed")})`

The thing is, you can react on some events that happen and looking here

https://github.com/tulios/kafkajs/blob/55b0b416308b9e597a5a6b97b0a6fd6b846255dc/src/consumer/index.js#L286

the event should be CRASH in that case. So we can react on that.

Our logs also show that this line was also logged
https://github.com/tulios/kafkajs/blob/55b0b416308b9e597a5a6b97b0a6fd6b846255dc/src/consumer/index.js#L122
So maybe the STOP was emitted
https://github.com/tulios/kafkajs/blob/55b0b416308b9e597a5a6b97b0a6fd6b846255dc/src/consumer/index.js#L118
Then if that would be the case, that only STOP was emitted (which I don't expect), then we can still handle this:

```
consumer.on(consumer.events.STOP, () => {
    if(!shutdownCalled) {
        throw new Error("Kafka consumer stopped unexpectedly");
    }
    console.log("Kafka consumer stopped normally")
})
```

The `KafkaJSGroupCoordinatorNotFound` is hard to reproduce so I wasn't able to confirm that it actually emitts CRASH and play around with it. But what you can easily play around with is the STOP event. From my testing, reacting on STOP event worked great and I was able to throw exception out (and crash the application which is the goal).

Anyway, this still needs to be confirmed that it actually works but looks promising in my opinion
