### ISSUE TITLE
Kraft Mode : The Kafka server does not support the requested API version

### ISSUE THREAD

**Issue by khannedy** [tulios/kafkajs#1651]
**Describe the bug**
When using Kafka 3.6.1 Kraft Mode, KafkaJS Producer can not send message

**To Reproduce**

```json
{
  "name": "belajar-nodejs-kafka",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "type": "module",
  "dependencies": {
    "kafkajs": "^2.2.4"
  }
}

```

```javascript
import {Kafka, Partitioners} from "kafkajs";

const kafka = new Kafka({
    brokers: ["localhost:9093"]
})

const producer = kafka.producer({
    createPartitioner: Partitioners.DefaultPartitioner
});
await producer.connect();

for (let i = 0; i < 10; i++) {
    await producer.send({
        topic: "helloworld",
        messages: [
            {
                "value": `Hello ${i}`
            }
        ]
    })
}

await producer.disconnect();

```

```log
/Users/khannedy/.nvm/versions/node/v18.17.1/bin/node /Users/khannedy/Developments/NODEJS/belajar-nodejs-kafka/producer.js
/Users/khannedy/Developments/NODEJS/belajar-nodejs-kafka/node_modules/kafkajs/src/retry/index.js:55
          reject(new KafkaJSNonRetriableError(e, { cause: e.cause || e }))
                 ^

KafkaJSNonRetriableError: The Kafka server does not support the requested API version
    at /Users/khannedy/Developments/NODEJS/belajar-nodejs-kafka/node_modules/kafkajs/src/retry/index.js:55:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  retriable: false,
  helpUrl: undefined,
  [cause]: KafkaJSServerDoesNotSupportApiKey: The Kafka server does not support the requested API version
      at Broker.lookupRequest (/Users/khannedy/Developments/NODEJS/belajar-nodejs-kafka/node_modules/kafkajs/src/protocol/requests/index.js:93:11)
      at Broker.metadata (/Users/khannedy/Developments/NODEJS/belajar-nodejs-kafka/node_modules/kafkajs/src/broker/index.js:175:27)
      at /Users/khannedy/Developments/NODEJS/belajar-nodejs-kafka/node_modules/kafkajs/src/cluster/brokerPool.js:158:38
      at retry (/Users/khannedy/Developments/NODEJS/belajar-nodejs-kafka/node_modules/kafkajs/src/retry/index.js:43:5)
      at /Users/khannedy/Developments/NODEJS/belajar-nodejs-kafka/node_modules/kafkajs/src/retry/index.js:75:5
      at new Promise (<anonymous>)
      at BrokerPool.retrier (/Users/khannedy/Developments/NODEJS/belajar-nodejs-kafka/node_modules/kafkajs/src/retry/index.js:72:10)
      at BrokerPool.refreshMetadata (/Users/khannedy/Developments/NODEJS/belajar-nodejs-kafka/node_modules/kafkajs/src/cluster/brokerPool.js:156:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /Users/khannedy/Developments/NODEJS/belajar-nodejs-kafka/node_modules/kafkajs/src/cluster/index.js:111:14 {
    retriable: false,
    helpUrl: undefined,
    apiKey: 3,
    apiName: 'Metadata',
    [cause]: undefined
  }
}

Node.js v18.17.1

Process finished with exit code 1
```

**Environment:**
 - OS: MacOS
 - KafkaJS version ^2.2.4
 - Kafka version 3.6.1
 - Node.js v18.17.1

**Comment by khannedy** [comment]
wrong kafka broker port
