### ISSUE TITLE
Confusing error messaging when the key of the message isn't string

### ISSUE THREAD

**Issue by zhangchiqing** [tulios/kafkajs#281]
I was publishing a message like this:
```js
const { Kafka } = require('kafkajs');
const kafka = new Kafka({
  clientId: 'my-app',
  brokers: ['localhost:9092']
});

const publish = async producer => {
  const d = { id: 100 };
  return producer.send({
    topic: 'data',
    messages: [{ key: d.id, value: JSON.stringify(d) }]
  });
};

const run = async () => {
  const producer = kafka.producer();
  await producer.connect();
  const published = await publish(producer);
  console.log(published);
};

run();
```

I expect to see logs showing it's published, but actually I got the following error:
```
▸ node kafka.js
{"level":"ERROR","timestamp":"2019-02-13T15:53:30.372Z","logger":"kafkajs","message":"[Producer] \"value\" argument must not be a number","retryCount":0,"retryTime":357}
(node:29079) UnhandledPromiseRejectionWarning: TypeError: "value" argument must not be a number
    at Function.Buffer.from (buffer.js:186:11)
    at module.exports.string (/Users/leo/zhangchiqing/kafkajs/node_modules/kafkajs/src/producer/partitioners/default/murmur2.js:14:23)
    at /Users/leo/zhangchiqing/kafkajs/node_modules/kafkajs/src/producer/partitioners/default/index.js:34:25
    at messages.reduce (/Users/leo/zhangchiqing/kafkajs/node_modules/kafkajs/src/producer/groupMessagesPerPartition.js:7:23)
    at Array.reduce (<anonymous>)
    at module.exports (/Users/leo/zhangchiqing/kafkajs/node_modules/kafkajs/src/producer/groupMessagesPerPartition.js:6:19)
    at createProducerRequests (/Users/leo/zhangchiqing/kafkajs/node_modules/kafkajs/src/producer/sendMessages.js:42:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:29079) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29079) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

However, this change below fixes it, I just need to convert the `key` from a number into a string. 
```diff
-    messages: [{ key: d.id, value: JSON.stringify(d) }]
+    messages: [{ key: `${d.id}`, value: JSON.stringify(d) }]
```

The problem is that the error message was confusing. It seems like the `value` field was a number, but actually, it's the `key` field was number.

Environment: 
Node: v8.11.4
Version: kafkajs@1.4.7

**Comment by Nevon** [comment]
`key` has to be something that is convertible to a Buffer, which number is not, but I agree that we could catch this earlier and provide a better error message.

**Comment by tulios** [comment]
We should add proper validation for `key` and `value`; they should only accept values that can be converted to a `Buffer`. Thanks for the report.
