### ISSUE TITLE
Unable to build Producer crypto.getRandomValues is not a function

### ISSUE THREAD

**Issue by jkerivan** [tulios/kafkajs#489]
When following the Getting Started section I am getting the following error and I am not sure why?  I have tried both node v10.16.0 and node 8.  

Error occurred:  TypeError: crypto.getRandomValues is not a function
    at Object.randomBytes (/Users/me/workspace/test-project/node_modules/kafkajs/src/producer/partitioners/default/randomBytes.js:4:31)
    at module.exports.size (/Users/me/workspace/test-project/node_modules/kafkajs/src/producer/partitioners/default/randomBytes.js:29:31)
    at /Users/me/workspace/test-project/node_modules/kafkajs/src/producer/partitioners/default/partitioner.js:21:17
    at module.exports (/Users/me/workspace/test-project/node_modules/kafkajs/src/producer/index.js:41:23)
    at Client.producer (/Users/me/workspace/test-project/node_modules/kafkajs/src/index.js:91:12)
    at Object.postMessagesToQueue (/Users/me/workspace/test-project/src/services/kafka_service.js:14:38)
    at Object.exports.handler (/Users/me/workspace/test-project/src/cso_runner.js:13:24)
    at [eval]:1:29
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)

**Comment by Nevon** [comment]
Are you perhaps running in the Node REPL? If so, this was fixed in #462. You can try running the pre-release version `1.11.0-beta.10` to see if that fixes it.

**Comment by jkerivan** [comment]
That was it thank you for your help
