### ISSUE TITLE
Kafka client reconnection failed

### ISSUE THREAD

**Issue by OlegPoberegets** [tulios/kafkajs#501]
Hello!!!

We had a problem with consumer reconnection after a network shutdown.
We use `"kafkajs": "^1.10.0"` with consumer configuration:
```json
{
    "sessionTimeout": 10000,
    "heartbeatInterval": 1000,
    "minBytes": 1,
    "maxWaitTimeInMs": 5000,
    "retry": {
        "retries": 100,
        "initialRetryTime": 500,
        "maxRetryTime": 2000
    }
}
```

We have a listener for CRASH event and a reconnection logic.
```js
this._vssMessageConsumer.on(this._vssMessageConsumer.events.CRASH, async ({payload}) => {
    this._logger.error(`[Kafka Consumer] Consumer "${payload.groupId}" crashed`, payload.error);
    try {
        await this._vssMessageConsumer.disconnect();
        await this._vssMessageConsumer.connect();
    } catch (err) {
        this._logger.error(`[Kafka Consumer] [Restart] ${err.message}`, err);
        /*
            The consumer will restart only if the name of the error is 'KafkaJSNumberOfRetriesExceeded' or error is a retryable.
            See https://github.com/tulios/kafkajs/blob/master/src/consumer/index.js#L257
        */
        if (err.name !== 'KafkaJSNumberOfRetriesExceeded' && err.retriable !== true) {
           // Start message processing 
        }
    }
});
```

And we have wrapped internal KafkaJS logs, but only WARN level:
```
[2019-09-16T01:42:28.180Z][WARN] [Kafkajs]: [RequestQueue] Response without match. Meta: '{"clientId":"my-client-02","broker":"my-broker-3:9092","correlationId":1140100}'
[2019-09-16T01:42:27.311Z][ERROR] [Kafkajs]: [Connection] Connection error: read ECONNRESET. Meta: '{"message":"[Connection] Connection error: read ECONNRESET","extra":{"broker":"my-broker-3:9092","clientId":"my-client-02","stack":"Error: read ECONNRESET\\n    at TCP.onread (net.js:622:25)"},"name":"ExtendableError"}'
[2019-09-16T01:42:05.297Z][ERROR] [Kafkajs]: [Connection] Connection error: connect ETIMEDOUT 10.2.0.192:9092. Meta: '{"message":"[Connection] Connection error: connect ETIMEDOUT 10.2.0.192:9092","extra":{"broker":"my-broker-1:9092","clientId":"my-client-02","stack":"Error: connect ETIMEDOUT 10.2.0.192:9092\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)"}}'
[2019-09-16T01:42:03.295Z][ERROR] [Kafkajs]: [Connection] Connection error: connect ETIMEDOUT 10.2.0.194:9092. Meta: '{"message":"[Connection] Connection error: connect ETIMEDOUT 10.2.0.194:9092","extra":{"broker":"my-broker-3:9092","clientId":"my-client-02","stack":"Error: connect ETIMEDOUT 10.2.0.194:9092\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)"}}'
[2019-09-16T01:42:00.291Z][ERROR] [Kafkajs]: [Connection] Connection error: connect ETIMEDOUT 10.2.0.194:9092. Meta: '{"message":"[Connection] Connection error: connect ETIMEDOUT 10.2.0.194:9092","extra":{"broker":"my-broker-3:9092","clientId":"my-client-02","stack":"Error: connect ETIMEDOUT 10.2.0.194:9092\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)"}}'
[2019-09-16T01:41:57.289Z][ERROR] [Kafkajs]: [Connection] Connection error: connect ETIMEDOUT 10.2.0.192:9092. Meta: '{"message":"[Connection] Connection error: connect ETIMEDOUT 10.2.0.192:9092","extra":{"broker":"my-broker-1:9092","clientId":"my-client-02","stack":"Error: connect ETIMEDOUT 10.2.0.192:9092\\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)"}}'
```

After `[RequestQueue] Response without match` we didn`t receive any logs from client and any events.

Can you help?

**Comment by Nevon** [comment]
You should not be changing the connection state from within the crash event handler. We already take care of restarting the consumer in the event of a crash. The crash handler is only for doing things like logging or other cleanup work that you need to do.

**Comment by OlegPoberegets** [comment]
Yes, but I had a few cases when a restart wasn't running.
Then I find this line https://github.com/tulios/kafkajs/blob/master/src/consumer/index.js#L257

**Comment by tulios** [comment]
@OlegPoberegets can you share one of these cases? Because if the error is not retriable, there is nothing KafkaJS can do to recover, it has to bubble up to userland. KafkaJS already cover all the cases for non-retriable but within the consumer life-cycle.

**Comment by OlegPoberegets** [comment]
@tulios sorry, but logs with a non-retriable error was lost. 
I remember that it was an error in lock.js. But I don`t 100% sure

I found a bug in my restart method because do `await this._vssMessageConsumer.connect();` after 
`await this._vssMessageConsumer.disconnect();` is not enough

**Comment by tulios** [comment]
@OlegPoberegets any news on this?

**Comment by OlegPoberegets** [comment]
No((
I will close issue
