### ISSUE TITLE
How to get standard console logs

### ISSUE THREAD

**Issue by Awatatah** [tulios/kafkajs#513]
HI, currently we are getting logs in JSON format like so:

> {"level":"error","message":"Error when calling eachMessage","extra":{"timestamp":"2019-10-01T19:12:59.159Z","logger":"kafkajs","topic":"brazos-XXXXXX.xxx-xx","partition":0,"offset":"4098","stack":"SyntaxError: Unexpected token t in JSON at position 1\n...

How can we get standard console outputs, e.g.

> /.../src/server.ts:63
throw Error('this is just a test');
      ^
Error: this is just a test
    at Object.<anonymous> (/.../src/server.ts:63:7)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Module.m._compile (/.../node_modules/ts-node/src/index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Object.require.extensions.<computed> [as .ts] (/..../node_modules/ts-node/src/index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    ...

**Comment by tulios** [comment]
Hi, you can replace the default logger. Take a look at this:

https://kafka.js.org/docs/custom-logger

You have some examples in the website, pasting a simple one here:

```js
const MyLogCreator = logLevel => ({ namespace, level, label, log }) => {
  const { timestamp, logger, message, ...others } = log
  console.log(`${label} [${namespace}] ${message}`, others)
}
```
