### ISSUE TITLE
NOT_LEADER_FOR_PARTITION error when connecting over TLS with Strimzi (Apache Kafka on OpenShift)

### ISSUE THREAD

**Issue by chainhead** [tulios/kafkajs#518]
# Problem
Producer or consumer clients using `kafkajs` cannot connect with [Strimzi](https://strimzi.io/quickstarts/okd/) over TLS.

# Reproduction
The steps to reproduce this error are listed as follows.

## Install Strimzi on an OpenShift cluster
- Follow instructions to install [here](https://strimzi.io/quickstarts/okd/) upto **Applying Strimzi installation file**.
- To set-up access for external clients, do the following:
 - `wget https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.14.0/examples/kafka/kafka-ephemeral.yaml`
- Edit `kafka-ephemeral.yaml` to add an `external` listener with type set to `route`. See example below.
- Apply the `kafka-ephemeral.yaml` with `oc apply -f kafka-ephemeral.yaml -n myproject`
- Wait for completion: `oc wait kafka/my-cluster --for=condition=Ready --timeout=300s -n myproject`

`kafka-ephemeral.yaml`

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.3.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: route
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

## Get Kafka end-point
- Get host name: `oc get routes myproject-kafka-bootstrap -o=jsonpath='{.status.ingress[0].host}{"\n"}'`
- Get secret: `oc extract secret/myproject-cluster-ca-cert --keys=ca.crt --to=- > ca.crt`

### Producer

```js
const fs = require('fs')
const { Kafka } = require('kafkajs')
 
const kafka = new Kafka({
  clientId: 'demo-pub',
  brokers: ['host-name-from-previous-step:443'],
  ssl : {
  	servername: 'host-name-from-previous-step',
    rejectUnauthorized: false,
    ca : [fs.readFileSync('ca.crt', 'utf-8')],
    secureProtocol: 'TLSv1_2_method'
  }
})
 
const producer = kafka.producer()
const run = async() => {
	await producer.connect()
	//
	await producer.send({
	    topic: 'test-topic',
	    messages: [
	      { value: 'Hello KafkaJS user!' },
	    ],
	  })
}

run().catch(console.error)
```

### Consumer

```js
const fs = require('fs')
const { Kafka, logLevel } = require('kafkajs')
 
const kafka = new Kafka({
  clientId: 'demo-sub',
  brokers: ['host-name-from-previous-step:443'],
  ssl : {
  	servername: 'host-name-from-previous-step',
    rejectUnauthorized: false,
    ca : [fs.readFileSync('ca.crt', 'utf-8')],
    secureProtocol: 'TLSv1_2_method'
  }
})
 
const consumer = kafka.consumer({ groupId: 'test-group' })
const run = async() => {
	await consumer.connect()
  	await consumer.subscribe({ topic: 'test-topic', fromBeginning: true })
  	//
	await consumer.run({
	    eachMessage: async ({ topic, partition, message }) => {
	      console.log({
	        partition,
	        offset: message.offset,
	        value: message.value.toString(),
	      })
	    },
	  })
}

run().catch(console.error)
```

### Producer

```bash
{ KafkaJSNumberOfRetriesExceeded
  Caused by: KafkaJSProtocolError: This server is not the leader for that topic-partition
    at createErrorFromCode (/Users/champ/noflo/node-tests/node_modules/kafkajs/src/protocol/error.js:536:10)
    at Object.parse (/Users/champ/noflo/node-tests/node_modules/kafkajs/src/protocol/requests/produce/v3/response.js:47:11)
    at Connection.send (/Users/champ/noflo/node-tests/node_modules/kafkajs/src/network/connection.js:306:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'KafkaJSNumberOfRetriesExceeded',
  retriable: false,
  helpUrl: undefined,
  originalError:
   { KafkaJSProtocolError: This server is not the leader for that topic-partition
       at createErrorFromCode (/Users/champ/noflo/node-tests/node_modules/kafkajs/src/protocol/error.js:536:10)
       at Object.parse (/Users/champ/noflo/node-tests/node_modules/kafkajs/src/protocol/requests/produce/v3/response.js:47:11)
       at Connection.send (/Users/champ/noflo/node-tests/node_modules/kafkajs/src/network/connection.js:306:35)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'KafkaJSProtocolError',
     retriable: true,
     helpUrl: undefined,
     type: 'NOT_LEADER_FOR_PARTITION',
     code: 6 },
  retryCount: 5,
  retryTime: 9468 }
```

### Consumer

```bash
{"level":"INFO","timestamp":"2019-10-07T13:31:31.839Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"test-group"}
{"level":"ERROR","timestamp":"2019-10-07T13:31:32.127Z","logger":"kafkajs","message":"[Connection] Response JoinGroup(key: 11, version: 2)","broker":"messaging-kafka-2-messaging.192.168.99.100.nip.io:443","clientId":"demo-sub","error":"This is not the correct coordinator for this group","correlationId":0,"size":24}
{"level":"ERROR","timestamp":"2019-10-07T13:31:33.125Z","logger":"kafkajs","message":"[Connection] Response JoinGroup(key: 11, version: 2)","broker":"messaging-kafka-2-messaging.192.168.99.100.nip.io:443","clientId":"demo-sub","error":"This is not the correct coordinator for this group","correlationId":1,"size":24}
{"level":"ERROR","timestamp":"2019-10-07T13:31:33.597Z","logger":"kafkajs","message":"[Connection] Response JoinGroup(key: 11, version: 2)","broker":"messaging-kafka-2-messaging.192.168.99.100.nip.io:443","clientId":"demo-sub","error":"This is not the correct coordinator for this group","correlationId":2,"size":24}
{"level":"ERROR","timestamp":"2019-10-07T13:31:34.490Z","logger":"kafkajs","message":"[Connection] Response JoinGroup(key: 11, version: 2)","broker":"messaging-kafka-2-messaging.192.168.99.100.nip.io:443","clientId":"demo-sub","error":"This is not the correct coordinator for this group","correlationId":3,"size":24}
{"level":"ERROR","timestamp":"2019-10-07T13:31:36.438Z","logger":"kafkajs","message":"[Connection] Response JoinGroup(key: 11, version: 2)","broker":"messaging-kafka-2-messaging.192.168.99.100.nip.io:443","clientId":"demo-sub","error":"This is not the correct coordinator for this group","correlationId":4,"size":24}
{"level":"ERROR","timestamp":"2019-10-07T13:31:39.851Z","logger":"kafkajs","message":"[Connection] Response JoinGroup(key: 11, version: 2)","broker":"messaging-kafka-2-messaging.192.168.99.100.nip.io:443","clientId":"demo-sub","error":"This is not the correct coordinator for this group","correlationId":6,"size":24}
{"level":"ERROR","timestamp":"2019-10-07T13:31:39.852Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNumberOfRetriesExceeded: The group is rebalancing","groupId":"test-group","retryCount":5,"stack":"KafkaJSNumberOfRetriesExceeded\n  Caused by: KafkaJSError: The group is rebalancing\n    at retrier (/Users/champ/noflo/node-tests/node_modules/kafkajs/src/consumer/runner.js:76:17)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"level":"INFO","timestamp":"2019-10-07T13:31:39.853Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"test-group"}
```

## Note
The cluster responds correctly to the Kafka [console clients](https://kafka.apache.org/quickstart) even when connecting with TLS.

**Comment by chainhead** [comment]
Another observation I made is as follows.

1. Set-up subscription with the Kafka console client for a topic e.g. `mytopic`.
2. Publish a message with `kafkajs` based producer client to a topic e.g. `mytopic`.
3. Works.

The other way round i.e. consumer with `kafkajs` and producer with console client does not work.

**Comment by tulios** [comment]
Do you have different hostnames for each broker? (`messaging-kafka-2-messaging.192.168.99.100.nip.io`)

**Comment by tulios** [comment]
@chainhead can you try the pre-release version `1.12.0-beta.1`?

**Comment by alkhachatryan** [comment]
I found out that the problem is with logs folder (where meta.properties is stored)
So before I launch zookeeper then kafka, I fully empty logs folder. To have everything in one place I just have one bash script

`#!/bin/bash

rm -rf /home/kafka/logs
mkdir /home/kafka/logs
sudo systemctl start zookeeper
sudo systemctl start kafka
`

**Comment by vinimoret** [comment]
Facing the same Issue with strimzi
