### ISSUE TITLE
I'm getting `ETIMEDOUT` and `authentication failed` on the 2nd topic only. How can I better troubleshoot this?

### ISSUE THREAD

**Issue by sean256** [tulios/kafkajs#523]
I'm having an issue subscribing a consumer to multiple topics. Usually the first topic or 2 will succeed nearly instantly, then it hits a wall. It will hang for several minutes then output 3 error messages. If I continue waiting it will throw the same 3 error messages.

I'm having a hard time figuring out if this is an issue on my end, kafkajs, or my company's Kafka instances. I'm leaning towards the client side of things since other teams here consume happily with Java connectors.

> NOTE: I redacted various things in code and the logs

Code:
```js
(async () => {
	const topics = ['topic-a', 'topic-b', 'topic-c'];

	const kafka = new Kafka({
		clientId: 'some-client-id',
		brokers: ['some-broker.redacted.com:9093'],
		sasl: {/* REDACTED */},
	});

	const consumer = kafka.consumer({ groupId: 'some-group-id' });

	for (let topic of topics) {
		console.log(`Sub to ${topic}...`);
		await consumer.subscribe({ topic }); // hangs forever on the second or 3rd topic
		console.log('...done');
	}

	// ... code for consumer.run below. It never makes it this far.
})();
```

Most of the time I get output like this:

```
Sub to topic-a...
...done
Sub to topic-b...
(Hangs here for several minutes...)
{"level":"ERROR","timestamp":"2019-10-14T21:25:12.210Z","logger":"kafkajs","message":"[Connection] Connection error: read ETIMEDOUT","broker":"some-broker-a.redacted.com:9093","clientId":"some-client-id","stack":"Error: read ETIMEDOUT\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)"}
{"level":"ERROR","timestamp":"2019-10-14T21:25:12.212Z","logger":"kafkajs","message":"[SCRAM512Authenticator] SASL SCRAM SHA512 authentication failed: Connection error: read ETIMEDOUT","broker":"some-broker-a.redacted.com:9093"}
{"level":"ERROR","timestamp":"2019-10-14T21:25:12.212Z","logger":"kafkajs","message":"[BrokerPool] KafkaJSSASLAuthenticationError: SASL SCRAM SHA512 authentication failed: Connection error: read ETIMEDOUT","retryCount":0,"retryTime":294,"stack":"KafkaJSSASLAuthenticationError: SASL SCRAM SHA512 authentication failed: Connection error: read ETIMEDOUT\n    at SCRAM512Authenticator.authenticate (/path-to-project/node_modules/kafkajs/src/broker/saslAuthenticator/scram.js:157:21)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
```

If I let it sit it will eventually throw the same 3 error messages.

**Comment by JaapRood** [comment]
Hmm, seems like a networking issue 🤔. It can't make a connection to one of the Brokers inside the Kafka Cluster. Seeing this only for a single topic while the rest works is totally plausible, as the partitions of certain topics are spread throughout the various brokers in the cluster. That's not to say it's not some other kind of issue, though, like over saturating I/O. Your use case of subscribing to multiple topics with a single consumer is also very standard practice.

In the error it mentions the broker it can't connect to `"broker":"some-broker-a.redacted.com:9093"`. When you run multiple times, is it always the same broker that the connection times out for?

**Comment by sean256** [comment]
> When you run multiple times, is it always the same broker that the connection times out for?

So far yes. I am also now running into issues where it may subscribe then timeout / start throwing errors after `consumer.run`

Are there any options for more details logs?
Does the retry option in `kafka.consumer` apply to `.subscribe` as well? It's hard to tell if tweaking that is making any difference.

**Comment by JaapRood** [comment]
The retry options passed to the consumer are used throughout the subscription process. It might be worth knowing that `consumer.run` is actually the thing that triggers the joining of the consumer group. `consumer.subscribe` is basically just a configuration method, so I wouldn't expect any network errors from there.

There's a bunch of instrumentation events you can listen for: https://kafka.js.org/docs/instrumentation-events#a-name-consumer-a-consumer. The events about requests & connection would definitely be helpful in further figuring out what's going on, perhaps also `GROUP_JOIN` and the fetch events.

If it's always the same broker to which you see network time-outs, can you find any indications that other connections to that broker are being made successfully? Perhaps the instrumentation events can help with that!

**Comment by sean256** [comment]
@JaapRood 
> `consumer.subscribe` is basically just a configuration method, so I wouldn't expect any network errors from there.

I am getting the network errors between `consumer.subscribe` calls so this can't be right. It's also an async method, which implies it's doing some sort of IO.

**Comment by JaapRood** [comment]
> I am getting the network errors between consumer.subscribe calls so this can't be right. It's also an async method, which implies it's doing some sort of IO.

Sanity checking myself, we're both right, and your comment actually helps narrow things down 😅.

`consumer.subscribe` doesn't trigger actually joining (subscribing) the consumer group, `consumer.run` does that. However, it _does_ attempt to refresh the metadata for said topic, for which it needs to a connection to the appropriate broker.

I suspect one of the brokers is just unreachable. `consumer.connect` only waits for a connection to a single broker in the cluster, not all of them. However, `consumer.subscribe` to a topic for which this unreachable broker is the leader would _not_ complete until said connection is made or times out.

Is there some way you can verify the networking irrespective of KafkaJS, like using something like [kafkacat](https://github.com/edenhill/kafkacat) to consume some messages in the same way?

**Comment by sean256** [comment]
> Is there some way you can verify the networking irrespective of KafkaJS, like using something like kafkacat to consume some messages in the same way?

I should have mentioned this earlier, but yes, `kafkacat` always works.

> ...and your example is using port `9093`, which usually only accepts SSL connections but no SASL.

I will look into this. My company documentation says to use `9093` with SASL, maybe they are mistaken. If this was the problem, wouldn't it NEVER work? I see now that I wasn't super clear on this, but it *usually* fails but does occasionally work.

**Comment by JaapRood** [comment]
> If this was the problem, wouldn't it NEVER work? I see now that I wasn't super clear on this, but it usually fails but does occasionally work.

A broker known to the client is *randomly* selected to request the metadata for the specific topic. If that broker also doesn't hold the partitions you're trying to access, it's conceivable how that particular broker just isn't used.
