### ISSUE TITLE
fetchTopicMetadata generates Cannot read property 'topicMetadata' of null

### ISSUE THREAD

**Issue by lafeuil** [tulios/kafkajs#549]
When I call twice the `fetchTopicMetadata` function of admin client, I get the following error : 
```
TypeError: Cannot read property 'topicMetadata' of null
    at Object.fetchTopicMetadata (/home/user/kafkajs-test/node_modules/kafkajs/src/admin/index.js:591:24)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async /home/user/kafkajs-test/admin.js:22:5
```

To have this error, the first call of `fetchTopicMetadata` must be on an existed topic and the second call on a non-existent topic. 

To reproduce : 

```javascript
const { Kafka } = require("kafkajs");
const kafka = new Kafka({
  clientId: "kafkajs-test.admin",
  brokers: ["kafka-1:9092", "kafka-2:9092", "kafka-3:9092"]
});
const admin = kafka.admin();
(async () => {
  await admin.connect();
  try {
      await admin.fetchTopicMetadata({
        topics: ["topic1"] // topic1 exists => no error
      });
  } catch (e) {
    console.error("topic1 error", e);
  }

  try {
    await admin.fetchTopicMetadata({
      topics: ["topic2"] // topic2 does not exist => Cannot read property 'topicMetadata' of null 
    });
  } catch (e) {
    console.error("topic2 error", e);
  }
  await admin.disconnect();
})();
```
Normally, the `fetchTopicMetadata` function generates a KafkaJSProtocolError error with type `UNKNOWN_TOPIC_OR_PARTITION` if topic does not exist.

**Comment by lafeuil** [comment]
The issue is due to this silent try/catch in `withBroker` function : 
https://github.com/tulios/kafkajs/blob/v1.11.0/src/cluster/brokerPool.js#L229
```javascript
  for (const nodeId of brokers) {
      const broker = await this.findBroker({ nodeId })
      try {
        return await callback({ nodeId, broker })
      } catch (e) {} // catch UNKNOWN_TOPIC_OR_PARTITION HERE
    }

    return null // and so return null
```

**Comment by lafeuil** [comment]
I think the problem is in the `refreshMetadataIfNecessary` function. If I force the refresh like this by checking if the requested topics are in the cache, it works !
```patch
diff --git a/src/cluster/brokerPool.js b/src/cluster/brokerPool.js
index 2264ea6..ef9eb42 100644
--- a/src/cluster/brokerPool.js
+++ b/src/cluster/brokerPool.js
@@ -188,7 +188,12 @@ module.exports = class BrokerPool {
    */
   async refreshMetadataIfNecessary(topics) {
     const shouldRefresh =
-      this.metadata == null || this.metadataExpireAt == null || Date.now() > this.metadataExpireAt
+      this.metadata == null ||
+      this.metadataExpireAt == null ||
+      Date.now() > this.metadataExpireAt ||
+      !topics.every(topic =>
+        this.metadata.topicMetadata.some(topicMetadata => topicMetadata.topic === topic)
+      )
 
     if (shouldRefresh) {
       return this.refreshMetadata(topics)
```
