### ISSUE TITLE
RangeError in consumer group syncGroup response processing for member without assignment

### ISSUE THREAD

**Issue by ankon** [tulios/kafkajs#550]
~~~~
 Crash: KafkaJSNumberOfRetriesExceeded: Attempt to access memory outside buffer bounds ({"groupId":"XXXX","retryCount":0,"stack":"KafkaJSNumberOfRetriesExceeded
  Caused by: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:70:11)
    at Buffer.readInt16BE (internal/buffer.js:492:5)
    at Decoder.readInt16 (/app/node_modules/kafkajs/src/protocol/decoder.js:36:31)
    at Object.decode (/app/node_modules/kafkajs/src/consumer/assignerProtocol.js:71:24)
    at ConsumerGroup.sync (/app/node_modules/kafkajs/src/consumer/consumerGroup.js:160:48)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /app/node_modules/kafkajs/src/consumer/runner.js:52:9
    at /app/node_modules/kafkajs/src/consumer/runner.js:354:11"})
~~~~

From my logs it seems that at that point this member didn't receive an assignment, so this piece of code fails:
https://github.com/tulios/kafkajs/blob/34824cbcb2d9721441518ad6875e48f604fd3864/src/consumer/assignerProtocol.js#L71

I think there needs to be a check in any of these places, I'm just not sure which one:
1. Check in ConsumerGroup.sync whether the memberAssignment is empty
2. Check in MemberAssignment.decode whether the given buffer is empty

**Comment by ankon** [comment]
FWIW, The reason I'm getting this now is that I changed my assigner to no longer pre-fill the assignments:
https://github.com/tulios/kafkajs/blob/34824cbcb2d9721441518ad6875e48f604fd3864/src/consumer/assigners/roundRobinAssigner/index.js#L41-L43
