### ISSUE TITLE
Rebalance breaks running consumers

### ISSUE THREAD

**Issue by asiborro** [tulios/kafkajs#558]
Hello everyone,

We have a service consuming 2 topics with 32 partitions each. When a rebalance happens in the group we get the following error:

```
Crash: KafkaJSNumberOfRetriesExceeded: Cannot read property '0' of undefined
```
```
stack: KafkaJSNumberOfRetriesExceeded
  Caused by: TypeError: Cannot read property '0' of undefined
    at /opt/app/services/sc-portal-search-consumer/node_modules/kafkajs/src/consumer/offsetManager/index.js:219:50
    at Array.filter (<anonymous>)
    at topicsWithPartitionsToCommit.topics.map.topic (/opt/app/services/sc-portal-search-consumer/node_modules/kafkajs/src/consumer/offsetManager/index.js:230:12)
    at Array.map (<anonymous>)
    at OffsetManager.uncommittedOffsets (/opt/app/services/sc-portal-search-consumer/node_modules/kafkajs/src/consumer/offsetManager/index.js:226:8)
    at OffsetManager.commitOffsets (/opt/app/services/sc-portal-search-consumer/node_modules/kafkajs/src/consumer/offsetManager/index.js:239:27)
    at ConsumerGroup.commitOffsets (/opt/app/services/sc-portal-search-consumer/node_modules/kafkajs/src/consumer/consumerGroup.js:290:30)
    at Runner.autoCommitOffsets (/opt/app/services/sc-portal-search-consumer/node_modules/kafkajs/src/consumer/runner.js:380:33)
    at Runner.processEachBatch (/opt/app/services/sc-portal-search-consumer/node_modules/kafkajs/src/consumer/runner.js:221:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The consumer is configured to run 2 concurrent batches.
Thanks

**Comment by tulios** [comment]
I think this is related to #555; I am currently investigating the issue

**Comment by songpr** [comment]
@tulios as commented in #555 the #582 do not fix issue in #555 and this bug.

**Comment by ankon** [comment]
This looks similar to the issue we saw in #775.

**Comment by williamoliveira** [comment]
no fix yet?

**Comment by jiho-kr** [comment]
Is it progressing?

**Comment by woderchen** [comment]
resolve this bug?
