### ISSUE TITLE
LZ4 compression not implemented : Kafkajs Node Implementation

### ISSUE THREAD

**Issue by ankyjk** [tulios/kafkajs#597]
Getting Following error while consuming messages using kafkajs library in nodejs.
How to solve this error?

```
"error":"LZ4 compression not implemented","correlationId":4,"size":9208}
{"level":"ERROR","timestamp":"2019-12-13T11:29:15.595Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNotImplemented: LZ4 compression not implemented","groupId":"test-group","stack":"KafkaJSNotImplemented: LZ4 compression not implemented\n    at 3 (*****/node_modules/kafkajs/src/protocol/message/compression/index.js:20:11)\n    at lookupCodecByRecordBatchAttributes (*****/node_modules/kafkajs/src/protocol/message/compression/index.js:34:18)\n    at module.exports (*****/node_modules/kafkajs/src/protocol/recordBatch/v0/decoder.js:61:17)\n    at decodeMessages (*****/node_modules/kafkajs/src/protocol/requests/fetch/v4/decodeMessages.js:27:35)\n    at decodePartition (*****/node_modules/kafkajs/src/protocol/requests/fetch/v7/response.js:37:19)\n    at Decoder.readArrayAsync (*****/node_modules/kafkajs/src/protocol/decoder.js:164:24)\n    at decodeResponse (*****/node_modules/kafkajs/src/protocol/requests/fetch/v7/response.js:42:29)\n    at Decoder.readArrayAsync (*****/node_modules/kafkajs/src/protocol/decoder.js:164:24)\n    at Object.decode (*****/node_modules/kafkajs/src/protocol/requests/fetch/v7/response.js:50:35)\n    at Connection.send (*****/node_modules/kafkajs/src/network/connection.js:305:45)"}
{"level":"ERROR","timestamp":"2019-12-13T11:29:15.624Z","logger":"kafkajs","message":"[Connection] Response Fetch(key: 1, version: 7)","broker":"172.20.18.57:9092","clientId":"my-app","error":"LZ4 compression not implemented","correlationId":6,"size":722}
{"level":"INFO","timestamp":"2019-12-13T11:29:15.697Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"test-group"}
```

**Comment by jpanduro-blackbird** [comment]
@ankyjk Take a look at https://www.npmjs.com/package/kafkajs-lz4

**Comment by ankyjk** [comment]
I am new to Kafka Nodejs,
I am using npm to install packages, in this, there is yarn, I tried installing kafkajs-lz4 using npm, but this does not help

**Comment by ankyjk** [comment]
> @ankyjk Take a look at https://www.npmjs.com/package/kafkajs-lz4

Thanks, Worked for me
