### ISSUE TITLE
Unexpected breakdown of Kafka after every few days.

### ISSUE THREAD

**Issue by kks010** [tulios/kafkajs#624]
```
[2020-01-04T05:51:52.278Z] ERROR: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"ERROR","timestamp":"2020-01-04T05:51:49.428Z","logger":"kafkajs","message":"[Connection] Response SyncGroup(key: 14, version: 1)","broker":"kafka-1.kafka.default.svc.cluster.local:9092","clientId":"plus1connect","error":"The coordinator is not aware of this member","correlationId":307,"size":14}
[2020-01-04T05:51:57.986Z] ERROR: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"ERROR","timestamp":"2020-01-04T05:51:57.986Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNumberOfRetriesExceeded: The coordinator is not aware of this member","groupId":"plus1connect-group-api-gateway-service-f0e0c0fd-7e68-43d6-b66f-b99746d96d08","retryCount":0,"stack":"KafkaJSNumberOfRetriesExceeded\n Caused by: KafkaJSProtocolError: The coordinator is not aware of this member\n at createErrorFromCode (/usr/src/app/node_modules/kafkajs/src/protocol/error.js:536:10)\n at Object.parse (/usr/src/app/node_modules/kafkajs/src/protocol/requests/syncGroup/v0/response.js:24:11)\n at Connection.send (/usr/src/app/node_modules/kafkajs/src/network/connection.js:306:35)\n at runMicrotasks ()\n at processTicksAndRejections (internal/process/task_queues.js:93:5)\n at async Broker.syncGroup (/usr/src/app/node_modules/kafkajs/src/broker/index.js:384:12)\n at async ConsumerGroup.sync (/usr/src/app/node_modules/kafkajs/src/consumer/consumerGroup.js:153:34)\n at async /usr/src/app/node_modules/kafkajs/src/consumer/runner.js:50:9\n at async /usr/src/app/node_modules/kafkajs/src/consumer/runner.js:348:11"}
[2020-01-04T05:51:58.088Z] ERROR: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"ERROR","timestamp":"2020-01-04T05:51:58.088Z","logger":"kafkajs","message":"[Connection] Response LeaveGroup(key: 13, version: 1)","broker":"kafka-1.kafka.default.svc.cluster.local:9092","clientId":"plus1connect","error":"The coordinator is not aware of this member","correlationId":308,"size":10}
[2020-01-04T05:51:58.089Z] INFO: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"INFO","timestamp":"2020-01-04T05:51:58.089Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"plus1connect-group-api-gateway-service-f0e0c0fd-7e68-43d6-b66f-b99746d96d08"}
[2020-01-04T05:51:58.089Z] ERROR: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"ERROR","timestamp":"2020-01-04T05:51:58.089Z","logger":"kafkajs","message":"[Consumer] Restarting the consumer in 6891ms","retryCount":0,"retryTime":6891,"groupId":"plus1connect-group-api-gateway-service-f0e0c0fd-7e68-43d6-b66f-b99746d96d08"}
[2020-01-04T05:52:03.680Z] INFO: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"INFO","timestamp":"2020-01-04T05:52:01.381Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"plus1connect-group-api-gateway-service-ad8900af-7e4f-42d7-bb06-1ef8a1b450e8","memberId":"plus1connect-a61bb0b2-45c1-4127-bf28-32d1046ab5e4","leaderId":"plus1connect-a61bb0b2-45c1-4127-bf28-32d1046ab5e4","isLeader":true,"memberAssignment":{"plus1connect.geofences.request":[0]},"groupProtocol":"RoundRobinAssigner","duration":20494}
[2020-01-04T05:52:21.891Z] INFO: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"INFO","timestamp":"2020-01-04T05:52:21.082Z","logger":"kafkajs","message":"[Consumer] Starting","groupId":"plus1connect-group-api-gateway-service-f0e0c0fd-7e68-43d6-b66f-b99746d96d08"}
[2020-01-04T05:54:01.982Z] ERROR: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"ERROR","timestamp":"2020-01-04T05:53:51.480Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-0.kafka.default.svc.cluster.local:9092","clientId":"plus1connect"}
[2020-01-04T05:54:24.834Z] ERROR: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"ERROR","timestamp":"2020-01-04T05:54:24.834Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to seed broker, trying another broker from the list: Connection timeout","retryCount":0,"retryTime":2863}
[2020-01-04T05:54:25.081Z] ERROR: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"ERROR","timestamp":"2020-01-04T05:54:25.081Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 1)","broker":"kafka-1.kafka.default.svc.cluster.local:9092","clientId":"plus1connect","error":"The coordinator is not aware of this member","correlationId":307,"size":10}
[2020-01-04T05:54:25.106Z] ERROR: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"ERROR","timestamp":"2020-01-04T05:54:25.106Z","logger":"kafkajs","message":"[Runner] The coordinator is not aware of this member, re-joining the group","groupId":"plus1connect-group-api-gateway-service-ad8900af-7e4f-42d7-bb06-1ef8a1b450e8","memberId":"plus1connect-a61bb0b2-45c1-4127-bf28-32d1046ab5e4","error":"The coordinator is not aware of this member","retryCount":0,"retryTime":9098}
[2020-01-04T05:54:25.121Z] INFO: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"INFO","timestamp":"2020-01-04T05:54:25.121Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"plus1connect-group-api-gateway-service-ad8900af-7e4f-42d7-bb06-1ef8a1b450e8","memberId":"plus1connect-69393ed7-5f69-4f71-ad55-587b3799c6dc","leaderId":"plus1connect-69393ed7-5f69-4f71-ad55-587b3799c6dc","isLeader":true,"memberAssignment":{"plus1connect.geofences.request":[0]},"groupProtocol":"RoundRobinAssigner","duration":15}
[2020-01-04T05:54:27.951Z] INFO: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"INFO","timestamp":"2020-01-04T05:54:27.951Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"plus1connect-group-api-gateway-service-f0e0c0fd-7e68-43d6-b66f-b99746d96d08","memberId":"plus1connect-da5586ca-06a5-4919-8b43-e27b9120e702","leaderId":"plus1connect-da5586ca-06a5-4919-8b43-e27b9120e702","isLeader":true,"memberAssignment":{"plus1connect.rules.request":[0]},"groupProtocol":"RoundRobinAssigner","duration":94}
[2020-01-04T05:57:03.782Z] ERROR: rules-service/25 on plus1connect-rules-engine-846d99cd74-5qmx5: {"level":"ERROR","timestamp":"2020-01-04T05:56:56.287Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 1)","broker":"kafka-1.kafka.default.svc.cluster.local:9092","clientId":"plus1connect","error":"The coordinator is not aware of this member","correlationId":315,"size":10}
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! rules-engine-service@1.0.0 start: node index.js --mainProcess
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the rules-engine-service@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2020-01-04T05_57_40_745Z-debug.log
```

**Comment by kks010** [comment]
It works when we restart the Pod.

**Comment by kks010** [comment]
@tulios Please help on this.

**Comment by JaapRood** [comment]
The logs contain the following error message: `The coordinator is not aware of this member`. In all likeliness that processing is taking too long somewhere and the consumer's session times out.

Kafka tries to detect which of the consumers inside a consumer-group are healthy. For it to do this, it expects all consumers to send _heartbeats_ at regular intervals. If any of them don't, that node is considered to be unhealthy, triggering a rebalance event. The error you're seeing is what happens when a consumer was deemed unhealthy and still tries to consume new messages. The KafkaJS consumer automatically to recover by retrying to rejoin and the action, but only a set number of times, as the reason why it keeps timing out might be structural.

The timeout length can be configured using `sessionTimeout`, and is 30 seconds by default, which is a pretty sane default. Shorter than 10 would cause a lot extra rebalances as processing slows down and speeds up naturally. More than 60 would cause rebalances to take a very long time, slowing down overall progress that's being made, increasing consumer lag, etc. 

A better alternative to changing the timeout length is heartbeating regularly. When using [`eachMessage`](https://kafka.js.org/docs/consuming#a-name-each-message-a-eachmessage), the consumer sends a heartbeat automatically after each message that is consumed. If processing a message can take longer, consider implementing [the more advanced `eachBatch` handler](https://kafka.js.org/docs/consuming#a-name-each-batch-a-eachbatch), which provides a `heartbeat` function. 

Please note that automatically sending heartbeats with something like `setInterval` would prevent time-outs, but also defeats it's purpose as a way to measure whether processing isn't stuck. The point is to call the heartbeat as part of the processing, to indicate actual progress being made.

**Comment by kks010** [comment]
@JaapRood Thanks for the update. 
I am currently using  "**eachmessage**" for the consumer using the below code : 

await this._registerConsumer(topic, ({ topic, partition, message });

async _registerConsumer(topic, onMessage) {
    if (this.consumers[topic]) return;

    try {
      await this._checkAndCreteTopic(topic);

      const consumer = this.kafka.consumer({
        groupId: `${this.options.groupIdPrefix}-${this.options.consumerGroup}-${uuid()}`,
        maxWaitTimeInMs: this.options.maxWaitTimeInMs,
        allowAutoTopicCreation: false
      });

      this.consumers[topic] = consumer;
      await consumer.connect();

      await consumer.subscribe({
        topic: topic
      });

      **await consumer.run({
        eachMessage: onMessage,
      });**
  }
}

If I will be using **eachBatch**, will it not delay the current communication speed? Also i want to know more in details about heartbeat function and resolveOffset that how will it help me in my case.

=> resolveOffset(message.offset)
     await heartbeat() 




Also, updated error log is as follows:

2019-12-25T05:09:21.418Z] ERROR: authenticator/26 on plus1connect-authenticator-55c84fd6f-rqs84: {"level":"ERROR","timestamp":"2019-12-25T05:09:21.418Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-3.kafka.default.svc.cluster.local:9092","clientId":"plus1connect"}
[2019-12-25T05:09:21.421Z] ERROR: authenticator/26 on plus1connect-authenticator-55c84fd6f-rqs84: {"level":"ERROR","timestamp":"2019-12-25T05:09:21.421Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":0,"retryTime":581}
[2019-12-25T06:09:48.043Z] ERROR: authenticator/26 on plus1connect-authenticator-55c84fd6f-rqs84: {"level":"ERROR","timestamp":"2019-12-25T06:09:48.042Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"kafka-3.kafka.default.svc.cluster.local:9092","clientId":"plus1connect"}
[2019-12-25T06:09:48.045Z] ERROR: authenticator/26 on plus1connect-authenticator-55c84fd6f-rqs84: {"level":"ERROR","timestamp":"2019-12-25T06:09:48.045Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":0,"retryTime":6598}
[2019-12-29T21:06:36.229Z] ERROR: authenticator/26 on plus1connect-authenticator-55c84fd6f-rqs84: {"level":"ERROR","timestamp":"2019-12-29T21:06:36.228Z","logger":"kafkajs","message":"[Connection] Connection error: read ECONNRESET","broker":"kafka-3.kafka.default.svc.cluster.local:9092","clientId":"plus1connect","stack":"Error: read ECONNRESET\n    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)"}
[2019-12-29T21:06:36.230Z]  INFO: authenticator/26 on plus1connect-authenticator-55c84fd6f-rqs84: FAILED TO CREATE TOPIC
    KafkaJSConnectionError: Connection error: read ECONNRESET
        at Socket.onError (/usr/src/app/node_modules/kafkajs/src/network/connection.js:136:23)
        at Socket.emit (events.js:210:5)
        at emitErrorNT (internal/streams/destroy.js:92:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
        at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by JaapRood** [comment]
Your example, without having run it, looks fine, assuming that `onMessage` is an async function. The function you pass to `eachMessage` _should_ be async and not return until the message has been fully processed, as otherwise there's the risk of buffering messages in memory until your machine runs out and the process crashes.

If `onMessage` takes more than 30 seconds to complete, you'll see the problem as described earlier.

> If I will be using eachBatch, will it not delay the current communication speed?

There's no reason it would. You can think of `eachMessage` as a very small layer on top of `eachBatch`, designed to make some basic consuming of messages easier.

>  Also i want to know more in details about heartbeat function and resolveOffset that how will it help me in my case.

Have a look at [the documentation for `eachBatch`](https://kafka.js.org/docs/consuming#a-name-each-batch-a-eachbatch), which has descriptions of what those functions do and an example.

> FAILED TO CREATE TOPIC
KafkaJSConnectionError: Connection error: read ECONNRESET

An ECONNRESET is a low-level Node.js error, indicating a networking issue, where the node process can't seem to connect to the Kafka broker. There's about a 1001 reasons why that could happen, to your machine switching networks, going asleep, network partitions, etc. If you get stuck with that, [the Confluent Community slack](https://launchpass.com/confluentcommunity) would be a better place to ask about that.

**Comment by JaapRood** [comment]
Reflecting on what I just wrote: 

> eachMessage should be async and not return until the message has been fully processed, as otherwise there's the risk of buffering messages in memory until your machine runs out and the process crashes.

> If onMessage takes more than 30 seconds to complete, you'll see the problem as described earlier.

If `onMessage` is not asynchronous, and your client therefor buffers lots of messages, overtime this might cause Node.js / V8 to do a major garbage collection pause. That might cause your entire program to pause for anywhere from a few seconds to minutes at a time (depending on the situation). That would definitely cause the `consumer` from heartbeating in time to be considered healthy by the Kafka cluster. 

That's a bit of a theory, but worth looking into.

**Comment by kks010** [comment]
> Reflecting on what I just wrote:
> 
> > eachMessage should be async and not return until the message has been fully processed, as otherwise there's the risk of buffering messages in memory until your machine runs out and the process crashes.
> 
> > If onMessage takes more than 30 seconds to complete, you'll see the problem as described earlier.
> 
> If `onMessage` is not asynchronous, and your client therefor buffers lots of messages, overtime this might cause Node.js / V8 to do a major garbage collection pause. That might cause your entire program to pause for anywhere from a few seconds to minutes at a time (depending on the situation). That would definitely cause the `consumer` from heartbeating in time to be considered healthy by the Kafka cluster.
> 
> That's a bit of a theory, but worth looking into.

Yes @JaapRood , This is exactly what is happening.

**Comment by JaapRood** [comment]
Glad to have been of help! Since it sounds you've gotten to the root of the problem, I'll close this issue for now. Feel free to open up a new one for additional troubles / questions.

**Comment by kks010** [comment]
Hi, @JaapRood I was working on this and found error logs regarding grouping. Hope you could with the following:- 

Jan 17, 2020 @ 15:54:14.704
2020-01-17T10:24:14.704Z	INFO	log/harvester.go:251	Harvester started for file: /var/log/containers/plus1connect-authenticator-55c84fd6f-swsm2_default_plus1connect-authenticator-8e4689ca9731984d28f4c699b9bac002e4a39e3f616cf85a5e05d2bc669b0804.log
Jan 17, 2020 @ 15:54:24.877
[2020-01-17 10:24:24,876] INFO [GroupCoordinator 3]: Member plus1connect-c5d594c6-18fe-48af-9eef-24c3fe88e0a0 in group plus1connect-group-authenticator-256297f8-4159-4d2b-b2cb-487028b3fa5b has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
Jan 17, 2020 @ 15:54:24.877
[2020-01-17 10:24:24,877] INFO [GroupCoordinator 3]: Preparing to rebalance group plus1connect-group-authenticator-256297f8-4159-4d2b-b2cb-487028b3fa5b in state PreparingRebalance with old generation 1 (__consumer_offsets-43) (reason: removing member plus1connect-c5d594c6-18fe-48af-9eef-24c3fe88e0a0 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
Jan 17, 2020 @ 15:54:24.877
[2020-01-17 10:24:24,877] INFO [GroupCoordinator 3]: Group plus1connect-group-authenticator-256297f8-4159-4d2b-b2cb-487028b3fa5b with generation 2 is now empty (__consumer_offsets-43) (kafka.coordinator.group.GroupCoordinator)
Jan 17, 2020 @ 15:59:09.711
2020-01-17T10:29:09.711Z	INFO	log/harvester.go:276	File is inactive: /var/log/containers/plus1connect-authenticator-55c84fd6f-swsm2_default_migration-1c6a59a025684d14ea8cc1c4c1d9f63ba9c4fe4e16bf5dd8b8b8507c4c204414.log. Closing because close_inactive of 5m0s reached.
Jan 17, 2020 @ 15:59:19.712
2020-01-17T10:29:19.711Z	INFO	log/harvester.go:276	File is inactive: /var/log/containers/plus1connect-authenticator-55c84fd6f-swsm2_default_plus1connect-authenticator-8e4689ca9731984d28f4c699b9bac002e4a39e3f616cf85a5e05d2bc669b0804.log. Closing because close_inactive of 5m0s reached.
