### ISSUE TITLE
Producer not Able to create Topics when `allowAutoTopicCreation` is set to true

### ISSUE THREAD

**Issue by AdelUnito** [tulios/kafkajs#696]
I'm trying to create a Kafka producer using KafkaJs and AWS MSK cluster as a broker

```
this.producer = client.producer({
      allowAutoTopicCreation: true,
      createPartitioner: Partitioners.JavaCompatiblePartitioner,
});

await this.producer.connect();
await this.producer.sendBatch({ topicMessages, compression: CompressionTypes.Snappy });
```

The connection was successful to the brokers but whenever I try to publish something I keep getting this error

```
{
   "level":"ERROR",
   "logger":"kafkajs",
   "message":"[Connection] Response Metadata(key: 3, version: 5)",
   "broker":"XXXXXX:9092",
   "clientId":"MyApp",
   "error":"This server does not host this topic-partition",
   "correlationId":12,
   "size":350
}
error: unhandledRejection { KafkaJSNonRetriableError
  Caused by: KafkaJSProtocolError: This server does not host this topic-partition
    at createErrorFromCode (/../node_modules/kafkajs/src/protocol/error.js:537:10)
    at Object.parse (/../node_modules/kafkajs/src/protocol/requests/metadata/v0/response.js:56:11)
    at Connection.send (/.../node_modules/kafkajs/src/network/connection.js:311:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'KafkaJSNumberOfRetriesExceeded',

```

I'm new to the Kafka world but what I could understand from this error is that the producer is not able to find the topic and not able to create it even if the `allowAutoTopicCreation: true`

am I missing something?

Thank you for you help in Advance

**Comment by AdelUnito** [comment]
I managed to solve this issue by changing the AWS Cluster configuration, instead of using the default configuration I had to create a new cluster configuration with `auto.create.topics.enable: true`
