### ISSUE TITLE
Rare ERR_BUFFER_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by goriunov** [tulios/kafkajs#715]
**Describe the bug**

During chaos testing on latest master was able to trigger

```
[34mdebug[39m: {"timestamp":"2020-04-30T00:19:02.499Z","logger":"kafkajs","message":"consumer has stopped, disconnecting","groupId":"connector-common-integration-play-v2"}
[34mdebug[39m: {"timestamp":"2020-04-30T00:19:03.049Z","logger":"kafkajs","message":"Fetching from 12 partitions for 2 out of 2 topics","topics":["az-realtime-gtfs-vp","az-realtime-health-check"],"activeTopicPartitions":[{"topic":"az-realtime-gtfs-vp","partitions":[0,10,11,2,4,7]},{"topic":"az-realtime-health-check","partitions":[0,10,11,4,7,8]}],"pausedTopicPartitions":[]}
[34mdebug[39m: {"timestamp":"2020-04-30T00:19:03.049Z","logger":"kafkajs","message":"Connecting","broker":"xyz:9092","clientId":"kafkajs-50270","ssl":false,"sasl":false}
[34mdebug[39m: {"timestamp":"2020-04-30T00:19:03.049Z","logger":"kafkajs","message":"Connecting","broker":"xyz:9092","clientId":"kafkajs-50270","ssl":false,"sasl":false}
[34mdebug[39m: {"timestamp":"2020-04-30T00:19:03.049Z","logger":"kafkajs","message":"Connecting","broker":"xyz:9092","clientId":"kafkajs-50270","ssl":false,"sasl":false}
[34mdebug[39m: {"timestamp":"2020-04-30T00:19:05.795Z","logger":"kafkajs","message":"Request Fetch(key: 1, version: 7)","broker":"xyz:9092","clientId":"kafkajs-50270","correlationId":12,"expectResponse":true,"size":187}
[33mwarn[39m: {"timestamp":"2020-04-30T00:19:06.151Z","logger":"kafkajs","message":"Response without match","clientId":"kafkajs-50270","broker":"xyz:9092","correlationId":7}
[34mdebug[39m: {"timestamp":"2020-04-30T00:19:06.193Z","logger":"kafkajs","message":"Request Fetch(key: 1, version: 7)","broker":"xyz:9092","clientId":"kafkajs-50270","correlationId":10,"expectResponse":true,"size":235}
[34mdebug[39m: {"timestamp":"2020-04-30T00:19:06.193Z","logger":"kafkajs","message":"Request Fetch(key: 1, version: 7)","broker":"xyz:9092","clientId":"kafkajs-50270","correlationId":83,"expectResponse":true,"size":211}
Consumed 0
[33mwarn[39m: {"timestamp":"2020-04-30T00:19:06.800Z","logger":"kafkajs","message":"Response without match","clientId":"kafkajs-50270","broker":"xyz:9092","correlationId":5}
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at Buffer.readInt32BE (internal/buffer.js:361:5)
    at Decoder.readInt32 (/Users/dmitrii/Desktop/Projects/at_connector_common/node_modules/kafkajs/src/protocol/decoder.js:50:31)
    at Connection.processData (/Users/dmitrii/Desktop/Projects/at_connector_common/node_modules/kafkajs/src/network/connection.js:410:38)
    at Socket.onData (/Users/dmitrii/Desktop/Projects/at_connector_common/node_modules/kafkajs/src/network/connection.js:121:14)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)

```

Node process just died after that error
 
**To Reproduce**
Unfortunately i have encounter this particular error only once and it is hard to trigger again, running more investigations at the moment...

**Expected behavior**
Do not have this error

**Environment:**
 - OS:  Mac OS 10.15.3
 - KafkaJS version: latest master branch 
 - Kafka version: 2.3.1
 - NodeJS version: 10.16.3

**Comment by dshifley** [comment]
I have also come across this error multiple times and have had a hard time pinning it down

**Environment:**
Centos: 7.6.x
Kafka Versions: 2.3.1, 2.4.0, 2.4.1, 2.5
Node JS Version:  v10.18.0
KafkaJS version: 1.12.0


**Different scenarios**
I have run kafka servers in a cluster, 3 zookeepers and 3 kafka instances, all on different servers with replication factor of 3

I have run one single zookeeper and kafka server.


I have run consumer groups with 1 topic, 3 partitions and processed almost 3 Billion records over 2 weeks with no issue. 3 separate instances of the program

The latest run, I had 3 consumer groups, consuming 3 separate topics which all have 1 partition each. One of the programs hit the error below after about 5.5million messages consumed. The other 2 are still running with no issue

I thought maybe it was related to load on the kafka server, which caused a hiccup. But running 3 instances on the same groupId should produce the same load of total messages in/out.

My suggestion would be to change the bufferId to 64bit instead of 32 since that is what kafka is trying to give it back at boundsError (internal/buffer.js:47:11)\n    at Buffer.readInt32BE (internal/buffer.js:361:5)\n

I am going to try upgrading to the latest version of node and seeing if that helps

**Specific Error message**
{"level":"ERROR","timestamp":"2020-05-10T19:13:00.059Z","logger":"kafkajs","message":"[Connection] Response Fetch(key: 1, version: 7)","broker":"ip:9092","clientId":"kafkajs","error":"Attempt to write outside buffer bounds","correlationId":8,"size":1048655}
{"level":"ERROR","timestamp":"2020-05-10T19:13:00.060Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNumberOfRetriesExceeded: Attempt to write outside buffer bounds","groupId":"groupId","retryCount":3,"stack":"KafkaJSNonRetriableError\n  Caused by: RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds\n    at boundsError (internal/buffer.js:47:11)\n    at Buffer.readInt32BE (internal/buffer.js:361:5)\n    at Decoder.readInt32 (/node_modules/kafkajs/src/protocol/decoder.js:50:31)\n    at module.exports (/node_modules/kafkajs/src/protocol/recordBatch/v0/decoder.js:41:40)\n    at decodeMessages (/node_modules/kafkajs/src/protocol/requests/fetch/v4/decodeMessages.js:27:35)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"level":"ERROR","timestamp":"2020-05-10T19:13:00.067Z","logger":"kafkajs","message":"[Consumer] Restarting the consumer in 730ms","retryCount":3,"retryTime":730,"groupId":"groupId"}


**The kafka server produced this log**

[2020-05-10 17:42:42,842] INFO [ProducerStateManager partition=groupId-0] Writing producer snapshot at offset 4922471 (kafka.log.ProducerStateManager)
[2020-05-10 17:42:42,843] INFO [Log partition=groupId-0, dir=/opt/kafka/datafiles/kafka-logs-1] Rolled new log segment at offset 4922471 in 10 ms. (kafka.log.Log)
[2020-05-10 17:48:40,019] INFO [GroupCoordinator 1]: Member[group.instance.id None, member.id kafkajs-6202ff7b-8d95-4dc3-9828-2ba0dd802078] in group groupId has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2020-05-10 17:48:40,019] INFO [GroupCoordinator 1]: Preparing to rebalance group groupId in state PreparingRebalance with old generation 1 (__consumer_offsets-36) (reason: removing member kafkajs-6202ff7b-8d95-4dc3-9828-2ba0dd802078 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2020-05-10 17:48:40,019] INFO [GroupCoordinator 1]: Group groupId with generation 2 is now empty (__consumer_offsets-36) (kafka.coordinator.group.GroupCoordinator)
[2020-05-10 17:48:40,877] INFO [GroupCoordinator 1]: Dynamic Member with unknown member id joins group groupid in Empty state. Created a new member id kafkajs-6d50c1c3-d0ac-4061-a30f-769f8fac3ef4 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)

**Comment by Nevon** [comment]
It looks like your two issues are actually unrelated. The first one is coming from the connection (before we even get into parsing the actual message protocol), when we try to read the correlation id from the response. The second issue is when trying to decode a RecordBatch.

For the second issue, there's some really tricky situations involving partial RecordBatches, or batches that contain both the older MessageSet *and* the newer RecordBatch (or even partials of them both). My unsubstantiated guess at this point would be that this is happening due to a version upgrade at some point. We encountered that a few years ago, and fixed the issue, but perhaps there's still some permutation of it that happens in some rare circumstance. Without having access to the actual buffer that couldn't be parsed, it's really hard to know.

What we did when this happened was to log the current offset of the consumer (and topic and partition) and then run a separate consumer that only consumed that particular offset and [logged the fetch buffer](https://kafka.js.org/docs/testing#logging) by running with extreme debug logging turned on, `KAFKAJS_LOG_LEVEL=debug KAFKAJS_DEBUG_PROTOCOL_BUFFERS=1 KAFKAJS_DEBUG_EXTENDED_PROTOCOL_BUFFERS=1`. That way we could get the exact buffer that couldn't be parsed and try to debug the issue using that.

Of course, the fetch buffer will contain whatever data it is you're consuming, so you may or may not be able to share that, depending on how sensitive the data is. If you can't share it, even privately, there's unfortunately not much we can do.

**Comment by dshifley** [comment]
Thanks @Nevon for the follow up .  A few follow up questions or comments

1) I was able to replicate this fairly consistently by putting my kafka servers into a cluster but on separate servers.  I ended up breaking my cluster, re-installing everything, and just running on a single node which seemed to stabilize the environment for now.

2) When you say record batches, I normally send 100 to 1000 records in a send call. Do you think changing that to 1 could prevent this issue? I am ok with a bit lesser performance for more reliability and would like to get back to a cluster prior to production

3) I will follow your suggestion about turning logging up once I hit the issue. my question is, do I need to start a new consumer from that offset? Or should I be able to restart my existing one since it should pick up where it left off with more logging. I should be able to share this data as it isn't super sensitive but will do it over DM

**Comment by Nevon** [comment]
I received the failing fetch response in a private message and was debugging it during the weekend. Documenting it here for posterity.

The request is a Fetch V7, which uses the V4 decodeMessages, as the recordbatch format hasn't changed. V4 decodeMessages in turn uses the RecordBatchDecoder v0. The recordbatch decoding is pretty straight forward, following [the protocol specification](https://kafka.apache.org/documentation/#recordbatch), where it first reads the base offset followed by a byte length for the batch, and then creates a new decoder by taking the length value it read.

In this case, the fetch response consists of two record sets. The first one is decoded just fine, and initially the second one is also decoded without any problem. However, at a certain point, when we read the length of the record batch we get back 0, so we end up creating a buffer of length 0 that we then try to read from. It's not a partial record set, which we've seen in the past, because the actual length of the record set buffer is correct according to the length read from the record set protocol, it's just this particular record batch in the record set that according to the protocol has a length of 0.

I considered if maybe it's possible that the protocol allows for empty record batches, although it doesn't make sense, so I tried treating it as a partial record batch and bailing out if that's the case, but it doesn't feel right since we only got through like half of the record set:

```
console.log src/protocol/decoder.js:94
    Determining if we can read another record batch {
    bufferByteLength: 1048576,
    offset: 485305,
    length: 49,
    canRead: true
    }
console.log src/protocol/requests/fetch/v4/decodeMessages.js:30
    Delegating to RecordBatchDecoder { recordsSoFar: 1981, magicByte: 2 }
console.log src/protocol/recordBatch/v0/decoder.js:33
    Starting to decode record batch {
    firstOffset: '2756082',
    length: 8761,
    decoderLength: 8761,
    fetchDecoderLength: 554498
    }
console.log src/protocol/recordBatch/v0/decoder.js:104
    Reading 36 records from RecordBatch
console.log src/protocol/decoder.js:94
    Determining if we can read another record batch {
    bufferByteLength: 1048576,
    offset: 494078,
    length: 49,
    canRead: true
    }
console.log src/protocol/requests/fetch/v4/decodeMessages.js:30
    Delegating to RecordBatchDecoder { recordsSoFar: 2017, magicByte: 2 }
console.log src/protocol/recordBatch/v0/decoder.js:33
    Starting to decode record batch {
    firstOffset: '0',
    length: 0,
    decoderLength: 0,
    fetchDecoderLength: 554486
    }
console.log src/protocol/recordBatch/v0/decoder.js:43
    Received RecordBatch with 0 length
```

A next step might be to try to manually inspect the response from the offending offset and see if it makes any kind of sense. It would also be interesting to try to decode it using some other client and see what comes out the other end.

**Comment by dshifley** [comment]
@Nevon It had been a few months. Was just checking in to see if this issue had been looked at or was on the list some where. Overall, the library is great, so this is the last remaining item that was on the list since I am running a single Kafka server as a stand alone.

Thanks!

**Comment by ksvitkovsky** [comment]
Hey @Nevon, I was able to reproduce the issue, but I'm new to Kafka and I'm not sure if that's just me doing something wrong. In a nutshell, whenever I try to consume from a topic with some unprocessed messages (current offset < log-end offset) - consumer throws `RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds`.

Steps to reproduce:
- `brew install kafka`, which got me `3.2.1`
- `zookeeper-server-start /opt/homebrew/etc/zookeeper/zoo.cfg`
- `kafka-server-start /opt/homebrew/etc/kafka/server.properties`
- `kafka-topics --boostrap-server localhost:9092 --create --topic nutopic`
- `node producer.js`
- `node consumer.js`

It works fine, however, when consumer is already running before I produce a message. I can also use `seek` to go to the last message offset and consume *new* messages in the topic, but I kinda need the old ones too 😅 

Please, let me know if you need any more details 🙏 

# Code

`producer.js`
```js
const { Kafka } = require('kafkajs');

const kafka = new Kafka({ brokers: ['localhost:9092'] });

const producer = kafka.producer();

async function produce() {
  await producer.connect();

  await producer.send({
    topic: 'nutopic',
    messages: [{ value: '123' }]
  });

  process.exit();
}

produce();
```

`consumer.js`
```js
const { Kafka } = require('kafkajs');

const kafka = new Kafka({ brokers: ['localhost:9092'] });

const consumer = kafka.consumer({
  groupId: 'js-consumer',
  sessionTimeout: 30000
});

async function consume() {
  await consumer.connect();
  await consumer.subscribe({ topic: 'nutopic' });

  await consumer.run({
    eachBatch: async payload => {
      console.log(payload.batch.messages.length);
    }
  });
}

consume();
```

**Comment by dshifley** [comment]
I randomly started getting this error again after a few years. But it was after rolling onto a new kafka server and server where the consumer runs. Both these servers were VMs like the rest, but these were completely under powered (think $40 dollar servers) and using network attached storage. My gut feeling is that there is some kind of race condition at high transaction volume and the network latency was too high.

Upgrading both servers to more dedicated boxes with "direct" attached storage seems to have resolved the issue.
