### ISSUE TITLE
[question] need help to handle some errors

### ISSUE THREAD

**Issue by JohannLai** [tulios/kafkajs#766]
**Describe the bug**
I think it is not a bug，could you tell me how to deal with these errors?
I'm not sure why there's a 403  status code. 😭 
```
{"level":"ERROR","timestamp":"2020-06-08T11:43:09.739Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 0)","broker":"10.101.193.211:9094","clientId":"xxx-push","error":"The group is rebalancing, so a rejoin is needed","correlationId":3962,"size":6}
{"level":"ERROR","timestamp":"2020-06-08T11:43:09.739Z","logger":"kafkajs","message":"[Runner] The group is rebalancing, re-joining","groupId":"wework_push","memberId":"xxx-push-/10.123.13.81-2020-06-08 14:40:48:840-efa063f9-f0c0-4a99-a6a2-44c945defc53","error":"The group is rebalancing, so a rejoin is needed","retryCount":1,"retryTime":640}
{"level":"ERROR","timestamp":"2020-06-08T11:43:39.406Z","logger":"kafkajs","message":"[Runner] Error when calling eachMessage","topic":"wework_push","partition":1,"offset":"10852","stack":"Error: Request failed with status code 403\n    at createError (/data/release/xxx/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/data/release/xxx/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/data/release/xxx/node_modules/axios/lib/adapters/http.js:237:11)\n    at IncomingMessage.emit (events.js:187:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:441:20)\n    at endReadableNT (_stream_readable.js:1094:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
```

**Comment by Nevon** [comment]
This is not an issue in KafkaJS. This is you making some HTTP request from within your `eachMessage` handler to some service that is returning a 403, which bubbles up through the error handler. You will have to debug your own code and the service you are calling to figure out why your application is not working.

**Comment by tulios** [comment]
@JohannLai  your code is failing
`Error when calling eachMessage` means that is on userland.

`Request failed with status code 403`

**Comment by JohannLai** [comment]
thanks
