### ISSUE TITLE
UnhandledPromiseRejection in beta.38

### ISSUE THREAD

**Issue by goriunov** [tulios/kafkajs#796]
**Describe the bug**

FIY, Have been running some chaos testing and stumbled on unhandled rejection in beta.38, also got the same issue during our deployment (looks like it is there for a while): 

```
(node:55902) UnhandledPromiseRejectionWarning: KafkaJSRequestTimeoutError: Request Fetch(key: 1, version: 7) timed out
    at SocketRequest.timeoutRequest (/node_modules/kafkajs/src/network/requestQueue/socketRequest.js:104:19)
    at inflight.forEach.request (/node_modules/kafkajs/src/network/requestQueue/index.js:59:21)
    at Map.forEach (<anonymous>)
    at Timeout.requestTimeoutIntervalId.setInterval (/node_modules/kafkajs/src/network/requestQueue/index.js:57:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

This usually happens after disconnect, basically we call disconnect and for some reason we get timeout after which is throwing `UnhandledPromiseRejection` i am doing more investigations around this area at the moment as this may cause issues during our zero downtime deployment. Also looks like this stack trace is useless as it only shows where the error has been created....

**Expected behavior**
To do not have unhandled rejections

**Environment:**
 - OS: [e.g. Mac OS 10.15.3] Mac OS 10.15.4
 - KafkaJS version [e.g. 1.12.0] beta.38
 - Kafka version [e.g. 2.3.1] 
 - NodeJS version [e.g. 10.13.0] 10.16.3

**Comment by Nevon** [comment]
Fixed by #797
