### ISSUE TITLE
Broker not found in the cached metadata

### ISSUE THREAD

**Issue by aaaeeeo** [tulios/kafkajs#802]
**Describe the bug**
Getting `KafkaJSNonRetriableError` when the client try to consume message:

**To Reproduce**
Blow customer code was used:
```
const kafka = new Kafka({
    clientId: options.client,
    brokers: [ bootstrap_server ]
  })

  const consumer = kafka.consumer({ groupId: group })

  const run = async () => {
    await consumer.connect()
    await consumer.subscribe({ topic: options.topic, fromBeginning: true })
    await consumer.run({
      eachMessage: async ({ topic, partition, message }) => {
        app.logger.info(message)
      }
    })
  }

  run().catch(app.logger.error)
```

**Expected behavior**
Customer should be able to read messages.

**Observed behavior**
Getting `KafkaJSNonRetriableError` with following log:
```
[Consumer] Crash: KafkaJSNumberOfRetriesExceeded: Broker 1546510463 not found in the cached metadata","groupId":"....","retryCount":5,"stack":"KafkaJSNonRetriableError\n  Caused by: KafkaJSBrokerNotFound: Broker 1546510463 not found in the cached metadata\n    at BrokerPool.findBroker (/app/node_modules/kafkajs/src/cluster/brokerPool.js:212:13)\n    at Cluster.findBroker (/app/node_modules/kafkajs/src/cluster/index.js:184:36)\n    at /app/node_modules/kafkajs/src/cluster/index.js:286:27\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at ConsumerGroup.join (/app/node_modules/kafkajs/src/consumer/consumerGroup.js:91:24)\n    at /app/node_modules/kafkajs/src/consumer/runner.js:51:9\n    at Runner.start (/app/node_modules/kafkajs/src/consumer/runner.js:105:7)\n    at start (/app/node_modules/kafkajs/src/consumer/index.js:230:7)"
```
Looks like the group coordinator broker somehow cannot be found in cached metadata?

**Environment:**
 - OS: CentOS Linux release 7.8.2003 (Core)
 - Kafka version [e.g. 2.3.1]
 - NodeJS version 12.13.1

**Additional context**
Tested using same config with Kafka-python, and it is working fine.

**Comment by Nevon** [comment]
Could you try [running the consumer with `DEBUG` log level](https://kafka.js.org/docs/configuration#logging) and posting the logs here? If the broker is not found in the metadata, we should refresh the metadata and try again.

If you aren't working with sensitive data, it would be helpful to also get response buffers to be able to see what actual metadata we got back. [This can be enabled with the environment variable `KAFKAJS_DEBUG_PROTOCOL_BUFFERS`](https://kafka.js.org/docs/testing#logging). Note that this will not include actual messages, but it can include things like hostnames, ports, etc.

**Comment by xuzaixian** [comment]
Same issue to me .

I think `kafkajs` should connect Group Coordinator with host&port when cannot found node in cahed metadata

**Comment by css-master** [comment]
up

**Comment by css-master** [comment]
please, help

**Comment by Web-Li** [comment]
同样的问题，按照官方示例写得代码，消息能发出，但是消费链接不上，请大佬帮忙
