### ISSUE TITLE
[need help]   Why can't I catch an exception? 😭

### ISSUE THREAD

**Issue by JohannLai** [tulios/kafkajs#833]
* description
There are 2 files in my consumer. I can see errrors in pm2 error log now, but I want to know how can I catch the error and report to Sentry.  Thanks teams.

```js
// index.js
import { run } from './consumer';

try {
  run();
} catch (e) {
  // HERE: cannnot log any error.
  console.error(`[consumer] ${e.message}`, e);
}

// consumer.js
import { kafka } from '../../storage/kafka';

const kafkaInstance = kafka();
const WEWORK_TOPIC = wework_push;
const WEWORK_GROUP_ID = wework_push;
const consumer = kafkaInstance.consumer({ groupId: WEWORK_GROUP_ID });

export const run = async () => {
  await consumer.connect();
  await consumer.subscribe({ topic: WEWORK_TOPIC });
  await consumer.run({
    eachMessage: async ({ topic, message }) => {
      console.log('kafka receive:', topic, parseMessageValue); 
    },
  });
};

```

Some log  I found in pm2 error log.

```json
{"level":"ERROR","timestamp":"2020-06-08T11:43:39.406Z","logger":"kafkajs","message":"[Runner] Error when calling eachMessage","topic":"xxx_push","partition":1,"offset":"10852","stack":"Error: Request failed with status code 403\n    at createError (/data/release/xxx/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/data/release/xxx/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/data/release/xxx/node_modules/axios/lib/adapters/http.js:237:11)\n    at IncomingMessage.emit (events.js:187:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:441:20)\n    at endReadableNT (_stream_readable.js:1094:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"}
```

**Comment by goriunov** [comment]
I can see few issues in here.

1. You have `run` function which is async and you are calling this function in `try` `catch` without awaiting so it will never throw in to your catch method...

2. The error you posted most likely coming from eachMessage function, there are 2 ways you get those first by using on error instrumentation from  kafka js https://kafka.js.org/docs/instrumentation-events  and second one you just wrap each of your kafka message in try catch (make sure to await things properly inside try catch) ex:

```js

   eachMessage: async ({ topic, message }) => {
         try {
              console.log('kafka receive:', topic, parseMessageValue); 
              // must properly await async things 
          } catch(err) {
             // you can re throw error if you want to
          }
    },
```

**Comment by JohannLai** [comment]
@goriunov thank you very much！
