### ISSUE TITLE
kafkaJsprotocolERROR on Kafka consumer

### ISSUE THREAD

**Issue by LakhsmiC** [tulios/kafkajs#872]
Hello All

We are running into kafkaJsprotocolERROR errors and the Consumers are not attached to the partitions once this error is observed on the pods. 
We are seeing these errors even though the Kafka servers/brokers are healthy and no issue identified on them. 
Note: Observed below errors when there is a sudden spike in traffic numbers. 

{"level":"ERROR","timestamp":"2020-09-14T21:11:14.887Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSNumberOfRetriesExceeded: The coordinator is not aware of this member","groupId":"capture-abc","retryCount":0,"stack":"KafkaJSNonRetriableError\n Caused by: KafkaJSProtocolError: The coordinator is not aware of this member\n at createErrorFromCode (/opt/att/app/node_modules/kafkajs/src/protocol/error.js:537:10)\n at Object.parse (/opt/att/app/node_modules/kafkajs/src/protocol/requests/joinGroup/v0/response.js:37:11)\n at Connection.send (/opt/att/app/node_modules/kafkajs/src/network/connection.js:311:35)\n at processTicksAndRejections (internal/process/task_queues.js:97:5)\n at Broker.joinGroup (/opt/att/app/node_modules/kafkajs/src/broker/index.js:351:12)\n at ConsumerGroup.join (/opt/att/app/node_modules/kafkajs/src/consumer/consumerGroup.js:93:23)\n at /opt/att/app/node_modules/kafkajs/src/consumer/runner.js:51:9"} 

Can you please share your thoughts on this. This error is giving hard time for us on production. 

Thanks
Lakshmi

**Comment by tulios** [comment]
Hi @LakhsmiC, this is a recoverable error, so it shouldn't bubble up and crash your application. Which version of KafkaJS and Kafka are you using? This error also means that your consumer was marked as dead by Kafka; you probably took too long to process an event without heart beating, making the broker kick the consumer out of the group.

**Comment by LakhsmiC** [comment]
Hello, 
Thank you for your prompt response. 
The Kafka version is kafka_2.12-2.3.1, Kafkajs client version is "kafkajs": "1.12.0". The heartbeat interval is 4000ms (4seconds).
So, do you think the heartbeat interval is not appropriate and needs to be brought down to a lower value to avoid such issues?

**Comment by tulios** [comment]
The heartbeat interval value looks ok. KafkaJS doesn't heartbeat in the background, so it heartbeats in between each message, if to process a single message you need more time than the heartbeat interval it is recommended to either increase the value or to switch to each batch and heartbeat while processing the message. The each batch handler gives you access to the heartbeat function.

**Comment by LakhsmiC** [comment]
Thank you so much  for clarifying on that. It helps in analysing the error. We commit every 300 messages upon consuming the messages. So does it wait for all 300 messages to be committed first and then poll a heartbeat . Or will it poll a heartbeat once each message is consumed .
Note: All the data we consume and process are asynchronous.

**Comment by tulios** [comment]
No, it tries to heartbeat in between each message if it is necessary. It works differently for `eachBatch` as you have access to heartbeat, for `eachMessage` it works like this:

if you have messages: `[1, 2, 3]`
```
1
# heartbeat if necessary (now - last heartbeat < interval config)
2
# heartbeat if necessary ...
3
# ...
```
