### ISSUE TITLE
Consumer member assignment only shows single topic

### ISSUE THREAD

**Issue by rohit-rapido** [tulios/kafkajs#891]
A consumer is running with groupId as GROUP-1, and a topic TOPIC-1. With a new change, two new topics(TOPIC-2, TOPIC-3) were created and which were supposed to join the same group (GROUP-1).
After starting the server, I observe that the consumer is starting with only topic TOPIC-1 and not consuming any message from TOPIC-2 and TOPIC-3.

In the logs I observe the below log
```
{"level":"INFO","timestamp":"2020-09-25T06:50:31.016Z","logger":"kafkajs","message":"[Runner] Consumer has joined the group","groupId":"GROUP-1","memberId":"Listener-59a354e3-3d8d-417e-9d86-0bc8b003b27f","leaderId":"Listener-32cd1b4d-ad02-42a1-a549-a14e4c68fbe6","isLeader":false,"memberAssignment":{"TOPIC-1":[10,14,18,2,6]},"groupProtocol":"RoundRobinAssigner","duration":22042}
```
There is no specific log in the debug log either.
Even after keeping the server on for 2.hrs, the consumer did not start.
The topic creation happened 3 weeks back and consumption was to start today. new topics never had any data prior to today.

**Environment:**
 - OS: [e.g. Mac OS 10.14.6]
 - KafkaJS version [e.g. 1.14.0]
 - Kafka version [e.g. 2.0.4]
 - NodeJS version [e.g. 12.18.0]

One observation. When I start a new consumer with different group and clientId but only subscribe to TOPIC-2 and TOPIC-3 then it starts consuming the messages.

**Comment by Nevon** [comment]
Can you share some code to reproduce what you are doing? I wrote a test case doing exactly what you described, and the consumer is assigned to all partitions as expected:

```js
const fs = require('fs')
const ip = require('ip')

const { Kafka, logLevel } = require('../index')
const PrettyConsoleLogger = require('./prettyConsoleLogger')

const host = process.env.HOST_IP || ip.address()

const kafka = new Kafka({
  logLevel: logLevel.INFO,
  logCreator: PrettyConsoleLogger,
  brokers: [`${host}:9094`, `${host}:9097`, `${host}:9100`],
  clientId: 'example-consumer',
  ssl: {
    servername: 'localhost',
    rejectUnauthorized: false,
    ca: [fs.readFileSync('./testHelpers/certs/cert-signed', 'utf-8')],
  },
  sasl: {
    mechanism: 'plain',
    username: 'test',
    password: 'testtest',
  },
})

// I first ran this once with just the first topic, then again with all topics
const topics = ['topic-test-issue-891-a', 'topic-test-issue-891-b', 'topic-test-issue-891-c']

const consumer = kafka.consumer({ groupId: 'test-group-issue-891' })
const admin = kafka.admin()

const run = async () => {
  await admin.connect()
  await admin.createTopics({ topics: topics.map(topic => ({ topic, numPartitions: 6 })) })
  await admin.disconnect()

  await consumer.connect()

  for (const topic of topics) {
    await consumer.subscribe({ topic, fromBeginning: true })
  }

  await consumer.run({
    eachBatch: async () => {},
  })
}

run().catch(e => kafka.logger().error(`[example/consumer] ${e.message}`, { stack: e.stack }))

const errorTypes = ['unhandledRejection', 'uncaughtException']
const signalTraps = ['SIGTERM', 'SIGINT', 'SIGUSR2']

errorTypes.map(type => {
  process.on(type, async e => {
    try {
      kafka.logger().info(`process.on ${type}`)
      kafka.logger().error(e.message, { stack: e.stack })
      await consumer.disconnect()
      process.exit(0)
    } catch (_) {
      process.exit(1)
    }
  })
})

signalTraps.map(type => {
  process.once(type, async () => {
    console.log('')
    kafka.logger().info('[example/consumer] disconnecting')
    await consumer.disconnect()
  })
})
```

```
❯ node examples/consumer.js
info:  ┏ [Consumer] Starting
info:  ┃ [0] {
info:  ┃ [1]   "timestamp": "2020-09-25T08:05:34.555Z",
info:  ┃ [2]   "logger": "kafkajs",
info:  ┃ [3]   "groupId": "test-group-issue-891"
info:  ┗ [4] }
info:  ┏ [Runner] Consumer has joined the group
info:  ┃ [ 0] {
info:  ┃ [ 1]   "timestamp": "2020-09-25T08:05:34.686Z",
info:  ┃ [ 2]   "logger": "kafkajs",
info:  ┃ [ 3]   "groupId": "test-group-issue-891",
info:  ┃ [ 4]   "memberId": "example-consumer-edd9ead4-5bd9-4a8d-8fc0-d76b86ca9e91",
info:  ┃ [ 5]   "leaderId": "example-consumer-edd9ead4-5bd9-4a8d-8fc0-d76b86ca9e91",
info:  ┃ [ 6]   "isLeader": true,
info:  ┃ [ 7]   "memberAssignment": {
info:  ┃ [ 8]     "topic-test-issue-891-a": [
info:  ┃ [ 9]       0,
info:  ┃ [10]       1,
info:  ┃ [11]       2,
info:  ┃ [12]       3,
info:  ┃ [13]       4,
info:  ┃ [14]       5
info:  ┃ [15]     ]
info:  ┃ [16]   },
info:  ┃ [17]   "groupProtocol": "RoundRobinAssigner",
info:  ┃ [18]   "duration": 128
info:  ┗ [19] }
^C
info:  ┏ [example/consumer] disconnecting
info:  ┃ [0] {
info:  ┃ [1]   "timestamp": "2020-09-25T08:05:39.199Z",
info:  ┃ [2]   "logger": "kafkajs"
info:  ┗ [3] }
info:  ┏ [Consumer] Stopped
info:  ┃ [0] {
info:  ┃ [1]   "timestamp": "2020-09-25T08:05:39.896Z",
info:  ┃ [2]   "logger": "kafkajs",
info:  ┃ [3]   "groupId": "test-group-issue-891"
info:  ┗ [4] }

# Updated with all topics
❯ node examples/consumer.js
error: ┏ [Connection] Response CreateTopics(key: 19, version: 2)
error: ┃ [0] {
error: ┃ [1]   "timestamp": "2020-09-25T08:05:52.853Z",
error: ┃ [2]   "logger": "kafkajs",
error: ┃ [3]   "broker": "localhost:9094",
error: ┃ [4]   "clientId": "example-consumer",
error: ┃ [5]   "error": "Topic with this name already exists",
error: ┃ [6]   "correlationId": 2,
error: ┃ [7]   "size": 142
error: ┗ [8] }
info:  ┏ [Consumer] Starting
info:  ┃ [0] {
info:  ┃ [1]   "timestamp": "2020-09-25T08:05:52.959Z",
info:  ┃ [2]   "logger": "kafkajs",
info:  ┃ [3]   "groupId": "test-group-issue-891"
info:  ┗ [4] }
info:  ┏ [Runner] Consumer has joined the group
info:  ┃ [ 0] {
info:  ┃ [ 1]   "timestamp": "2020-09-25T08:05:53.006Z",
info:  ┃ [ 2]   "logger": "kafkajs",
info:  ┃ [ 3]   "groupId": "test-group-issue-891",
info:  ┃ [ 4]   "memberId": "example-consumer-692cccaf-fceb-4b08-a9a0-2356d2896094",
info:  ┃ [ 5]   "leaderId": "example-consumer-692cccaf-fceb-4b08-a9a0-2356d2896094",
info:  ┃ [ 6]   "isLeader": true,
info:  ┃ [ 7]   "memberAssignment": {
info:  ┃ [ 8]     "topic-test-issue-891-a": [
info:  ┃ [ 9]       0,
info:  ┃ [10]       1,
info:  ┃ [11]       2,
info:  ┃ [12]       3,
info:  ┃ [13]       4,
info:  ┃ [14]       5
info:  ┃ [15]     ],
info:  ┃ [16]     "topic-test-issue-891-b": [
info:  ┃ [17]       0,
info:  ┃ [18]       1,
info:  ┃ [19]       2,
info:  ┃ [20]       3,
info:  ┃ [21]       4,
info:  ┃ [22]       5
info:  ┃ [23]     ],
info:  ┃ [24]     "topic-test-issue-891-c": [
info:  ┃ [25]       0,
info:  ┃ [26]       1,
info:  ┃ [27]       2,
info:  ┃ [28]       3,
info:  ┃ [29]       4,
info:  ┃ [30]       5
info:  ┃ [31]     ]
info:  ┃ [32]   },
info:  ┃ [33]   "groupProtocol": "RoundRobinAssigner",
info:  ┃ [34]   "duration": 44
info:  ┗ [35] }
```

**Comment by ankon** [comment]
I bit of a guess: The assignment looks a bit like you aren't _subscribing_ to these topics. It's not that a group is subscribed to topics, but rather each consumer needs to both use the same group id _and_ subscribe to all topics that should be consumed.

**Comment by rohit-rapido** [comment]
@ankon afaik consumers of a consumer group will subscribe to a topic provided.
@Nevon 
Please find the sample code :
```
const {Kafka, logLevel} = require('kafkajs');
const logger            = require('./logger');
const config            = require('../config');
const kafkaHost         = config.kafkaClient.kafkaHost;
const kafkaHosts        = kafkaHost.split(',');
const topicMap          = config.kafkaClient.topics;
const Handler           = require('../').Handler;

const kafka = new Kafka({
    clientId: 'Listener-1',
    brokers: kafkaHosts,
    connectionTimeout: 3000,
    logLevel: logLevel.INFO
});
const admin = kafka.admin();
const consumer = kafka.consumer({ groupId: "Group-1" });

class KafkaListener {
    async init() {
        try {
            await consumer.connect();
            logger.info(`Kafka consumer connected;`)
        } catch(err) {
            logger.error("Consumer Connection Error", err);
        }
        try {
            await consumer.subscribe({topic: topicMap.TOPIC1, fromBeginning: false});
            consumer.logger().setLogLevel(logLevel.ERROR);
        } catch (err) {
            logger.error(topicMap.TOPIC1, "Consumer Connection Error", err);
        }
        try {
            await consumer.subscribe({topic: topicMap.TOPIC2, fromBeginning: true});
            consumer.logger().setLogLevel(logLevel.DEBUG)
        } catch (err) {
            logger.error(topicMap.TOPIC2, "Consumer Connection Error", err);
        }
        try {
            await consumer.subscribe({topic: topicMap.TOPIC3, fromBeginning: true});
        } catch (err) {
            logger.error(topicMap.TOPIC3, "Consumer Connection Error", err);
        }

        await consumer.run({
            eachMessage: async ({ topic, partition, message }) => {
                try {
                    message = message.value.toString();
                    await this.processMessage(message, topic);
                } catch (err) {
                    logger.error("error in processing message");
                }
            }
        });
    }

    async processMessage(message, topic){
        switch (topic) {
            case topicMap.TOPIC1 :
                await this.processTopic1(message);
                break;
            case topicMap.TOPIC2 :
                await this.processTopic2(message);
                break;
            case topicMap.Process :
                await this.processTopic3(message);
                break;
            default :
                break;

        }
    }


    async processTopic1(message){
        let logMsg = {
            message: "Processing TOPIC1",
            data: message
        };
        try {
            let body = JSON.parse(message);
            const resp = await Handler.initiateTransactionForTopic1(body);
            logMsg.message = "processed TOPIC1";
            logMsg.resp = resp;
            logger.info(logMsg);
        } catch (e) {
            logMsg.message = "Error in TOPIC1";
            logMsg.error = e;
            logger.error(logMsg);
        }

    }

    async processTopic2(message){
        let logMsg = {
            message: "Processing TOPIC2 Events",
            data: message
        };
        try {
            let body = JSON.parse(message);
            const resp = await Handler.initiateTransactionForTopic2(body);
            logMsg.message = "processed TOPIC2";
            logMsg.resp = resp;
            logger.info(logMsg);
        } catch (e) {
            logMsg.message = "Error in TOPIC2";
            logMsg.error = e;
            logger.error(logMsg);
        }

    }


    async processTopic3(message){
        let logMsg = {
            message: "Processing TOPIC3 Events",
            data: message
        };
        try {
            let body = JSON.parse(message);
            const resp = await Handler.initiateTransactionForTopic3(body);
            logMsg.message = "processed  TOPIC3";
            logMsg.resp = resp;
            logger.info(logMsg);
        } catch (e) {
            logMsg.message = "Error in  TOPIC3";
            logMsg.error = e;
            logger.error(logMsg);
        }

    }
}

const kafkaListener = new KafkaListener();

module.exports = {
    KafkaListener : kafkaListener,
    client : admin,
    consumer
};
```

**Comment by Nevon** [comment]
> afaik consumers of a consumer group will subscribe to a topic provided.

Each consumer in the consumer group has to subscribe to the topics, but judging from your code, that is being done (although you're ignoring any errors during subscription). Are you sure you're not getting any errors? I'm just guessing here, but maybe you have ACLs set on the topics so that your consumer group is not allowed to read from them.

**Comment by rohit-rapido** [comment]
@Nevon 
All the consumer statements are under try catch, for any error there would be some log, but no logs are printed.
Sure I will check if there are any ACLs set to the new topics.

As I said earlier, when I create a new group, it works smoothly. Additionally, the data in each message is just few bytes.
I also observed some kafka server logs :
```
[2020-09-25 01:23:16,542] ERROR [ReplicaManager broker=1] Error processing fetch with max size -2147483648 from consumer on partition __consumer_offsets-11: (fetchOffset=776351504, logStartOffset=-1, maxBytes=-2147483648, currentLeaderEpoch=Optional.empty) (kafka.server.ReplicaManager)
java.lang.IllegalArgumentException: Invalid max size -2147483648 for log read from segment FileRecords(size=9030, file=/var/lib/kafka/data/__consumer_offsets-11/00000000000000000000.log, start=0, end=2147483647)
	at kafka.log.LogSegment.read(LogSegment.scala:296)
	at kafka.log.Log.$anonfun$read$2(Log.scala:1517)
	at kafka.log.Log.read(Log.scala:2335)
	at kafka.cluster.Partition.$anonfun$readRecords$1(Partition.scala:992)
	at kafka.cluster.Partition.readRecords(Partition.scala:982)
	at kafka.server.ReplicaManager.read$1(ReplicaManager.scala:1008)
	at kafka.server.ReplicaManager.$anonfun$readFromLocalLog$8(ReplicaManager.scala:1080)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at kafka.server.ReplicaManager.readFromLocalLog(ReplicaManager.scala:1079)
	at kafka.server.ReplicaManager.readFromLog$1(ReplicaManager.scala:893)
	at kafka.server.ReplicaManager.fetchMessages(ReplicaManager.scala:898)
	at kafka.server.KafkaApis.handleFetchRequest(KafkaApis.scala:811)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:128)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:70)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Nevon** [comment]
That error is interesting, but it shouldn't affect partition assignment. The consumer should still be assigned to partitions for the new topics, even if fetching from them fails.

The error looks like an integer overflow to me. This is the only reference I can find, but it doesn't really explain what's happening: https://issues.apache.org/jira/browse/KAFKA-7656

Is the configuration for the client (`new Kafka({ ... })`) the exact same as what you're using in production? We default the values for `maxBytes` and `maxBytesPerPartition` to 10mb and 1mb respectively, so it would be far from overflowing. However, the broker actually overwrites this on their side based on throttling quotas (https://github.com/apache/kafka/commit/587e43d18e8ae7c9fa401d57e06652d5c2eea35c#diff-ccd0deee5adb38987e4f009b749fd11c), so it's possible there's a broker bug causing this overflow.

**Comment by rohit-rapido** [comment]
Yeah, there is no change in the configuration. All envs have exact same config.

**Comment by rohit-rapido** [comment]
Hey @Nevon any new update on this ?

**Comment by Nevon** [comment]
There's not really much I can do given that there's no way to reproduce the issue and no more information provided. I am fairly confident that this is an issue in your environment, but I have nothing else to go on. 

I would first suggest that you run with debug log level to see if there are any hints in there. That will tell us if you are actually assigned those topic-partitions.

The admin client has a number of operations to describe topics and consumer groups, which would be interesting to see.
