### ISSUE TITLE
my connection end before create topic and give me this error

### ISSUE THREAD

**Issue by mohammedzourob99** [tulios/kafkajs#969]
```
[Connection] Connection error: write after end","broker":"localhost:29092","clientId":"notification-app","stack":"Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at Socket.Writable.write (_stream_writable.js:292:11)
    at Object.sendRequest (/home/error/Desktop/Cudy_3.0/notification-microservice/node_modules/kafkajs/src/network/connection.js:312:27)
    at SocketRequest.send [as sendRequest] (/home/error/Desktop/Cudy_3.0/notification-microservice/node_modules/kafkajs/src/network/requestQueue/index.js:135:23)
    at SocketRequest.send (/home/error/Desktop/Cudy_3.0/notification-microservice/node_modules/kafkajs/src/network/requestQueue/socketRequest.js:85:10)
    at RequestQueue.sendSocketRequest (/home/error/Desktop/Cudy_3.0/notification-microservice/node_modules/kafkajs/src/network/requestQueue/index.js:164:19)
    at RequestQueue.push (/home/error/Desktop/Cudy_3.0/notification-microservice/node_modules/kafkajs/src/network/requestQueue/index.js:144:12)
    at /home/error/Desktop/Cudy_3.0/notification-microservice/node_modules/kafkajs/src/network/connection.js:307:29
    at new Promise (<anonymous>)
    at sendRequest (/home/error/Desktop/Cudy_3.0/notification-microservice/node_modules/kafkajs/src/network/connection.js:302:14)
    at async Connection.send (/home/error/Desktop/Cudy_3.0/notification-microservice/node_modules/kafkajs/src/network/connection.js:321:53)
```

**Comment by Nevon** [comment]
Closing this in favor of #1074, where we have a way to reproduce the issue. I believe the issues are the same.
